loculus-project/loculus

README.md

Update README to point directly at loculus.org

---

kubernetes/loculus/values.yaml

fix(website): Update plausible domain for preview

---

.github/workflows/docs-deploy.yml

We need to add this CNAME or we lose our Github custom domain with every deployment

Add CNAME with docs deployment

---

ena-submission/README.md
ena-submission/Snakefile
ena-submission/scripts/call_loculus.py
ena-submission/scripts/get_ena_submission_list.py
ena-submission/scripts/submission_db_helper.py

Just putting these out there to prevent merge conflicts in case you keep editing the base @anna-parker 
Probably best to merge these sooner. Also, it's fine with me to pile all the PRs up into one, to some extent it feels like some bits and pieces are missing (maybe part of the other PRs).

[For Anya] Edits while PR reviewing create ena projects

---

kubernetes/loculus/values.yaml

preview URL: https://silo0216.loculus.org

chore(kubernetes): update SILO 0.2.16 - fix unaligned sequences bugs

---

website/src/styles/mdcontainer.scss

Used for https://github.com/pathoplexus/pathoplexus/pull/63

feat(website): add FAQ header styling

---

docs/src/content/docs/introduction/current-state-and-roadmap.md

We were referencing this but not including it - and it does seem a useful thing to include

docs: Add Known Instances to roadmap

---

preprocessing/nextclade/src/loculus_preprocessing/prepro.py

Preview: https://revert-2676-segments-alig.loculus.org/
This reverts commit 658fac5eb72748f203bea95116fdaa9a9cce1601.
This accepts things even if they don't align

Revert fix(prepro): Raise warning if not all input segments align (#2676)

---

kubernetes/loculus/values.yaml

https://update-silo.loculus.org

chore: update SILO to v0.2.17

---

website/src/components/SearchPage/DownloadDialog/generateDownloadUrl.ts

preview URL: https://reverthotfix.loculus.org/
reverting the commits:
9eed2bc54ee55047d9834c8824c3971485879b48
565cc79f264fed135513f5b8a9281b1389bb39fd
Now that SILO 0.2.16 fixed the issues

fix(website): revert hotfix

---

.github/workflows/backend-tests.yml
.github/workflows/ingest-tests.yaml
.github/workflows/website-tests.yml

chore(ci): Use Github actions for everything now that AWS free credits have run out

---

kubernetes/loculus/templates/lapis-silo-deployment.yaml
kubernetes/loculus/values.yaml

resolves #
preview URL: https://add-count-in-header-test.loculus.org/
Wow the installation actually works... however then I can't run the script...

Add_count_in_header_test

---

deploy.py

resolves https://github.com/loculus-project/loculus/issues/2806
preview URL: https://deploy-clean.loculus.org/

feat(ci): Make deploy script cleaner: use temp file, add logs

---

ingest/environment.yml

resolves https://github.com/loculus-project/loculus/issues/2828
preview URL: https://fix-nci-datasets.loculus.org/
Apply error log suggestions (see below) and update the datasets package.
```
For best results
1. Make sure to use --as-json-lines with the datasets command
2. Make sure that you're using the latest version of the datasets command line tool
```
Sequences are showing up again for cchf and west nile:

feat(ingest): Update datasets package in ingest

---

kubernetes/loculus/templates/ingest-deployment.yaml

https://remove-reloader-from-cron.loculus.org/

Remove reloader from CronJob

---

.github/workflows/ena-submission-tests.yaml

fix(ci): use ubuntu-latest instead of codebuild

---

preprocessing/nextclade/src/loculus_preprocessing/prepro.py
preprocessing/nextclade/src/loculus_preprocessing/processing_functions.py

resolves https://github.com/loculus-project/loculus/issues/2886
preview URL: https://prepro-patch.loculus.org/
Test on preview:
Depending on how fast we want this rolled out we can wait on tests or merge this as is. I didn't find any other immediate exception handling issues in the preprocessing_functions.py file, but I added some TODOs for other small issues I found.

fix(prepro): Add execption handling to identity and call_function

---

kubernetes/loculus/templates/ingest-config.yaml

fix(ena-submission, ingest): actually add flag for ingest to check schema

---

kubernetes/loculus/templates/ingest-config.yaml

fix(config): helm default removed

---

kubernetes/loculus/templates/ena-submission-config.yaml
kubernetes/loculus/templates/ingest-config.yaml
kubernetes/loculus/templates/ingressroute.yaml
kubernetes/loculus/templates/loculus-preprocessing-deployment.yaml
kubernetes/loculus/values_preview_server.yaml

Adds basic auth for keycloak for use on staging with a sealed secret
https://basic-auth-keycloak.loculus.org/
loculus / widetailpotato

feat(deployment): Add basic-auth to keycloak

---

ena-submission/config/defaults.yaml
ingest/config/defaults.yaml

fix(ingest): Change to ingest/ena-submission to debug log level

---

docs/src/team.json

docs: change Jonas' last name

---

docs/src/content/docs/for-administrators/my-first-loculus.md
docs/src/content/docs/introduction/current-state-and-roadmap.md

Using prettier to fix formatting of the docs

docs: fix formatting

---

website/.eslintrc.cjs

Instead we simply turn them off directly

chore(website): don't `override` eslint rules that we set ourselves to `error`

---

docs/src/content/docs/for-administrators/my-first-loculus.md

docs: fix typo in my-first-loculus.md

---

ena-submission/.gitignore
ena-submission/Snakefile
ena-submission/scripts/create_assembly.py
ena-submission/scripts/create_project.py
ena-submission/scripts/deposition_dry_run.py
ena-submission/scripts/ena_submission_helper.py
ena-submission/scripts/test_ena_submission.py
ena-submission/test/text_project_request.xml

resolves #2977, relates to #2983
preview URL: https://project-cleanup.loculus.org/
1. Improve project by adding center name to project name and title (name=link and title=right below link of project shown in picture below)
2. Clean up address in manifest to also include center name
3. Improve error logging by printing contents of all files
New projects will have this name/title/description
Name: `West Nile Virus: Genome sequencing by Test institution`
Title: `West Nile Virus: Genome sequencing by Test institution, city, country`
Description: `Automated upload of West Nile Virus sequences submitted by Test institution, city, country to Loculus`

feat(ena-deposition): Small tweaks to uploaded metadata in manifest and project

---

kubernetes/loculus/templates/keycloak-database-service.yaml

fix(kubernetes): use correct config value to disable local Keycloak DB service

---

backend/build.gradle
backend/src/test/kotlin/org/loculus/backend/SpringBootTestWithoutDatabase.kt

Update spring 3.3.3 -> 3.3.4 and fix a bug that came up.
- ~All necessary documentation has been adapted.~
- ~The implemented feature is covered by an appropriate test.~

chore: Bump spring boot to 3.3.4

---

kubernetes/loculus/values.yaml

preview URL: https://silo031.loculus.org/
Changelog:
* **preprocessing:** error on duplicate primary keys ([687c3ef](https://github.com/GenSpectrum/LAPIS-SILO/commit/687c3ef8803c3dee19b222bcb790bbc4fb33cabe)) https://github.com/GenSpectrum/LAPIS-SILO/pull/624
* validate the column types earlier to prevent duckdb auto-casting to cast types with differing round-trip conversions ([ac238b2](https://github.com/GenSpectrum/LAPIS-SILO/commit/ac238b208a02a7b00bdab92ff3039562e2a1d704)) https://github.com/GenSpectrum/LAPIS-SILO/pull/624

chore(kubernetes): silo 0.3.1

---

kubernetes/loculus/values.yaml

doc: add comment to country list in values.yaml

---

docs/src/content/docs/for-users/approve-submissions.md
docs/src/content/docs/for-users/create-manage-groups.md
docs/src/content/docs/for-users/submit-sequences.md

I copied over the API submission documentation from Pathoplexus with small modifications.
See https://docs-docs-api-submission.loculus.org/for-users/submit-sequences/#api and https://docs-docs-api-submission.loculus.org/for-users/approve-submissions/#api

docs: sequence submission and submission approval

---

kubernetes/loculus/values.yaml

Parallel change to https://github.com/pathoplexus/pathoplexus/pull/294

fix: use github pages to host sequences not raw.githubusercontent to avoid 403 errors/rate limits

---

CONTRIBUTING.md

Discussion: https://loculus.slack.com/archives/C05G172HL6L/p1728396826684719

docs: mention breaking changes in contributing.md

---

README.md

Just some capitalization, links, "authorization" -> "authentication"

feat(docs): small readme improvements

---

preprocessing/nextclade/src/loculus_preprocessing/processing_functions.py
preprocessing/nextclade/tests/test_processing_functions.py

Date-ranges-test-fixes

---

website/src/config.ts
website/src/middleware.ts

See https://github.com/withastro/astro/issues/12527
Discussed here: https://loculus.slack.com/archives/C05G172HL6L/p1733245136034479
Required to allow Astro version >=4.16.14
https://astro-upgrade.loculus.org

fix(website): work around astro bug executing middleware at build time

---

.github/dependabot.yml

see https://github.com/loculus-project/loculus/issues/3305
see https://github.com/loculus-project/loculus/issues/3295

chore(deps): disable unupgradable deps in dependabot.yaml

---

preprocessing/nextclade/src/loculus_preprocessing/backend.py

preview URL: https://no-crash.loculus.org
- Backend sometimes sends error message rather than valid ndjson in `extract-unprocessed-entries` response, in particular when there's more than 1 prepro pipeline replicate
- Prepro shouldn't crash for known issues, just sleep for a bit then continue

fix(prepro): don't crash when backend sends error instead of valid ndjson

---

preprocessing/nextclade/src/loculus_preprocessing/backend.py

fix(prepro): avoid type error when raising exception

---

website/src/pages/index.astro

Limits organisms to be 3 wide when there are 5 organisms
https://theosanderson-patch-1.loculus.org/

feat(website): Limit organism card container width when there are 5 organisms

---

ena-submission/src/ena_deposition/config.py

fix(ingest): Fix stupid bug

---

website/src/pages/index.astro

See https://loculus.slack.com/archives/C07K8UDNNUS/p1733768136304609?thread_ts=1733765846.984079&cid=C07K8UDNNUS
preview URL: https://center-cards.loculus.org
- Center organism cards inside surrounding div, and also center that div.

chore(website): center organism cards

---

backend/docs/db/schema.sql
backend/src/main/kotlin/org/loculus/backend/model/ReleasedDataModel.kt
backend/src/main/kotlin/org/loculus/backend/service/submission/SequenceEntriesView.kt
backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt
backend/src/main/resources/db/migration/V1.9__update_sequence_entries_view_add_pipeline_version.sql
backend/src/test/kotlin/org/loculus/backend/controller/submission/GetReleasedDataEndpointTest.kt
backend/src/test/kotlin/org/loculus/backend/utils/EarliestReleaseDateFinderTest.kt
kubernetes/loculus/templates/_common-metadata.tpl

resolves #3209 
preview URL: https://backend-pipeline-v-in-metadata.loculus.org/swagger-ui/index.html#/submission-controller/getReleasedData
WIP
n/A

feat(backend): Return `pipelineVersion` in `get-released-data`

---

kubernetes/loculus/values.yaml

change link to main

---

website/src/components/DataUseTerms/EditDataUseTermsModal.tsx
website/src/components/Navigation/DocsMenu.tsx
website/src/utils/search.ts
website/src/utils/serversideSearch.ts

fix a couple any types

---

ena-submission/README.md
ena-submission/scripts/deposition_dry_run.py

resolves #
preview URL:
Nothing special this just improves curl request docs - would be great if this could be merged :-)

feat(deposition): improve ENA deposition docs and dry run helpers

---

docs/astro.config.mjs
docs/src/content/docs/for-users/approve-submissions.md
docs/src/content/docs/for-users/authenticate-via-api.md
docs/src/content/docs/for-users/submit-sequences.md
docs/src/content/docs/introduction/api-overview.md

resolves #3357
Preview: https://docs-docs-api-links.loculus.org
This depends on #3359 which should be merged first.

docs: add API overview and describe where to find the APIs

---

preprocessing/nextclade/src/loculus_preprocessing/sequence_checks.py

resolves #3507
preview URL: https://gap-message.loculus.org/ebola-sudan/submission/2/review

feat(website): Improve message when gapped sequences uploaded.

---

website/src/types/backend.ts

resolves https://github.com/loculus-project/loculus/issues/3515 - see issue for details
preview URL: https://fix-boolean-bug.loculus.org/
I just tested that this works locally and on the preview by logining in as superuser and revising a sequence to add the isLabHost flag.

fix(website): allow revision of metadata records with boolean fields

---

kubernetes/loculus/values.yaml

chore(kubernetes): remove TODO that is already done

---

backend/src/main/kotlin/org/loculus/backend/config/Config.kt
backend/src/main/kotlin/org/loculus/backend/service/submission/ProcessedSequenceEntryValidator.kt
backend/src/test/kotlin/org/loculus/backend/controller/submission/PreparedProcessedData.kt
backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmitProcessedDataEndpointTest.kt
backend/src/test/resources/backend_config.json
backend/src/test/resources/backend_config_single_segment.json
docs/src/content/docs/for-administrators/setup-with-kubernetes.md
kubernetes/loculus/silo_import_job.sh
kubernetes/loculus/templates/lapis-silo-database-config.yaml
kubernetes/loculus/templates/lapis-silo-deployment.yaml
kubernetes/loculus/values.yaml
preprocessing/specification.md
website/src/components/SearchPage/SearchForm.spec.tsx
website/src/components/SearchPage/SearchFullUI.spec.tsx
website/src/components/SearchPage/fields/FieldProps.tsx
website/src/components/SearchPage/fields/NormalTextField.tsx
website/src/types/config.ts

preview URL: http://tae-silo-0-5-0.loculus.org
This updates the dependency SILO to version `0.5.0`. 
To note: This version has some nice changes to the CLI interface and config handling of SILO. A refactor of `silo_import_job.sh` should be easier now, as some things that were previously specified by config files can now be directly supplied via CLI. This can reduce the "magic" some commands seemed to exhibit before.
The help-text SILO provides has also been improved a lot, which can be consulted for the usability improvements mentioned above.
Moreover, the built binary is now called `silo` instead of `siloApi`. `api` and `preprocessing` are supplied instead of `--api` and `--preprocessing`.
~~- [ ] The implemented feature is covered …

chore(deps): SILO v0.5.0

---

README.md

docs: Amend a goal that we would reach stability by EOY 2024

---

kubernetes/loculus/values.yaml

preview URL: https://lapis0311.loculus.org/ 
Changelog:
* **lapis:** stream JSON responses ([#1053](https://github.com/GenSpectrum/LAPIS/issues/1053)) ([bfb5f99](https://github.com/GenSpectrum/LAPIS/commit/bfb5f994c6e0adfeb4380f436a12d4179039974a)), closes [#1047](https://github.com/GenSpectrum/LAPIS/issues/1047)
* **lapis:** fix description of mutation objects in OpenApi spec ([#1051](https://github.com/GenSpectrum/LAPIS/issues/1051)) ([c6f625e](https://github.com/GenSpectrum/LAPIS/commit/c6f625e22074731e12f6cdbcb68344350e65503e))

chore(kubernetes): update to LAPIS 0.3.11

---

kubernetes/loculus/values.yaml

feat!: Allow raw reads input

---

ena-submission/src/ena_deposition/config.py

chore(deposition): small refactors

---

website/src/components/Submission/DataUploadForm.tsx

resolves #
preview URL:
Adds suggestion raised here: https://github.com/pathoplexus/pathoplexus/pull/351#issuecomment-2630832417 - this will clarify to users why we have different metadata lists

feat(website): clarify template differences

---

kubernetes/loculus/Chart.yaml

feat(Helm): Add icon to Helm Chart

---

website/vitest.setup.ts

fix(test): fixes accidentally merged failing test

---

docs/src/content/docs/for-administrators/data-use-terms.md

fix(docs): disable the data use terms in the "Disabling data use terms" example

---

.github/workflows/e2e-k3d.yml
deploy.py
kubernetes/loculus/values.yaml

resolves #3684, apart from for previews which are in a different repo
This will also fix a current broken test on main: https://github.com/loculus-project/loculus/actions/runs/13305856122/job/37156558700 though potentially that should be either added to the schema or refactored to work in a different way

feat(deployment): skip schema validation for dev

---

ena-submission/scripts/test_ena_submission.py
ena-submission/src/ena_deposition/create_assembly.py
ena-submission/src/ena_deposition/ena_submission_helper.py
kubernetes/loculus/values.yaml

resolves https://github.com/loculus-project/loculus/issues/3682
preview URL:
Read about chromosome list template here: https://ena-docs.readthedocs.io/en/latest/submit/fileprep/assembly.html#chromosome-list-file
1. Rename `main` to `genome` for single-segmented organisms
2. Rename chromosome type of single-segmented organisms to MONOPARTITE instead of SEGMENTED
3. Allow topology to be defined via values.yaml

feat(deposition): improve chromosome list

---

.github/workflows/datasets-mirror.yml

This is for Genspectrum
Tested and works!
https://github.com/loculus-project/loculus/actions/runs/13416010768/job/37476935445

feat(ci): Add RSV A/B and Influenza A to mirrored NCBI datasets

---

ingest/Snakefile

fix(ingest): format with Snakefile with snakefmt

---

website/src/components/SearchPage/DownloadDialog/DownloadButton.tsx
website/src/components/SearchPage/DownloadDialog/DownloadDialog.spec.tsx

resolves #3728
https://download-copy.loculus.org/ebola-sudan/search?
Provides a button to copy the download URL.
Thank you to @chaoran-chen for the tests!

feat(website): button to copy download URL

---

backend/src/main/kotlin/org/loculus/backend/service/submission/AccessionPreconditionValidator.kt
backend/src/test/kotlin/org/loculus/backend/controller/seqsetcitations/SeqSetValidationEndpointsTest.kt
backend/src/test/kotlin/org/loculus/backend/controller/submission/ApproveProcessedDataEndpointTest.kt
backend/src/test/kotlin/org/loculus/backend/controller/submission/DeleteSequencesEndpointTest.kt
backend/src/test/kotlin/org/loculus/backend/controller/submission/ReviseEndpointTest.kt
backend/src/test/kotlin/org/loculus/backend/controller/submission/RevokeEndpointTest.kt
backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmitExternalMetadataEndpointTest.kt

chore(grammar): Change error message to have correct grammar

---

website/src/components/common/Banner.tsx

The banner was meant to reappear after a day but it looks like I made a copy-paste error

fix(website): Make banner reappear after day

---

.github/workflows/ingest-tests.yaml
ingest/Snakefile
ingest/environment.yml

Currently run in CI only, no actual formatting is done in CI - we can add this later.

chore(ci/ingest): check formatting with snakefmt in ci

---

.github/workflows/datasets-mirror.yml

resolves https://github.com/loculus-project/loculus/issues/3786
preview URL:
1. Increase cronjob polling to every other hour
2. add influenza B
3. add slack notification if job fails
Tested that this will notify us on failure:

feat(ci): github actions - Increase mirror cronjon polling and add notification on failure

---

kubernetes/loculus/values.schema.json

fix(deployment): Helm Schema - Add `additionalProperties: false` where it was missing

---

website/src/components/SequenceDetailsPage/SequenceEntryHistoryMenu.spec.tsx
website/src/components/SequenceDetailsPage/SequenceEntryHistoryMenu.tsx
website/src/pages/seq/[accessionVersion]/versions.astro
website/src/utils/getVersionStatusColor.ts
website/tests/pages/sequences/accession.spec.ts

resolves #3738
resolves https://github.com/loculus-project/loculus/issues/2935
preview URL: 
- Changes the width of the popup and some texts and colors of the labels.
I looked at the changes and also the changes on the big version page. You can see what I did also in the video below.
https://github.com/user-attachments/assets/62224154-223c-4bee-b17d-2a12e4be48ff

design(website): Change version dropdown design

---

kubernetes/loculus/values.yaml

resolves #
preview URL: https://test.loculus.org/
Mutations are back on ebola sudan!!

feat(config): correct yaml syntax for prepro

---

kubernetes/loculus/values.schema.json

fix(kubernetes): add `"additionalProperties": false` to `preprocessing`

---

ena-submission/ENA_submission.md
ena-submission/scripts/deposition_dry_run.py
ena-submission/src/ena_deposition/create_assembly.py

resolves #
preview URL:
This adds docs and fixes a small regression - the address is not being correctly added to the manifest due to the misspelling of groupId as group_id.
This can only be fully tested on ENA prod with a broker account (lol) but I saw an error in the logs caused by the previous refactor in https://github.com/loculus-project/loculus/pull/3673 this fixes that bug

feat(ena-deposition): add docs on locus tag prefix, add fix a small bug

---

docs/src/team.json

This adds SIB as an affiliation to the team members who are members of SIB.

docs: add SIB affiliations

---

.github/workflows/format-integration-tests.yml
integration-tests/tests/specs/features/search/active-filters.spec.ts

Check formatting of the integration tests

feat(ci): format check for integration tests in CI

---

.github/workflows/datasets-mirror.yml

feat(config): add more taxonIds to mirror

---

backend/src/main/kotlin/org/loculus/backend/api/SubmissionTypes.kt
backend/src/main/kotlin/org/loculus/backend/model/ReleasedDataModel.kt
backend/src/main/kotlin/org/loculus/backend/service/submission/CompressionService.kt
backend/src/main/kotlin/org/loculus/backend/service/submission/EmptyProcessedDataProvider.kt
backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt
backend/src/test/kotlin/org/loculus/backend/controller/submission/PreparedProcessedData.kt
backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmitProcessedDataEndpointTest.kt
backend/src/test/kotlin/org/loculus/backend/service/ProcessedMetadataPostprocessorTest.kt
backend/src/test/kotlin/org/loculus/backend/utils/EarliestReleaseDateFinderTest.kt
preprocessing/specification.md

_This PR is targeting the `file-sharing` feature branch and not the main branch._
resolves #3930
🚀 Preview: https://fs-submit-processed-api.loculus.org

feat(backend): accept files in /submit-processed-data

---

website/src/components/Submission/FileUpload/FolderUploadComponent.tsx

resolves #
🚀 Preview: https://fs-fix-submission.loculus.org

Fix submission issue

---

kubernetes/loculus/templates/_common-metadata.tpl

resolves #
🚀 Preview: https://fs-details-view.loculus.org

display file fields 

---

backend/build.gradle
backend/src/main/kotlin/org/loculus/backend/config/BackendSpringConfig.kt
backend/src/main/kotlin/org/loculus/backend/config/Config.kt
backend/src/main/kotlin/org/loculus/backend/config/S3Config.kt
backend/src/main/kotlin/org/loculus/backend/service/files/S3Service.kt
backend/src/main/resources/application.properties
backend/src/test/kotlin/org/loculus/backend/config/BackendSpringConfigTest.kt
backend/src/test/kotlin/org/loculus/backend/controller/EndpointTestExtension.kt
backend/src/test/kotlin/org/loculus/backend/controller/files/RequestUploadEndpointTest.kt
backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmitEndpointFileSharingTest.kt
backend/src/test/kotlin/org/loculus/backend/service/GenerateAccessionFromNumberServiceTest.kt
backend/src/test/kotlin/org/loculus/backend/service/submission/EmptyProcessedDataProviderTest.kt
kubernetes/loculus/templates/_common-metadata.tpl
kubernetes/loculus/templates/loculus-backend.yaml
kubernetes/loculus/values_preview_server.yaml

Resolves #3952
🚀 Preview: https://fs-test-containers.loculus.org

test(backend): add MinIO testcontainer

---

backend/src/main/kotlin/org/loculus/backend/api/FileTypes.kt
backend/src/main/kotlin/org/loculus/backend/api/SubmissionTypes.kt
backend/src/main/kotlin/org/loculus/backend/model/ReleasedDataModel.kt
kubernetes/loculus/templates/_common-metadata.tpl
website/src/components/SequenceDetailsPage/DataTableEntryValue.tsx

resolves #3933
🚀 Preview: https://fs-better-details-view.loculus.org

render file list with file names and clickable links

---

kubernetes/loculus/templates/silo-deployment.yaml

resolves https://github.com/loculus-project/loculus/issues/3840
preview URL:
Adds a SILO readinessProbe to ensure it doesnt "start" before it is healthy
🚀 Preview: https://add-silo-readiness-probe.loculus.org

feat(config): add silo readinessProbe

---

preprocessing/nextclade/src/loculus_preprocessing/prepro.py
preprocessing/nextclade/src/loculus_preprocessing/processing_functions.py

feat: strip before nextclade

---

website/AGENTS.md

This is some context for AI agents (e.g. Codex) working on the website. It would be very helpful for me if we can merge it as it ensures that the agents check CI before merging.

chore: Add agents.md to website dir

---

CONTRIBUTING.md

docs: Clarify conventional commit requirement only applies to `main`

---

preprocessing/dummy/main.py

fix(prepro): Fix small typo in dummy preprocessing defaults

---

kubernetes/config-processor/README.md

Expands the config processor README.md

docs: Expand config processor README.md

---

preprocessing/nextclade/src/loculus_preprocessing/prepro.py

resolves issues mentioned in https://loculus.slack.com/archives/C05G172HL6L/p1747834980182839?thread_ts=1747646649.125089&cid=C05G172HL6L

feat(prepro): improve error message

---

website/src/components/SearchPage/SeqPreviewModal.tsx

resolves https://github.com/loculus-project/loculus/issues/4104

fix(website): fix version selector alignment

---

website/package-lock.json
website/package.json
website/src/components/ReviewPage/ReviewPage.spec.tsx
website/src/components/Submission/FileUpload/ColumnMappingModal.spec.tsx
website/vitest.setup.ts

Use some best practices which solve some messages that otherwise appear when you run `npm run test` warning about these things

chore(website): reduce test noisiness

---

ena-submission/ENA_submission.md
ena-submission/scripts/deposition_dry_run.py

resolves https://github.com/loculus-project/loculus/issues/3868
Updates docs to inform readers that locus_tag registration is in fact not required to submit annotations: see https://github.com/loculus-project/loculus/issues/3868 for details.
Adds documentation on how to submit raw reads

feat(deposition): improve docs on raw reads and assembly annotation

---

backend/src/main/kotlin/org/loculus/backend/service/seqsetcitations/SeqSetCitationsDatabaseService.kt

appears to resolve #4251 by batching checks to avoid SQL issues
I created a SeqSet with all WNV sequences which I seemed unable to do otherwise
🚀 Preview: https://seqset-sql.loculus.org

fix(backend): fix large seqset bug

---

.github/workflows/add-preview-url.yml

fix(workflow): don't fail PR description action for PRs from forks

---

kubernetes/loculus/values.yaml

It's been half a year since our last check. No changes detected so we're still good.
I used Claude to verify: https://claude.ai/share/da8496b7-2c73-42e2-867a-123c2bd0193a

chore(values): update check date of INSDC country list

---

ena-submission/src/ena_deposition/ena_submission_helper.py

This function is used to add geolocation (country) to the embl flat file created for ena deposition.
This list of geolocation fields should ideally be moved into a config - but as we are already improving/modifying this code for https://github.com/loculus-project/loculus/pull/4344 I think its good to at least add these additional fields here for now and we can improve the code structure later

feat(deposition): add more geolocation fields to assembly embl flat file

---

.github/workflows/build-arm-images.yaml

Alternative to #4444
Added `arm-images` label and it triggered a parallel build: https://github.com/loculus-project/loculus/actions/runs/15727747928/job/44321388564?pr=4445

chore(ci): allow triggering arm-builds with PR label

---

preprocessing/nextclade/environment.yml

chore(preprocessing): Bump nextclade 3.9 -> 3.14

---

preprocessing/nextclade/src/loculus_preprocessing/backend.py
preprocessing/nextclade/src/loculus_preprocessing/config.py
preprocessing/nextclade/src/loculus_preprocessing/prepro.py
preprocessing/nextclade/src/loculus_preprocessing/processing_functions.py
preprocessing/nextclade/src/loculus_preprocessing/sequence_checks.py

I've addressed some warnings - whenever there was a simple solution possible.
I also ignored some false positive warnings.

chore(prepro): linter fixes

---

.github/workflows/datasets-mirror.yml

Update datasets-mirror.yml with more EVs

---

website/src/components/SearchPage/DownloadDialog/DownloadDialog.tsx

chore(website): Remove remnant TODO

---

.github/workflows/format-website-on-dispatch.yml

This will hopefully solve https://github.com/loculus-project/loculus/actions/runs/15977042797/job/45062139380?pr=4553

fix(ci): Bump setup Node action in format website

---

ena-submission/README.md
ena-submission/environment.yml

chore(deposition): add pip install -e . to docs, add type packages to env

---

ingest/scripts/heuristic_group_segments.py
ingest/scripts/prepare_metadata.py
kubernetes/loculus/values.yaml

resolves #
🚀 Preview: https://multi-path-evs-anya.loculus.org

enable searching for genotype on multi-pathogen pages

---

website/src/utils/templateProcessor.ts

resolves #
🚀 Preview: https://match-dash.loculus.org

multipath: match dash too in linkouts

---

backend/build.gradle

Minor bump, no breaking changes etc, all good.

chore(deps): bump flyway in backend

---

backend/src/main/kotlin/org/loculus/backend/controller/SubmissionController.kt

Under the hood, it does the same, but it's more idiomatic and nicer to read.

refactor(backend): use Kotlin style extension function for deserialization

---

backend/src/main/kotlin/org/loculus/backend/service/submission/UploadDatabaseService.kt

refactor(backend): don't select more than necessary

---

ena-submission/src/ena_deposition/__main__.py
ena-submission/src/ena_deposition/api.py
ena-submission/src/ena_deposition/create_assembly.py
ena-submission/src/ena_deposition/create_project.py
ena-submission/src/ena_deposition/create_sample.py
ena-submission/src/ena_deposition/submission_db_helper.py
ena-submission/src/ena_deposition/trigger_submission_to_ena.py
ena-submission/src/ena_deposition/upload_external_metadata_to_loculus.py
ruff.toml

fix(deposition): replace all prints with proper logs, and print full exception for top level exceptions in __main__.py

---

preprocessing/nextclade/src/loculus_preprocessing/processing_functions.py
preprocessing/nextclade/tests/test_processing_functions.py

resolves https://github.com/loculus-project/loculus/issues/4550

feat(prepro): Add warning if 'and' found in `authors`

---

backend/src/main/kotlin/org/loculus/backend/controller/SubmissionControllerDescriptions.kt
docs/src/content/docs/for-administrators/configuring-extra-files.md
docs/src/content/docs/for-administrators/existing-preprocessing-pipelines.md
kubernetes/loculus/values.yaml

chore: fix 4 typos

---

website/src/components/SearchPage/DownloadDialog/SequenceFilters.tsx
website/src/components/common/FixedLengthTextViewer.tsx

chore(website): remove useless comments and `as any`

---

integration-tests/tests/specs/features/annotations.dependent.spec.ts
preprocessing/nextclade/src/loculus_preprocessing/embl.py
preprocessing/nextclade/tests/flatfiles/single_segment.embl

resolves https://loculus.slack.com/archives/C05G172HL6L/p1754478090293089?thread_ts=1754473903.880519&cid=C05G172HL6L
🚀 Preview: https://update-descriptions.loculus.org

feat(prepro): update embl flat file descriptions

---

docs/src/content/docs/reference/helm-chart-config.mdx
kubernetes/loculus/templates/_common-metadata.tpl
kubernetes/loculus/values.yaml
website/src/components/SequenceDetailsPage/DataTableEntryValue.tsx
website/src/components/SequenceDetailsPage/LinkWithMenuComponent.tsx
website/src/types/config.ts

Resolves https://github.com/loculus-project/loculus/issues/1770
This is not really breaking - it just adds a new option - but we should use it in PPX
🚀 Preview: https://linkmenu.loculus.org

feat!(website): add menu for viewing in different INSDC dbs

---

.github/workflows/datasets-mirror.yml

feat(actions): add Orthopneumovirus to mirror and sort taxonIds

---

.vscode/settings.json
website/src/components/SequenceDetailsPage/SequenceDataUI.tsx
website/src/components/common/RestrictedUseWarning.tsx
website/tests/pages/review/index.spec.ts

🚀 Preview: https://restricteduse.loculus.org

feat(website): refactor restricted use banner to make it easy to modify 

---

docs/src/content/docs/for-users/submit-extra-files.md

resolves #4964
Preview of the relevant page: https://docs-docs-broken-link.loculus.org/for-users/submit-extra-files/
🚀 Preview: https://docs-broken-link.loculus.org

fix(docs): fix link

---

website/src/utils/search.ts

It preserves the results:
true -> false
false -> true
undefined -> true

refactor(website): simplify boolean expression

---

website/src/components/SearchPage/DownloadDialog/DownloadDataType.ts

It seems to have been moved to DownloadGenerator::downloadEndpoint without removing this.
resolves #

chore(website): delete unused function

---

preprocessing/nextclade/src/loculus_preprocessing/config.py
preprocessing/nextclade/src/loculus_preprocessing/prepro.py

required for https://github.com/GenSpectrum/servers/issues/294
Testing on genspectrum servers shows this is WAI

feat(prepro): add nextclade_dataset_tag_map

---

.github/workflows/values-schema-prettier.yml
kubernetes/.prettierrc
kubernetes/loculus/values.schema.json

Formatting is currently inconsistent and this caused Claude (and me) struggle with editing it (it assumed indentation was correct) in #5098

test(k8s): enforce value.schema.json is formatted with prettier
