.github/workflows/e2e-k3d.yml
For public repositories, GitHub runners are larger so should be OK for our E2E tests: https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
=> Use standard runner for E2E tests

website/src/pages/api-documentation/index.astro
Found this 404 with a simple spider script (ChatGPT mostly):
```py
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin, urlparse, urlunparse
import sys
from collections import defaultdict
def extract_urls(url):
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')
urls = []
for link in soup.find_all('a', href=True):
href = link['href']
full_url = urljoin(url, href)
urls.append(full_url)
return urls
def filter_and_normalize_urls(urls, base_domain):
filtered_urls = set()
for url in urls:
if url.startswith(base_domain) and '/seq/' not in url:
parsed_url = urlparse(url)
normalized_url = urlunparse(parsed_url._replace(fragment=""))
filtered_urls.add(normalized_url)
return filtered_urls
def check_url_status(url):
try:
response = …
```
=> fix: link target is /doc/how-to/authentication-api not _api

kubernetes/loculus/templates/_possiblePriorityClassName.tpl, kubernetes/loculus/templates/ena-submission-deployment.yaml, kubernetes/loculus/templates/ingest-deployment.yaml, kubernetes/loculus/templates/keycloak-deployment.yaml, kubernetes/loculus/templates/lapis-silo-deployment.yaml, kubernetes/loculus/templates/loculus-backend.yaml, kubernetes/loculus/templates/loculus-preprocessing-deployment.yaml, kubernetes/loculus/templates/loculus-website.yaml, kubernetes/loculus/values.yaml
To allow instances to have various levels of priority - e.g. to make production more important than staging in a cluster.
> Pods can have priority. Priority indicates the importance of a Pod relative to other Pods. If a Pod cannot be scheduled, the scheduler tries to preempt (evict) lower priority Pods to make scheduling of the pending Pod possible
https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/
=> feat(deployment): allow specifying a priorityClassName

website/src/components/Navigation/Navigation.astro
Preview: https://use-sandwich-menu-even-at.loculus.org/
This is required due to the number of pathoplexus menu items. In time we should adapt our nav strategy.
Change from left to right
=> feat(website): Use sandwich menu even at slightly larger screen sizes

preprocessing/nextclade/src/loculus_preprocessing/prepro.py
resolves #2595 
preview URL: https://segments-align-anya.loculus.org/
1. No warning if 1+ segment is removed but others align: 
2. If segments S and L are flipped causing both to not align we see
=> fix(prepro): Raise warning if not all input segments align

website/src/styles/mdcontainer.scss
Uses a much subtler effect on hovering over docs links, avoiding the potential for text to reflow when bolding
See e.g. front page FAQ of https://preview-test2.pathoplexus.org/
=> feat(website): simplify link hover effect on Docs pages

website/src/components/Navigation/DocsMenu.tsx
This should resolve #2662 by fixing the width of the menu
I've tried to test it just by editing live CSS and it seemed to work
(Cornelius update): https://fix-resizing-issue.loculus.org
=> fix(website): fix resizing issue on DocsMenu

.github/workflows/codeql.yml
Adds CodeQL config, which automatically scans for security vulnerabilities.
Python and Typescript work without custom config, but kotlin required some.
=> ci: add codeql config

backend/.gitignore, backend/README.md, backend/build.gradle, backend/gradle.properties, backend/src/main/kotlin/org/loculus/backend/auth/AuthenticatedUser.kt, backend/src/main/kotlin/org/loculus/backend/config/SecurityConfig.kt, backend/src/main/kotlin/org/loculus/backend/model/SubmitModel.kt, backend/src/main/kotlin/org/loculus/backend/service/submission/UploadDatabaseService.kt, backend/src/test/kotlin/org/loculus/backend/controller/RequestAuthorization.kt, backend/src/test/kotlin/org/loculus/backend/controller/submission/GetReleasedDataEndpointTest.kt, backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmissionControllerClient.kt, docs/package-lock.json, kubernetes/loculus/silo_import_job.sh, kubernetes/loculus/templates/_config-processor.tpl, kubernetes/loculus/templates/keycloak-config-map.yaml, kubernetes/loculus/templates/lapis-silo-deployment.yaml, kubernetes/loculus/values.yaml, kubernetes/loculus/values_e2e_and_dev.yaml
resolves #1913
resolves #1625
preview URL: https://get-no-auth.loculus.org
- Don't require authn/authz for `get-released-data` endpoint
- Fix lints
- Run backend tests in paralell
=> feat(backend): don't require authentication for /get-released-data

backend/build.gradle, backend/gradle/wrapper/gradle-wrapper.properties
Last bump was 9 months ago. We should check this whenever kotlin version is bumped by dependabot.
8.8 is the max version of gradle supported by kotlin 2.0.20
See https://kotlinlang.org/docs/gradle-configure-project.html#apply-the-plugin
preview URL: https://bump-gradle.loculus.org
Bump gradle version to 8.8 from 8.5
=> deps(backend): bump gradle to 8.8 from 8.5

kubernetes/loculus/templates/_siloDatabaseConfig.tpl
resolves #2668
Previously failing to set `silo:` resulted in 
which led LAPIS to crash
https://theosanderson-patch-7.loculus.org
=> fix(deployment): Only try to include SILO-specific config in the LAPIS/SILO configmap if it is actually defined

backend/build.gradle, backend/gradle.properties
Maybe helps with #2708 (hopefully, let's see)
This reverts the parallel test execution that was introduced in #1914. Some tests expect an empty database, so parallel execution can very likely be a source of flakiness.
I will run backend tests five times: https://github.com/loculus-project/loculus/actions/runs/10716872022/job/29715313279?pr=2710
=> chore(backend): disable parallel test execution to avoid flaky tests

docs/src/content/docs/for-administrators/my-first-loculus.md
This tutorial is intended to be the most basic configuration of Loculus possible, without requiring people to think about preprocessing functions, etc. but we previously had to include a date due to the fact that our configuration essentially required it for SILO. We've now fixed that, so we can remove it.
=> docs: Remove date from "my first loculus" tutorial

website/README.md
=> doc: recommend fast `npm run start-server` for faster and less flaky e2e tests

website/src/components/Submission/DataUploadForm.tsx
resolves #
preview URL: https://delete-dummy.loculus.org/
Also lets us use load dummy data for the unaligned test organism. 
Adds the load example data to 
This works:
=> Add load example data to no-aligned-organism

backend/src/main/kotlin/org/loculus/backend/service/submission/ProcessedSequenceEntryValidator.kt, backend/src/test/kotlin/org/loculus/backend/controller/submission/PreparedProcessedData.kt, backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmitProcessedDataEndpointTest.kt, preprocessing/nextclade/src/loculus_preprocessing/sequence_checks.py
resolves #
preview URL: https://no-gaps-in-unaligned.loculus.org/
'-' only makes sense in the context of aligned sequences. It is not accepted by ENA and is not included in official IUPAC lists: https://genome.ucsc.edu/goldenPath/help/iupac.html#:~:text=The%20International%20Union%20of%20Pure,for%20either%20G%20or%20A).
=> Remove '-' from list of allowed symbols in unaligned sequences.

preprocessing/nextclade/src/loculus_preprocessing/prepro.py
Preview: https://revert-2678-revert-2676-s.loculus.org/
Resolves #2595
Currently when a user submits multi-segmented entries where at least one segment aligns, then they will not be warned if other segments of the same entry do not align (Use case: someone submits a proper CCHF L segment, but the M segment isn't the M segment, it's actually S).
For non-segmented viruses, we guarantee, that every sequence that's released actually aligns.
The bug here currently is, that this is not true for segmented viruses.
All segments that are submitted _must_ align, otherwise the user cannot release the entry.
There should be no change to pathoplexus production DB state with this PR, as ingest already filters out all sequences that do not align.
It only impacts future user submissions of segmented …
=> fix(prepro): Label a sequence with error if not all input segments align

.github/dependabot.yml
It happens fairly frequently that npm dependabot updates fail, separating minor and patch will reduce time spent debugging
Inspired by the latest dependabot PR that wasn't quite trivial (multiple unrelated failures, grouping made it harder to figure out what's wrong)
=> chore(deps): separate minor and patch updates in npm dependabot

kubernetes/loculus/values.yaml
resolves #
preview URL: https://add-lat-long.loculus.org/
ENA accepts latitude and longitude values - we do not, as some submitters have these values it would be great to also add this option for compatibility. 
I used the decimal degree format as this is expected by ENA: https://www.ebi.ac.uk/ena/browser/view/ERC000033
=> Add latitude and longitude to default metadata values.

backend/src/main/kotlin/org/loculus/backend/controller/SubmissionController.kt, backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt, backend/src/test/kotlin/org/loculus/backend/controller/submission/GetReleasedDataEndpointTest.kt, kubernetes/loculus/silo_import_job.sh, kubernetes/loculus/templates/lapis-silo-deployment.yaml, kubernetes/loculus/values.yaml
partially resolves https://github.com/loculus-project/loculus/issues/2724
preview URL: http://add-count-in-header.loculus.org/
As we send data in ndjson format, clients (such as the silo_import_job) have no way of knowing if the data they have received is complete or if the stream was interrupted early.
To fix this, /get-released-data adds header x-rowcount to the response with the total number of expected records in the accompanying stream.
Clients can then compare this number with the responseBody to see if they have received all records and discard/re-request in case the stream was aborted early.
The actual streaming is executed after `getReleased` is defined. This means the count calculated for the header and the results of the stream are not inside the same database transaction. This …
=> fix(backend, silo-preprocessing):  add new header x-total-records to get-released-data to enable streaming result verification

website/src/components/IndexPage/getOrganismStatistics.ts
https://only-count-latest-version.loculus.org/
=> feat(website): Only count latest versions for stats on main page

backend/src/main/kotlin/org/loculus/backend/api/SubmissionTypes.kt, backend/src/main/kotlin/org/loculus/backend/model/ReleasedDataModel.kt, backend/src/test/kotlin/org/loculus/backend/controller/submission/GetReleasedDataEndpointTest.kt
Spawned by this Slack discussion: https://loculus.slack.com/archives/C05G172HL6L/p1726586424473839
=> refactor(backend): rename enum `SiloVersionStatus` to `VersionStatus` and document the enum

website/src/components/IndexPage/getOrganismStatistics.ts, website/src/components/SearchPage/DownloadDialog/generateDownloadUrl.ts, website/src/components/SequenceDetailsPage/SequencesBanner.astro, website/src/pages/[organism]/search/index.astro, website/src/pages/[organism]/submission/[groupId]/released.astro, website/src/services/lapisClient.ts, website/src/types/lapis.ts, website/src/utils/getVersionStatusColor.ts
Also some slight tweaks to function names in organism statistics, follow up to #2814
Backend rename (not coupled as versionStatus usage is only internal) is done in: #2817
=> refactor(website): rename `siloVersionStatus` to `versionStatus`

kubernetes/loculus/values.yaml
resolves https://github.com/loculus-project/loculus/issues/2636
preview URL: https://add-nih-countries.loculus.org/
As calculated in https://github.com/loculus-project/loculus/pull/2335 these are the countries on the NIH list yet missing from the ENA list, adding them here for consistency. 
For reference here is:
- The ENA checklist: https://www.ebi.ac.uk/ena/browser/api/xml/ERC000011
- The NIH checklist https://www.ncbi.nlm.nih.gov/genbank/collab/country/.
I added these countries to the end of the list. Currently we do not use the ENA checklist for verification - if this changes these countries will need to be properly mapped.
=> Add countries in NIH list which are missing from ENA list

kubernetes/loculus/values.yaml
Relates to #2788
Might require pp values.yaml changes - need to check
https://fix-continent.loculus.org
=> fix: don't ingest region as geoLocAdmin2 (it's continent)

ingest/scripts/call_loculus.py, ingest/scripts/group_segments.py, ingest/scripts/prepare_metadata.py
resolves #2650
preview URL: https://author-order.loculus.org
We started sorting author lists when it turned out that different segments of the same isolate could have different author orders. We should have done the sorting only for grouping purposes and not when submitting to Loculus.
This PR fixes that by only sorting for grouping purposes.
Note: this will cause ingest to submit revisions for existing deployments as the ingest hash changes.
=> [don't merge without prior discussion] fix: don't sort author lists, except for segment grouping purposes

ingest/scripts/call_loculus.py
resolves #
preview URL: https://ingest-error.loculus.org/
Raise an error in ingest if we ever have multiple loculus accession for one insdc accession loculus. 
This si still too late (i.e. the duplication has already occured) but will warn us and hopefully make the logs a bit cleaner.
=> feat(ingest): Raise ingest error if we ever have multiple loculus accession for one insdc accession in loculus

deploy.py
I made a mistake in what was meant to be a helpful feature to avoid confusion. It should allow `main.loculus.org` but not `loculus.org` but I used `<=` not `<` so it currently doesn't allow `main.loculus.org`. Apologies.
=> fix(deploy): hotfix mistake in my changes to `deploy.py` to handle subdomains appropriately

backend/src/main/kotlin/org/loculus/backend/controller/SubmissionController.kt, backend/src/main/kotlin/org/loculus/backend/model/SubmitModel.kt, backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt, backend/src/main/kotlin/org/loculus/backend/service/submission/UploadDatabaseService.kt, backend/src/test/kotlin/org/loculus/backend/controller/submission/GetOriginalMetadataEndpointTest.kt
preview URL: https://testMtadataLock.loculus.org
This is a follow-up to #2846
=> test(backend): test `/get-original-metadata` locked during new submissions

website/src/components/SequenceDetailsPage/SequenceContainer.spec.tsx, website/src/components/SequenceDetailsPage/SequenceViewer.tsx, website/src/components/SequenceDetailsPage/SequencesContainer.tsx, website/tests/pages/sequences/accession.spec.ts, website/tests/pages/sequences/sequences.page.ts
preview URL: https://seq-changes.loculus.org/ebola-zaire/search?
- Fixes the height of the sequence container avoiding layout shifts when moving between tabs
- Uses a single tab for all proteins - selected with a dropdown- , rather than one tab per protein, which would be important for users working on some organisms
- Adjusts the names of the raw and aligned nucleotide tabs
=> feat(website): One tab for all protein sequences

kubernetes/loculus/silo_import_job.sh
Accidentally introduced in "feat(silo-prepro): use hash instead of line count to test for equality (#1488)" (b0523ad9) when changing the interpolation.
=> fix(silo-preprocessing): Fix interpolation syntax error

kubernetes/loculus/templates/ingest-deployment.yaml
ArgoCD sync options were tagged in the wrong place, ~likely allowing concurrency~ (edit: but we were using `strategy: Recreate`). Also we were not using reloader.
https://argocd-move.loculus.org/
=> Move argoCD sync options to the right place in ingest, and add reloader

kubernetes/loculus/templates/ingest-config.yaml, kubernetes/loculus/templates/ingest-deployment.yaml
We encountered an issue during a rollout in which the config map was changed and triggered a reload of the pod [edit: actually we didn't have the reloader - so I'm not sure if that is it] before the pod itself was upgraded to the next version, causing double version bumps in staging. This avoids that by making the config map contain the loculus version that it targets and making an initContainer in the deployment that checks that this matches that expected by the deployment.
https://ingest-version-checking.loculus.org/
=> feat(deployment): ingest version checking

kubernetes/loculus/templates/ingest-deployment.yaml
resolves #
preview URL: https://stop-revoke-cronjob.loculus.org/
Although `loculus-revoke-and-regroup-cronjob` was scheduled to a non-existent time it was still being started by argocd, this caused concurrent ingest and duplication of ingested sequences.
=> fix(deployment): suspend loculus-revoke-and-regroup-cronjob

backend/src/main/kotlin/org/loculus/backend/controller/SubmissionController.kt, backend/src/main/kotlin/org/loculus/backend/controller/SubmissionControllerDescriptions.kt, backend/src/main/kotlin/org/loculus/backend/model/ReleasedDataModel.kt, backend/src/test/kotlin/org/loculus/backend/controller/submission/ExtractUnprocessedDataEndpointTest.kt, backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmissionControllerClient.kt, kubernetes/loculus/silo_import_job.sh, preprocessing/dummy/main.py, preprocessing/nextclade/environment.yml, preprocessing/nextclade/src/loculus_preprocessing/backend.py, preprocessing/nextclade/src/loculus_preprocessing/datatypes.py, preprocessing/nextclade/src/loculus_preprocessing/prepro.py, preprocessing/nextclade/src/loculus_preprocessing/processing_functions.py
relates to #2092 
preview URL: https://etag-prepro.loculus.org
Send etag to /extract-unprocessed-sequences to reduce db/backend load
Big reduction in db and backend load, approximately to 1/4 to 1/3 of the previous base load
=> feat(backend,prepro): use etag to reduce database load

ena-submission/README.md, ena-submission/Snakefile, ena-submission/config/defaults.yaml, ena-submission/scripts/create_assembly.py, ena-submission/scripts/create_project.py, ena-submission/scripts/create_sample.py, ena-submission/scripts/ena_submission_helper.py, ena-submission/scripts/upload_external_metadata_to_loculus.py
resolves #
preview URL:
1. Maps results of successful ENA assembly submission to insdc_accession_base and insdc_accession_full and uploads these results to Loculus - handles the case with a single and also a multi-segment organism: 
2. Tested locally and updated README with exact commands for local testing and additional warnings.
3. Refactored code to have `--test` flag (determines if ENA dev or prod is used) that is set at config level to make code clearer.
=> Add INSDC accession to results of ena submission and upload to backend.

ena-submission/Snakefile, ena-submission/config/defaults.yaml, ena-submission/scripts/create_assembly.py, ena-submission/scripts/create_project.py, ena-submission/scripts/create_sample.py, ena-submission/scripts/ena_submission_helper.py, ena-submission/scripts/submission_db_helper.py, ena-submission/scripts/test_ena_submission.py, ena-submission/scripts/trigger_submission_to_ena.py, ena-submission/scripts/upload_external_metadata_to_loculus.py
resolves #
preview URL: https://reduce-ena-db-load.loculus.org/
1. Reduce the size of connection pools (for connections to the postgres db) used by each snakemake rule from max4 to max2. 
2. Increase sleep period after each iteration of snakemake rules from 2 to 10seconds.
3. Increase period between checking github for new data from 1 to 2min.
4. Improve error handling when requests to ENA fail (I had tests for this but they were wrong - errors on main currently due to incorrect error handling). 
```
During handling of the above exception, another exception occurred:
...
File "/package/scripts/ena_submission_helper.py", line 392, in check_ena
f"ENA check failed with status:{response.status_code}. "
^^^^^^^^
UnboundLocalError: cannot access local variable 'response' where it is not …
```
=> Reduce ena submission induced db load

.github/workflows/build-arm-images.yaml, ena-submission/README.md, ena-submission/config/config.yaml, ena-submission/flyway/conf/flyway.conf, ena-submission/scripts/create_assembly.py, ena-submission/scripts/create_project.py, ena-submission/scripts/create_sample.py, ena-submission/scripts/get_ena_submission_list.py, ena-submission/scripts/submission_db_helper.py, ena-submission/scripts/trigger_submission_to_ena.py, ena-submission/scripts/upload_external_metadata_to_loculus.py, kubernetes/loculus/templates/ena-submission-deployment.yaml
resolves #
preview URL: https://use-urlto-connect-to-db.loculus.org/
The ena-submission pod does not start on Pathoplexus as the db has a different name. This PR changes from using the host to using the java url.
It additionally renames the ena-submission schema to ena_deposition_schema.
=> fix(ena-submission): Use db url instead of host for connections, do not hardcode db name

kubernetes/loculus/templates/_common-metadata.tpl
Resolves #2633, resolves https://github.com/loculus-project/loculus/issues/2675
Preview: https://groupchange.loculus.org/
There are some technical constraints here: the first listed name is the one that will appear in the combined field on the sequence page, which is why I've gone for this exact solution. Happy for a fuller change in the future.
=> fix(website): Change submitting group ID displayName 

ena-submission/Snakefile, ena-submission/scripts/create_assembly.py, ena-submission/scripts/create_project.py, ena-submission/scripts/create_sample.py, ena-submission/scripts/ena_submission_helper.py, ena-submission/scripts/ena_types.py, ena-submission/scripts/test_ena_submission.py, ena-submission/test/get_ena_analysis_process_response.json
resolves https://github.com/loculus-project/loculus/issues/2895
preview URL: https://patch-create-assembly.loculus.org/
Note that chromosome accessions are the accessions of the nucleotides in each submitted segment, in PP we call this insdcAccession_{segment}.
1. Rename check_ena to get_ena_analysis_process, refactor so that get_chromsome_accessions is a separate sub-function of get_ena_analysis_process, and results are returned when either the gca accession OR the chromosome accessions are returned (in contrast to now only returning results when both are returned)
2. Add tests that get_chromsome_accessions works for single and multi-segmented viruses now that we know the expected response format for both. I added a test where I mock the response using a known response text for a …
=> fix(ena-submission): Parse get analysis process response better for single segment case, return partial results and submit projects with holdUntilDate

website/src/components/SequenceDetailsPage/SequenceDataUI.tsx
preview URL: http://fixdatausetermsdisplay.loculus.org
Website seq details showed restricted even after expiration of restriction.
See https://loculus.slack.com/archives/C05G172HL6L/p1727769592602569
Root cause was misunderstanding in website code of what the dataUseTermsHistory contains.
The website code assumed there would be a new entry when something becomes open, but in fact the history is just a log of changes.
The backend only returns the history - which does not include "OPEN" as a last entry when the restricted period expired. LAPIS has the correct values - let's simply rely on that.
This assumes the following as correct:
* The backend just stores the history (not the state) of data use terms. 
* getting the history from the backend for a sequence entry that has expired …
=> fix(website): don't display data as "restricted" when the last restricted data use terms expired

kubernetes/loculus/templates/ena-submission-config.yaml, kubernetes/loculus/templates/ingest-config.yaml, kubernetes/loculus/templates/loculus-preprocessing-deployment.yaml
- **fix: use kubernetes dns to avoid basic auth for internal services**
resolves #
preview URL: https://fix-dns.loculus.org
=> fix: use kubernetes dns to avoid basic auth for internal services

kubernetes/loculus/templates/keycloak-database-deployment.yaml, kubernetes/loculus/templates/loculus-database-standin.yaml
This prevents the stand-in databases from using rolling migrations to try to avoid race conditions where the backend runs migrations on the old DB then the new DB has no migrations.
preview URL: https://recreate.loculus.org
=> fix(deployment): Use recreate strategy for stand in  dbs

website/tsconfig.json
resolves https://github.com/loculus-project/loculus/issues/2937
`astro check` produces a lot of pointless output, flooding the screen, bad developer experiencer. Seems to happen when there's a playwright report dir present with js files.
Adding playwright dir to excludes fixes it.
Before: 
After:
=> chore(website): add playwright outputs to astro check exclude dir

ena-submission/README.md, ena-submission/Snakefile, ena-submission/scripts/create_assembly.py, ena-submission/scripts/deposition_dry_run.py, ena-submission/scripts/ena_submission_helper.py
resolves #
preview URL: https://ena-deposition-add-dry-ru.loculus.org/
=> feat(ena-submission): Add a dry run option for faster debugging/ submission review/ updates

ena-submission/scripts/deposition_dry_run.py, ena-submission/scripts/upload_external_metadata_to_loculus.py
workaround until we figure out #2945 
preview URL: https://tempfixes.loculus.org or https://temp-fixes.loculus.org
The ena-submission pipeline is failing to upload external metadata because it is uploading a gcaAccession field which is currently missing from the config.yaml.
Adding new metadata fields currently causes issues (this might be helped by addressing #2793), until these can be resolved we temporarily do not upload the gcaAccession to Loculus.
This PR also fixes an unrelated little bug in the dry-run script.
=> fix(ena-submission): temporarily do not send gcaAccession to Loculus

ena-submission/ENA_submission.md, ena-submission/Snakefile, ena-submission/environment.yml, ena-submission/scripts/create_assembly.py, ena-submission/scripts/ena_submission_helper.py, ena-submission/scripts/ena_types.py, ena-submission/scripts/test_ena_submission.py, kubernetes/loculus/values.yaml
resolves #
preview URL: https://test-adding-authors.loculus.org/
Adding AUTHORS as a field to the manifest file was not successful, from reading the docs it has become clear to us that instead of submitting the sequence as a fasta we should submit a flat file, flat files allow us to set metadata fields and the authors field.
Docs: https://ena-docs.readthedocs.io/en/latest/submit/fileprep/flat-file-example.html
Flat file: annotations: https://www.ebi.ac.uk/ena/WebFeat/. 
As we are submitting as a broker it is important that we add the AUTHORS to the assembly: https://ena-docs.readthedocs.io/en/latest/faq/data_brokering.html#authorship.
=> feat(deposition): submit EMBL flatfile instead of fasta for better nucleotide metadata

backend/src/main/kotlin/org/loculus/backend/service/datauseterms/DataUseTermsDatabaseService.kt, backend/src/main/kotlin/org/loculus/backend/service/submission/UploadDatabaseService.kt
preview URL:
While implementing #2953 I thought it might be good to log (in the audit log) when someone changes data use terms.
=> feat(backend): audit log when someone sets data use terms

kubernetes/loculus/values.yaml, website/README.md, website/src/components/Edit/EditPage.tsx, website/src/components/Submission/DataUploadForm.tsx, website/src/pages/[organism]/submission/template/index.ts, website/src/routes/routes.ts, website/src/settings.ts, website/tests/pages/submission/submit.page.ts, website/tests/pages/submission/template.spec.ts
preview URL: https://submissionidedit.loculus.org/
* The `submissionId` should not be configurable. It's "hardcoded" in the backend (i.e. required), so we can also hardcode it in the website.
* The edit page has a separate display for the submission id anyway - it doesn't need to be in the input fields there
* The metadata template needs the submission id - let's hardcode it
* Also add `accession` when someone want a template for revisions.
* Test the metadata templates
This is a follow-up to https://loculus.slack.com/archives/C06JCAZLG14/p1727707545650969.
=> [BREAKING] Don't include submission id in website `input fields`, add accession to metadata revision template

kubernetes/loculus/templates/_common-metadata.tpl, kubernetes/loculus/values.yaml
preview URL: https://lapis034silo0222.loculus.org/
* **lapis:** order CSV/TSV columns of aggregated/details data as specified in the request fields or as in the database config ([6cf8704](https://github.com/GenSpectrum/LAPIS/commit/6cf8704e61c9435b37e3846d210496bcad00a977)), closes [#910](https://github.com/GenSpectrum/LAPIS/issues/910)
* **lapis-docs:** fix link on landing page ([d4137b3](https://github.com/GenSpectrum/LAPIS/commit/d4137b3e3de8daf6a9001f1beaff17ef7d9b53df))
* **lapis:** abort on startup when silo url has invalid syntax ([373d662](https://github.com/GenSpectrum/LAPIS/commit/373d6625abfb74c46b0ec65f020126c7c87089c4)), closes [#939](https://github.com/GenSpectrum/LAPIS/issues/939)
* **lapis-docs:** Sequence file naming scheme uses indexes now not names …
=> chore: update to LAPIS 0.3.4, SILO 0.2.22

website/tests/pages/submission/template.spec.ts
resolves #2963
preview URL:
webkit seems to ignore the content disposition header. It doesn't download the file, instead it displays it.
=> tests(website): skip download tests in webkit

ena-submission/scripts/create_assembly.py, ena-submission/scripts/test_ena_submission.py
resolves #
preview URL: https://ena-add-address.loculus.org/
=> Ena add address

kubernetes/loculus/templates/ena-submission-config.yaml
preview URL: https://dontconfigureenadepositio.loculus.org/
```
Error: template: loculus/templates/ena-submission-config.yaml:21:8: executing "loculus/templates/ena-submission-config.yaml" at <include "loculus.generateENASubmissionConfig" .>: error calling include: template: loculus/templates/_common-metadata.tpl:373:32: executing "loculus.generateENASubmissionConfig" at <$instance.enaDeposition.configFile>: nil pointer evaluating interface {}.configFile
```
But actually I have `disableEnaSubmission: true` in my config.
The `loculus-ena-submission-config` `ConfigMap` is only used (AFAICS) in the `ena-submission-deployment.yaml`, which also has the condition `{{- if not .Values.disableEnaSubmission }}`.
-> We also don't need the config map in that case.
~~- [ ] All necessary documentation …
=> fix(kubernetes): don't expect `$instance.enaDeposition` config when ena submission is disabled

docs/src/content/docs/for-administrators/setup-with-kubernetes.md, docs/src/content/docs/reference/helm-chart-config.mdx
resolves #2928
This add a very rough reference for the Helm chart configuration – co-authored with @theosanderson (with the help of a few chat bots). It has still a lot of gaps and any help in filling them would be highly appreciated!
https://docs-docs-helm-config.loculus.org/reference/helm-chart-config/
=> docs: add reference of Helm chart configuration

docs/astro.config.mjs, docs/src/content/docs/for-administrators/build-new-preprocessing-pipeline.md, docs/src/content/docs/for-administrators/existing-preprocessing-pipelines.md
Here's a short docs describing how our Helm chart will call a preprocessing pipeline and provide the config. (Thanks, @anna-parker, for explaining to me how it works!)
=> docs: document how to deploy a custom pipeline with Kubernetes and Helm

website/src/styles/mdcontainer.scss
resolves #
preview URL: https://docs-padding.loculus.org/governance
old:
new:
=> feat(website): Add padding to code blocks in docs

.github/workflows/website-playwright-dev-test.yml
We were getting errors in the pip install due to a managed environment (due to some change on the GitHub side)
=> fix(ci): Explicitly install python in dev server test

website/src/services/serviceHooks.ts
preview URL: https://prettierlapissequenceerro.loculus.org/
The message before was not helpful and not pretty either. This is at least helpful (to us), but not very pretty for users either.
After: 
Before:
=> fix(website): show more helpful error when LAPIS returns error when fetching sequences

website/tests/e2e.fixture.ts
Just a little enhancement to the playwright tests. 
I've added a function that checks if the keycloak server is actually reachable. If it isn't, the setup exits with an error code. Before, it was just silently failing and no error was raised.
- ~~The implemented feature is covered by an appropriate test.~~
=> tests: Add keycloak check to e2e test setup

kubernetes/loculus/values.yaml
preview URL: https://lapis035silo0223.loculus.org/
Both changes are very unlikely to break something for Loculus: 
* In LAPIS we implemented additional checks on the database config. If something changes for Loculus, then LAPIS will crash on startup.
* In SILO we fixed a bug in a code path of the preprocessing that is not used by Loculus.
* **lapis:** validate that `lapisAllowsRegexSearch`-fields are of type string ([97b3ce9](https://github.com/GenSpectrum/LAPIS/commit/97b3ce912c7b28304aec823fd6c794c9d9a99525))
* **lapis:** validate that metadata fields do not contain the reserved character `.` ([97b3ce9](https://github.com/GenSpectrum/LAPIS/commit/97b3ce912c7b28304aec823fd6c794c9d9a99525)), [#976](https://github.com/GenSpectrum/LAPIS/issues/976)
* **preprocessing:** enforce exact match …
=> chore(kubernetes): update to LAPIS 0.3.5, SILO 0.2.23

website/package-lock.json
I think this resolves #3007 
https://github.com/loculus-project/loculus/actions/runs/11346512598/job/31555755856 (I ticked "all browsers")
preview URL:
=> chore(website): Update playwright to 1.48.0

website/src/components/Navigation/OrganismSelector.astro, website/src/components/SearchPage/SeqPreviewModal.tsx, website/src/components/SearchPage/Table.tsx, website/src/components/SequenceDetailsPage/SequenceEntryHistoryMenu.tsx, website/src/components/SequenceDetailsPage/SequencesBanner.astro, website/src/components/SequenceDetailsPage/SequencesDataTableTitle.astro, website/src/pages/seq/[accessionVersion].fa/index.ts, website/src/pages/seq/[accessionVersion].tsv/index.ts, website/src/pages/seq/[accessionVersion]/getSequenceDetailsTableData.ts, website/src/pages/seq/[accessionVersion]/index.astro, website/src/pages/seq/[accessionVersion]/versions.astro, website/src/pages/seq/sequenceDownload.ts, website/src/routes/routes.ts, website/src/services/lapisClient.ts, website/src/styles/base.scss, website/src/types/lapis.ts, website/src/utils/createDownloadAPIRoute.ts, website/src/utils/shouldMiddlewareEnforceLogin.spec.ts, website/tests/pages/sequences/accession.fa.spec.ts, website/tests/pages/sequences/accession.spec.ts, website/tests/pages/sequences/sequences.page.ts
resolves #2019
preview URL: https://feat-2019-download-indivi.loculus.org/ [Edited by Theo: fyi this gets truncated so you probably need to look it up in ArgoCD - ping on Slack if you don't have the credentials to access that]
Turn the download button into a selection dropdown instead, where you can select to either download FASTA or a Metadata TSV.
=> feat: Allow downloading metadata in the sequence detail view

website/astro.config.mjs
Resolves a bug when running `npm run dev`: https://github.com/microsoft/playwright/issues/33031
=> fix(website): exclude chromium-bidi from vite optimisation

website/src/components/SearchPage/SeqPreviewModal.tsx
tries to resolve confusion that the download button looks like a button but is actually now a dropdown menu
http://kebabdownload.loculus.org
before:
after:
IMO this is a bit better but I don't feel super strongly.
=> feat(website): add menu icon to download icon

.github/workflows/preprocessing-tests.yaml, preprocessing/nextclade/src/loculus_preprocessing/processing_functions.py, preprocessing/nextclade/tests/test.py
preview URL: https://prepro-raise.loculus.org
Under certain circumstances, prepro annotates sequences with entries, but doesn't log nor error - which makes it hard to detect that something is wrong for admins.
This PR makes sure we log and/or raise in those situations.
Previously, there would be nothing in the logs when a preprocessing function is misspelled in config.
Related to https://loculus.slack.com/archives/C05G172HL6L/p1728487952627419?thread_ts=1728487780.666019&cid=C05G172HL6L
Also makes a few small changes by using simple string concatenation when that is more concise than f-strings.
Now it logs errors when there's a config error:
```
ERROR:root:Processing failed for PPD_000QKNP.1 with error: Processing for spec: ProcessingSpec(inputs={'date': 'sampleCollectionDate'}, …
```
=> fix(prepro): log and raise if prepro encounters config error to allow early detection

website/src/components/SearchPage/DownloadDialog/DowloadDialogButton.tsx, website/src/components/SearchPage/DownloadDialog/DownloadDialog.tsx
preview URL:
The download button didn't have a fixed with, and so the width dependent on the amount of width of the characters inside. This PR fixes the width to a fixed value so the layout doesn't change anymore when the number of selected sequences changes.
n/A
=> fix: prevent download button layout shifts

backend/src/main/resources/application.properties
see https://loculus.slack.com/archives/C05G172HL6L/p1729529276846749
https://fix-timeout.loculus.org
Fixes #3033
=> fix(backend): allow requests to last 10hr, instead of just 30s

website/src/components/SeqSetCitations/SeqSetList.tsx
When creating a seqset and then editing it, the same seqset ID will come up twice in the seqset table. The key property should be unique.
This PR adds the version to the key to make it unique, thus fixing the error.
=> fix: add seqset version to row key to make key unique

backend/src/main/resources/logback.xml, backend/src/test/resources/logback-test.xml
preview URL:
See https://github.com/GenSpectrum/LAPIS/pull/996
We had the same issue here
https://logback.qos.ch/codes.html#layoutInsteadOfEncoder
=> fix(backend): get rid of logger config deprecation warnings in the log

.github/dependabot.yml
Since we now sometimes get CI failure, easier to have things less grouped
=> chore(ci): split gradle dependabot updates into patch and minor

kubernetes/loculus/values.yaml
preview URL: https://removeunuseddbhost.loculus.org/
AFAICS, this was introduced here:
https://github.com/loculus-project/loculus/commit/e76d3ebfcaa46030ed78d32a45529c4ff87b1941#diff-8c45270b76bf36f08f571b509614d6672984b0604844a487a0ad3ba2ad794943R1467 But then later not used anymore:
https://github.com/loculus-project/loculus/commit/43bdbf0876b7d04a20b060522874b7c31a809a50#diff-2770ff9da854df0d7d21f7b41e229f84677a4b0562825d22e84ca421f8a4e3f8R66
Currently, the Loculus docs also don't mention it.
I did not find any usage. But it would be good to have a second pair of eyes checking.
Update: This field does not exist in ppx - so no need to config changes when rolling out to ppx.
~~- [ ] The implemented feature is covered by an …
=> fix(config): remove unused `secrets.database.data.host` in values.yaml

.github/workflows/preprocessing-tests.yaml, preprocessing/nextclade/.justfile, preprocessing/nextclade/README.md, preprocessing/nextclade/pyproject.toml, preprocessing/nextclade/src/loculus_preprocessing/backend.py, preprocessing/nextclade/src/loculus_preprocessing/config.py, preprocessing/nextclade/src/loculus_preprocessing/datatypes.py, preprocessing/nextclade/src/loculus_preprocessing/prepro.py, preprocessing/nextclade/src/loculus_preprocessing/processing_functions.py, preprocessing/nextclade/src/loculus_preprocessing/sequence_checks.py, preprocessing/nextclade/tests/factory_methods.py, preprocessing/nextclade/tests/test.py, preprocessing/nextclade/tests/test_processing_functions.py
Preview: https://test-prepro-v2-cr.loculus.org/
Use pytest instead of unittest: results in nicer test result view:
Just run via `pytest`
=> Small tweaks to test-prepro-v2

ingest/config/defaults.yaml, ingest/scripts/format_ncbi_metadata.py, kubernetes/loculus/values.yaml
resolves #
preview URL:
Checkout https://github.com/pathoplexus/pathoplexus/commit/ce68b92e8b01055a36b5fa60893876078963bf98 to perform regression testing (ignore authors as should be different) by comparing this branch with Loculus main: 
```sh
micromamba activate pp-integrity
cd tests/regression-testing 
snakemake results/ebola-zaire.meta.main.format-authors-cleanup.diff 
snakemake results/cchf.meta.main.format-authors-cleanup.diff 
snakemake results/west-nile.meta.main.format-authors-cleanup.diff 
```
There is no diff in the ebola-zaire, cchf and west nile metadata - between main or the format-authors branch
=> Format authors cleanup

website/Dockerfile
Increase the memory availability to the website to avoid crashes on sequences with very large numbers of deletions
=> fix(website): Increase website memory limit to 1024 mb to avoid crashes with very large numbers of deletions

deploy.py, kubernetes/loculus/templates/_common-metadata.tpl, kubernetes/loculus/templates/_lapis-urls.tpl, kubernetes/loculus/templates/loculus-website-config.yaml
preview URL: https://makewebsitepublicurlsconf.loculus.org/
For GenSpectrum, we need to be able to set the public URLs of the services that the website accesses. Actually this is a generalized case of the "codespaceName" feature, so my approach was to pull out the `$.Values.codespaceName` parameter from the Helm chart into `deploy.py`. The website URLs can be set in values.yaml via
```
website:
runtetimeConfig:
public:
backendUrl: ...
lapisUrlTemplate: https://%organism%.my.lapis.org 
keycloakUrl: ...
```
This is the first step. In a second I will need to do something similar for Keycloak: #3071.
=> feat(kubernetes): make public runtime config urls of the website configurable

deploy.py, kubernetes/loculus/templates/_common-metadata.tpl, kubernetes/loculus/templates/_keyclaok-url.tpl, kubernetes/loculus/templates/keycloak-config-map.yaml, kubernetes/loculus/templates/keycloak-deployment.yaml, kubernetes/loculus/values.yaml
preview URL: https://makekeycloakconfigurable.loculus.org/
This is a follow up to https://github.com/loculus-project/loculus/pull/3063.
* Fully removes `Values.codespaceName`. Instead, everything is configured in `./deploy.py` (for codespaces).
* We also need to be able to configure the frontend url of Keycloak.
* Also we don't want that anyone can register (or login via 3rd party providers).
=> Make keycloak configurable

kubernetes/loculus/templates/keycloak-config-map.yaml
preview URL:
If `disableEnaSubmission: true`, then I don't want to be forced to configure a `externalMetadataUpdaterPassword`
=> fix(kubernetes): don't create `external_metadata_updater` user when `disableEnaSubmission`

website/src/styles/mdcontainer.scss
- Give h3 proper top margin (and also add h4 just in case)
- Give images some y margin
Relates to https://github.com/pathoplexus/pathoplexus/pull/262
See https://loculus.slack.com/archives/C05GWA22R19/p1730378998996159?thread_ts=1730377039.594559&cid=C05GWA22R19
=> feat(website): improve css for markdown pages

.github/workflows/schema-dump.yml, backend/docs/db/schema.sql
resolves #2791 
Adds CI to capture the DB schema after all migrations in `backend/docs/db/schema.sql`. It calculates what this is and if it doesn't match the current captured file the check fails. To make the check pass you can add the `update_db_schema` label which will cause the CI to write over that schema file with the current schema.
Purpose: to make it easy to see diffs in schema, allows seeing the current schema without having to manually add up all migrations in one's head
Limitations:
CI does not re-run after the auto-update. I consider that out of scope for this PR.
I'm not sure if migrations will change order - maybe there is a way to make the order more deterministic?
=> feat(ci): dump current db schema automatically

website/README.md, website/src/styles/mdcontainer.scss
resolves #
preview URL:
Adds an outline to images in the docs: as any explanatory images of how our website works include text which is in the same color and format as the docs this can be confusing, here I just add a very simple border around images to make it clearer that they are images: 
Previously:
=> feat(docs): Add an image-border

kubernetes/loculus/values.yaml, kubernetes/loculus/values_preview_server.yaml
resolves #3158
preview URL: https://additional-head.loculus.org
This removes Plausible from the default `additionalHeadHTML` config but instead adds it only for our preview deployments.
- ~~[ ] All necessary documentation has been adapted.~~
- ~~[ ] The implemented feature is covered by an appropriate test.~~
=> fix(confg): remove Plausible from default additionalHeadHTML

docs/astro.config.mjs, docs/src/content/docs/for-users/search-sequences.md, website/src/components/SearchPage/SearchForm.tsx, website/src/components/SearchPage/searchFormHelpDocsUrl.ts, website/src/pages/api-documentation/authenticationApiDocsUrl.ts, website/src/pages/api-documentation/index.astro, website/src/pages/docs/how-to/search-sequences-website.mdx
Resolve #3140 and resolve #3160
preview URL: https://redirect-to-docs.loculus.org
~This adds a redirect to the Loculus docs from the two locations where Pathoplexus has actual docs pages but not Loculus. This also copies over the mutation search docs from Pathoplexus to the Loculus docs.~
~It unfortunately doesn't seem to possible to have a server-side redirect in .mdx, so I had to create .astro files instead. This means that we have to delete these files on the Pathoplexus-side again because .astro files preceed .mdx files. @theosanderson, do you think that's a reasonable solution?~
The search form help button and the link to the authentication API docs now point to the Loculus docs. The variables are in separate files so that they can be easily overwritten by Pathoplexus. Here is a PR …
=> feat!(website): add redirects to docs and add search sequences docs

website/src/components/Submission/DataUploadForm.tsx, website/src/components/Submission/dataUploadDocsUrl.ts
Like #3163 but for the "help pages" link on the submit page.
Preview: https://upload-help.loculus.org
=> feat!(website): change link to the data upload docs

docs/src/content/docs/for-administrators/my-first-loculus.md
Reorder tutorial to try to avoid a problem @DrYak encountered, and use `<pre>` for TSV that was being turned into spaces.
https://docs-docs-update.loculus.org/for-administrators/my-first-loculus/#testing-it-out-with-some-data
(We should do a more substantial change in the future to avoid having to delete the pod at all, which is too complicated for this tutorial)
Thanks to @DrYak and @chaoran-chen
=> docs: Fixes to my-first-loculus.md

ingest/Snakefile, ingest/config/defaults.yaml, kubernetes/loculus/templates/ingest-config.yaml, kubernetes/loculus/templates/loculus-preprocessing-config.yaml, kubernetes/loculus/values.yaml, preprocessing/nextclade/README.md, preprocessing/nextclade/src/loculus_preprocessing/config.py, preprocessing/nextclade/src/loculus_preprocessing/prepro.py
resolves #
preview URL: https://allow-custom-datasets.loculus.org/
This PR allows multi-segmented pathogens to use nextclade datasets from different servers and of different names in the server.
Currently we assume all datasets of a multi-segmented organism are in the same folder on the same server and that that folder has a sub-folder with the name of that respective pathogen - this might not always be the case.
This PR should have no effect on our current pathogens. 
It also allows us to not have to define nucleotide sequences in the ingest and prepro configs separately. 
I removed the preview to save on space - but it has no averse affect:
=> feat(ci, ingest, prepro): Allow custom nextclade datasets

backend/src/main/kotlin/org/loculus/backend/controller/SeqSetCitationsController.kt, backend/src/main/kotlin/org/loculus/backend/service/seqsetcitations/SeqSetCitationsDatabaseService.kt, backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt, backend/src/test/kotlin/org/loculus/backend/controller/seqsetcitations/CitationEndpointsTest.kt
resolves #
preview URL:
In preparation for this: https://github.com/loculus-project/loculus/issues/1000 where I want to return metadata which requires the `organism` to be known in getSequences, I decided it would make sense to split the usage of the `getSequences` function that _doesn't_ use the `organism` out into its own function.
I added a new function that does exactly what is needed for the usage in seq set citations, which - I think - makes that code path easier to understand and also makes the `getSequences` function (and the changes to come) easier.
n/a
=> refactor getSequences usage in SeqSetCitationsController

docs/src/content/docs/reference/helm-chart-config.mdx, kubernetes/loculus/templates/_common-metadata.tpl, kubernetes/loculus/values.yaml, website/src/components/IndexPage/WelcomeMessage.astro, website/src/pages/index.astro, website/src/types/config.ts
resolves #3161
preview URL: https://welcome-message.loculus.org
This adds an optional `welcomeMessageHTML` config to allow an admin to configure the welcome message.
See #3217
- ~~[ ] The implemented feature is covered by an appropriate test.~~
=> feat(website): make welcome message configurable

.idea/runConfigurations/BackendApplicationKt.run.xml, backend/src/main/kotlin/org/loculus/backend/config/BackendSpringConfig.kt, backend/src/main/kotlin/org/loculus/backend/controller/SeqSetCitationsController.kt, backend/src/test/kotlin/org/loculus/backend/controller/seqsetcitations/SeqSetEndpointsDisabledTest.kt, backend/src/test/resources/application.properties, backend/start_dev.sh, docs/src/content/docs/reference/helm-chart-config.mdx, kubernetes/loculus/templates/_common-metadata.tpl, kubernetes/loculus/templates/loculus-backend.yaml, kubernetes/loculus/values.yaml, website/src/components/Navigation/Navigation.astro, website/src/components/Navigation/SandwichMenu.tsx, website/src/config.ts, website/src/pages/seqsets/[seqSetId].[version].astro, website/src/pages/seqsets/index.astro, website/src/routes/navigationItems.ts, website/src/types/config.ts
resolves #3210
preview URL: https://3210-allow-disabling-of-s.loculus.org/
I grouped the seqSet config values. The values.yaml section can look like
```
seqSets:
enabled: false
``` 
or
```
seqSets:
enabled: false
crossRef: null
``` 
or
```
seqSets:
enabled: true
crossRef:
DOIPrefix: "placeholder"
endpoint: "https://test.crossref.org"
``` 
When `seqSets. enabled == false`, 
* the backend endpoint are disabled
* the website SeqSets navigation item is disabled
* the SeqSets pages on the website return 404
BREAKING CONFIG CHANGES:
* `enableCrossRefCredentials` was removed. Use `seqSets.enabled` instead.
* moved `crossRef` to `seqSets.crossRef`
=> feat!: allow disabling of seqsets [CFG]

docs/src/content/docs/reference/helm-chart-config.mdx, kubernetes/loculus/templates/_common-metadata.tpl, kubernetes/loculus/templates/_siloDatabaseConfig.tpl, kubernetes/loculus/values.yaml, website/src/types/config.ts, website/src/utils/search.ts
resolves #2684 
preview URL: https://feat-2684-substring-searc.loculus.org
Add support for regex search for more fields, by making regex-searchability configurable in the Helm chart values.yaml.
Support is enabled for submissionId, authors, authorAffiliations, specimenCollectorSampleId
TODO
=> feat!: Add substring search support for more fields

backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt, backend/src/test/kotlin/org/loculus/backend/controller/submission/GetDataToEditEndpointTest.kt
https://fix-unable-to-edit.loculus.org/
resolves #3224
This line was added in https://github.com/loculus-project/loculus/pull/3125 accidentally
This is another reason to potentially rename this endpoint to avoid confusion as Chaoran suggested once
=> fix(backend): fix the inability to access revision form due to checking status 

backend/src/test/kotlin/org/loculus/backend/controller/submission/DeleteSequencesEndpointTest.kt
resolves https://github.com/loculus-project/loculus/issues/3235
Came up frequently while working on #3232 so I decided to fix it (but break out into separate PR to keep that PR clean)
=> chore(backend): fix flaky test that made wrong assumptions about order being guaranteed

docs/src/content/docs/reference/helm-chart-config.mdx, kubernetes/loculus/templates/_common-metadata.tpl, kubernetes/loculus/values.yaml, website/src/config.ts, website/src/middleware.ts, website/src/middleware/submissionPagesDisablingMiddleware.ts, website/src/pages/organism-selector/[redirectTo].astro, website/src/routes/navigationItems.ts, website/src/types/config.ts
resolves #3211
preview URL: https://3211-make-it-possible-to.loculus.org/
Adds 3 new config values in the `values.yaml`:
```
website:
websiteConfig:
enableLoginNavigationItem: false
enableSubmissionNavigationItem: false
enableSubmissionPages: false
``` 
Locally, when setting all new config values to false:
=> make it possible to disable the submit workflow on the website

kubernetes/loculus/templates/keycloak-database-standin.yaml, kubernetes/loculus/templates/loculus-database-standin.yaml, kubernetes/loculus/values.yaml
resolves #3254
preview URL: https://persistence.loculus.org
Need to revert from true to false before merging.
Allows not reloading the main and keycloak dbs for each commit in preview/dev deployments through values.yaml
Note that the database is 20+ minutes old while backend was replaced recently, that's what we can do now:
=> feat(config): allow dev standin dbs to be semi-persistent through values.yaml

backend/src/test/kotlin/org/loculus/backend/controller/TestHelpers.kt, backend/src/test/kotlin/org/loculus/backend/controller/submission/ApproveProcessedDataEndpointTest.kt, backend/src/test/kotlin/org/loculus/backend/controller/submission/DeleteSequencesEndpointTest.kt
resolves #3242 
This should avoid most of the flakes due to similar wrongly strong assumptions about SQL result order being stable without explicit sorting.
I can't find any more instances of `jsonPath("\$[*]`. 
But I should also look for `jsonPath("\$[0]` which I haven't done. Just noticed some tests like this in the revocation tests.
=> chore(backend): fix some more racy backend tests by not asserting on exact order

backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt, backend/src/test/kotlin/org/loculus/backend/controller/TestHelpers.kt, backend/src/test/kotlin/org/loculus/backend/controller/submission/RevokeEndpointTest.kt
Fixes #3244
https://theosanderson-fix-revoked.loculus.org/
Update the submitter of a revoked sequence to the revoker
* Modify `backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt` to set the `submitterColumn` to the revoker's account during the revocation process
* Change the `revoke` function to use the revoker's username for the `submitterColumn` instead of cloning the old submitter information
Tested that autoapprove no longer happens:
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/loculus-project/loculus/pull/3246?shareId=b9d63876-b575-4564-b2fb-3c100518daf2).
=> fix(backend): Fix submitter of revoked sequences to be the revoker

docs/astro.config.mjs
resolves #2952
preview URL: https://docs-plausible.loculus.org
This adds Plausible to the Loculus homepage/docs.
=> docs: add Plausible analytics

backend/src/test/kotlin/org/loculus/backend/controller/EndpointTestExtension.kt
This would have made it immediately clear what the reason for the test failures in https://github.com/loculus-project/loculus/pull/3259 was. So good to have for future.
Also truncate in one go for simplicity and maybe also performance.
=> test(backend): throw when database clearing fails in tests

backend/docs/db/schema.sql, backend/src/main/resources/db/migration/V1.6__add_sequence_entries_preprocessed_data_foreign_key.sql, backend/src/test/kotlin/org/loculus/backend/controller/EndpointTestExtension.kt, backend/src/test/kotlin/org/loculus/backend/controller/debug/DeleteAllSequenceDataEndpointTest.kt
resolves #3250, alternative to #3252
preview URL: https://delete-processed2.loculus.org
This adds a foreign key to `sequence_entries_preprocessed_data` for `accession` and `version`.
- ~~[ ] All necessary documentation has been adapted.~~
- ~~[ ] The implemented feature is covered by an appropriate test.~~
=> fix(backend): add foreign key to delete preprocessed data

docs/astro.config.mjs, docs/src/content/docs/for-administrators/setup-with-k3d-and-nginx.mdx
preview URL: https://docs-tutorial-k3d-nginx.loculus.org/for-administrators/setup-with-k3d-and-nginx/
This adds a tutorial about how to deploy Loculus to a server with a domain. It's based on the GenSpectrum deployment by @fengelniederhammer.
=> docs: add tutorial for setup with k3d and nginx

keycloak/keycloakify/package.json, keycloak/keycloakify/yarn.lock
- I screwed up the yarn lockfile in #3318: Remove unused deps
- Cherry pick all keykloakify updates together: #3314 #3315 #3316 #3317
- Update yarn to 4.5.3
=> chore(keycloakify): aggregate major version bumps

backend/src/main/kotlin/org/loculus/backend/controller/SubmissionController.kt, backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt, website/src/components/ReviewPage/ReviewPage.tsx, website/src/hooks/useSubmissionOperations.ts, website/src/pages/[organism]/submission/[groupId]/index.astro, website/src/services/backendApi.ts, website/src/types/backend.ts
resolves #3095, resolves #1612, resolves #3269, resolves #2880
helps with #3267
preview URL: https://profile-get-seqs.loculus.org
@fhennig correctly identified that the way we calculated status counts in getSequences was the culprit behind the inconsistent total counts. 
We issued 4 independent db queries one after the other. In between statuses changed. What made it worse was that each of the calls was hugely inefficient, using a join on data use terms, ordering by accession column and much more that is totally unnecessary for the counts calculation.
The fluctuation could be fixed by higher transaction isolation but this is much much faster and efficient so should be enough (I've profiled with simple logs and tested).
Also fixes fact that log message misses mention of some filters. …
=> fix(backend,website): calculate status counts efficiently & request only aggregates for submission portal

docs/src/content/docs/for-administrators/existing-preprocessing-pipelines.md, kubernetes/loculus/values.yaml, preprocessing/nextclade/environment.yml, preprocessing/nextclade/src/loculus_preprocessing/processing_functions.py, preprocessing/nextclade/tests/test_processing_functions.py
Discussed on Slack: https://loculus.slack.com/archives/C05G172HL6L/p1732110859357449
preview URL: https://date-ranges.loculus.org
- Replace Ebola Zaire with Ebola Sudan to have a small, fast loading, real organism (Zaire is 3k sequences, Sudan 150, we already have large ones with WNV and CCHF). This speeds up time to useful preview.
- Change processing of dates to make `sampleCollectionDate` be of type string and of form `YYYY` or `YYYY-MM` or `YYYY-MM-DD` (instead of type date with `YYYY-MM-DD` and MM and DD forced to 01 if missing)
- Introduce new processed data fields of type date `sampleCollectionDateRangeLower` and `sampleCollectionDateRangeUpper`
- Upper bound of date range is constrained by submission date (sequences cannot be from samples collected after they were submitted)
- …
=> feat(preprocessing): parse dates into date ranges to correctly represent incomplete dates

website/src/components/IndexPage/OrganismCard.astro, website/src/pages/index.astro
Small tweak to line up organism cards with other text on the index page
https://test-tweak-to-organism-ca.loculus.org/
=> fix(website): line up organism cards with other UI elements

website/src/components/SequenceDetailsPage/DataTableEntryValue.tsx, website/src/components/Submission/DataUploadForm.tsx, website/src/styles/base.scss
resolves https://github.com/loculus-project/loculus/issues/3341 and various other problems
preview URL: https://breakword.loculus.org/
becomes
We were using `break-all` which allows wrapping newlines very arbitrarily.  Now we only use `break-words`
.
=> fix(website): Adjust break all to break word

backend/docs/db/schema.sql, backend/src/main/kotlin/org/loculus/backend/model/ReleasedDataModel.kt, backend/src/main/resources/db/migration/V1.7__add_table_update_trigger_for_data_use_terms.sql
fixes #3354
preview URL: https://fix-etag.loculus.org
I had forgotten to include `data_use_terms_table` updates in the list of tables whose update should reset the etagg
=> fix(backend): reset etag for data_use_terms_table updates

kubernetes/loculus/values.yaml
preview URL: https://lapis0310.loculus.org/
Those are two uncritical LAPIS version updates: One just affects the docs (which Loculus doesn't use), the other introduces a feature such that LAPIS can tell its version:
https://lapis-lapis0310.loculus.org/cchf/sample/aggregated
```
{
"data": [
{
"count": 0
}
],
"info": {
...
"lapisVersion": "0.3.10"
}
}
``` 
* **lapis:** add LAPIS version to info response ([#1019](https://github.com/GenSpectrum/LAPIS/issues/1019)) ([7d8d713](https://github.com/GenSpectrum/LAPIS/commit/7d8d7132150896b85244dbd240b15005b2aa47ec))
* **lapis-docs:** mark sections of the docs that are generated from the config ([b2009eb](https://github.com/GenSpectrum/LAPIS/commit/b2009eb4674fe1f9d790a5f64e80d4c7f0bb2808)), closes …
=> chore(kubernetes): upgrade to LAPIS 0.3.10

kubernetes/loculus/templates/keycloak-deployment.yaml
Based on the following log warnings:
```
2024-12-03 18:56:06,497 WARN  [org.keycloak.services] (main) KC-SERVICES0110: Environment variable 'KEYCLOAK_ADMIN' is deprecated, use 'KC_BOOTSTRAP_ADMIN_USERNAME' instead
2024-12-03 18:56:06,497 WARN  [org.keycloak.services] (main) KC-SERVICES0110: Environment variable 'KEYCLOAK_ADMIN_PASSWORD' is deprecated, use 'KC_BOOTSTRAP_ADMIN_PASSWORD' instead
```
resolves #
preview URL:
=> chore(kubernetes): migrate away from deprecated env variable names

backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt
=> fix(backend): lock rows that are being streamed to pipeline

backend/src/main/resources/application.properties
followup to #3032
I used the wrong syntax, `server.` instead of `spring.`
preview URL: https://fix-timeout.loculus.org
see: https://loculus.slack.com/archives/C05G172HL6L/p1733397193081819
Proof that it now actually works, comparing main with this branch:
=> fix(backend): use correct syntax to extend async timeout

.gitignore, website/src/components/SearchPage/SearchFullUI.tsx, website/src/components/SearchPage/Table.tsx
resolves https://github.com/loculus-project/loculus/issues/3382
preview URL: https://search-table-2.loculus.org/ebola-sudan/search?
Ensures that the download button always stays on the page even when the table is wider than the screen, which doesn't happen at the moment
=> fix(website): don't allow search page to expand beyond window width - instead make the table scroll

.gitignore, docs/src/content/docs/reference/helm-chart-config.mdx, kubernetes/loculus/templates/_common-metadata.tpl, kubernetes/loculus/values.yaml, website/src/components/SearchPage/Table.tsx, website/src/types/config.ts
resolves #3378
preview URL: https://column-order.loculus.org/
Adds an optional index to metadata items that determines their order. Currently this applies only to the search page table columns. We could expand this to e.g. the search fields but this would be a bit more complex, so is considered out of scope for now. The order of fields is `accession, [lower order index], [higher order index], [higher still..], [fields without order index specified]`
=> feat(website): Column order for search table

kubernetes/loculus/silo_import_job.sh
It truned out that `jq -c '.'` was rate limiting and causing significant extra processing time.
New command has been tested for correctness and performance, still validates.
see https://loculus.slack.com/archives/C05G172HL6L/p1733500150097089?thread_ts=1733478069.696049&cid=C05G172HL6L
https://speed-up-silo-prepro.loculus.org
=> perf(silo-prepro): speed up by using more efficient jq command

website/src/styles/base.scss
Found by @corneliusroemer. Fixes overflows on seq details page. https://loculus.slack.com/archives/C05G172HL6L/p1733766470652209?thread_ts=1733766069.701169&cid=C05G172HL6L
----
Co-authored-by: Cornelius Roemer <corneliusroemer@users.noreply.github.com>
=> fix(website): word-break: break-word;

website/src/components/SearchPage/Table.tsx
Now that we have lots of columns with defined min widths on PPX, when you add a new column it is given essentially zero width, and looks absurd.
Preview: https://theosanderson-patch-1.loculus.org/
Instead we should give a sensible minimum width, for now I'm going for 130px.
=> fix(website): Set min width to 130px for columns without defined widths

website/src/components/SearchPage/DownloadDialog/DownloadDialog.spec.tsx, website/src/components/SearchPage/DownloadDialog/DownloadDialog.tsx, website/src/components/SearchPage/DownloadDialog/DownloadForm.tsx, website/src/components/SearchPage/DownloadDialog/OptionBlock.tsx, website/src/components/SearchPage/DownloadDialog/SequenceFilters.tsx, website/src/components/SearchPage/SearchFullUI.tsx, website/src/components/common/ActiveFilters.spec.tsx, website/src/components/common/ActiveFilters.tsx, website/src/utils/search.ts
https://filterstyle.loculus.org
Idea is to make it less like an input, and maybe also use some color as accents on the modal. Also use _display names_ for the fields instead of the URL params.
I'll see after the weekend if i still like it!
<details>
<summary>New 'selected sequences' filter</summary>
https://github.com/user-attachments/assets/b0d4be11-d960-443d-b1a9-7939301932bb
</details>
<details>
<summary>before</summary>
</details>
=> style: Trying out a new active-filter style

website/package-lock.json, website/package.json, website/tsconfig.json
preview URL: http://astro-v5.loculus.org
Using the guide: https://5-0-0-beta.docs.astro.build/en/guides/upgrade-to/v5/
Breaking changes to still check out:
- https://5-0-0-beta.docs.astro.build/en/guides/upgrade-to/v5/#changed-actions-submitted-by-html-forms-no-longer-use-cookie-redirects
=> chore(deps): Upgrade to astro v5

ingest/scripts/filter_out_depositions.py, ingest/scripts/format_ncbi_metadata.py, ingest/scripts/prepare_metadata.py
resolves #
preview URL: https://ingest-mem-improvements.loculus.org/
Currently format_ncbi_metadata.py formats each line in a jsonl but then saves each line to a dictionary before writing to a tsv file. Instead we could immedietly write each line to a tsv using csv. 
This is a drastic memory reduction for large datasets, e.g. the peak memory usage for Influenza A is currently 2600M (using htop) with this change we decrease to a constant 14M memory usage. Additionally, we even get a small speed-up (shaving off 0.3sec - seen by adding benchmarking to snakemake rule) as I remove the intermediate pandas df conversion step.
=> feat(ingest): Improve memory usage

backend/src/main/kotlin/org/loculus/backend/api/SubmissionTypes.kt, backend/src/main/resources/db/migration/V1.8__update_error_schema.sql, backend/src/test/kotlin/org/loculus/backend/controller/submission/PreparedProcessedData.kt, preprocessing/dummy/main.py, preprocessing/nextclade/src/loculus_preprocessing/datatypes.py, preprocessing/nextclade/src/loculus_preprocessing/prepro.py, preprocessing/nextclade/src/loculus_preprocessing/processing_functions.py, preprocessing/nextclade/src/loculus_preprocessing/sequence_checks.py, preprocessing/nextclade/tests/factory_methods.py, preprocessing/nextclade/tests/test_config.yaml, preprocessing/nextclade/tests/test_processing_functions.py, preprocessing/specification.md, website/src/components/Edit/DataRow.tsx, website/src/components/Edit/EditPage.spec.tsx, website/src/components/Edit/EditPage.tsx, website/src/components/ReviewPage/ReviewCard.tsx, website/src/types/backend.ts, website/tests/util/preprocessingPipeline.ts, website/vitest.setup.ts
resolves #
preview URL: https://update-error-schema-anya.loculus.org/
Follow up of https://github.com/loculus-project/loculus/pull/932
This PR:
1. Adds both unprocessed and processed metadata field names to the error annotations, updating the types and tests in preprocessing, website and backend.
2. Use the unprocessed and processed (mapped to displayName) metadata field names for errors and warnings in the edit form.
3. Removed the duplicated uneditable processed metadata section from the edit page and move the edit button to the bottom of the edit page.
4. Add a tooltip with information on the name of the input metadata field (currently we just show the display Name which is confusing for users): 
This change isn't "breaking per-se as we include a flyway migration that updates the …
=> feat(website, backend, prepro)!: Update error schema with input and output metadata field names

docs/src/content/docs/reference/helm-chart-config.mdx, kubernetes/loculus/templates/_common-metadata.tpl, kubernetes/loculus/values.yaml, website/src/config.ts, website/src/pages/[organism]/submission/template/index.ts, website/src/types/config.ts, website/tests/pages/revise/revise.page.ts, website/tests/pages/submission/template.spec.ts
resolves #3331
preview URL: http://submission-template.loculus.org
=> feat(website): Make submission template configurable

docs/src/content/docs/reference/helm-chart-config.mdx, kubernetes/loculus/silo_import_job.sh, kubernetes/loculus/templates/_lineage-system-for-organism.tpl, kubernetes/loculus/templates/_siloDatabaseConfig.tpl, kubernetes/loculus/templates/foo.yaml, kubernetes/loculus/templates/lapis-silo-deployment.yaml, kubernetes/loculus/values.yaml, preprocessing/dummy/lineage.yaml, preprocessing/dummy/main.py, website/tests/pages/search/index.spec.ts, website/tests/util/preprocessingPipeline.ts
~~resolves~~ part of #3074 
preview URL: https://lineage-validation.loculus.org
- make the lineage definition configurable in the helm chart
- provide the lineage definition file URLs to the silo import job
- configure silo import to use the lineage definition file
n/A
- ~~The implemented feature is covered by an appropriate test.~~
=> feat: Add lineage definition file to SILO import config

ingest/Snakefile, ingest/environment.yml, ingest/scripts/call_loculus.py, ingest/scripts/parse_nextclade_sort_output.py, ingest/scripts/prepare_metadata.py, preprocessing/nextclade/src/loculus_preprocessing/prepro.py
resolves #
preview URL: https://add-fast-segment-identifi.loculus.org/
1. Add option in Snakefile to either determine segments via [nextclade sort](https://docs.nextstrain.org/projects/nextclade/en/stable/user/nextclade-cli/reference.html#nextclade-sort) or nextclade align. Nextclade sort is extremely fast and when used on influenza data produces highly accurate results. Similar to the nextclade dataset requirement for nextclade align nextclade sort requires a minimzer.json. 
2. Add script to parse nextclade sort output, set dataset with highest score as segment -> allow option to parse `dataset` (identified sorted group's name) into additional metadata fields and add them to the metadata tsv during prepare_metadata. 
3. Fix small bug in prepro.
See this isn action here: …
=> feat(ingest): Add option to use nextclade sort to identify segments for multi-segmented organisms

website/src/components/SearchPage/SearchFullUI.spec.tsx
resolves #3326
- The test failed because it searched for the search field by `name`, but the if the `label` is not given, the sentence case of the name is used. That's why the query returned no results, but the search field was actually there.
- The test now has the label set explicitly.
=> fix: false positive test 'notSearchable' test

website/src/pages/api-documentation/index.astro, website/src/utils/getAuthUrl.ts
resolves #3358
preview URL: https://api-urls.loculus.org/api-documentation
This displays the API URLs directly on the API documentation page.
- ~~[ ] All necessary documentation has been adapted.~~
- ~~[ ] The implemented feature is covered by an appropriate test.~~
=> feat(website): show API URLs on API documentation page

backend/src/main/kotlin/org/loculus/backend/api/DataUseTerms.kt, backend/src/main/kotlin/org/loculus/backend/service/datauseterms/DataUseTermsDatabaseService.kt
A tiny refactoring to avoid having the check `restrictedUntilString == null` at two places.
=> refactor(backend): reduce redundancy in DataUseTerms.fromParameters()

docs/src/content/docs/reference/helm-chart-config.mdx, kubernetes/loculus/templates/_common-metadata.tpl, kubernetes/loculus/values.yaml, website/src/types/config.ts, website/src/utils/search.ts, website/tests/pages/search/index.spec.ts
resolves #3325 
preview URL: http://column-hiding.loculus.org
- Adds a new metadata config setting: `hideInSearchResultsTable` which you can set to hide a column in the Column visibility dialog.
Nothing to see really.
- ~~The implemented feature is covered by an appropriate test.~~
=> Make it possible to hide fields from the table

kubernetes/loculus/silo_import_job.sh, kubernetes/loculus/templates/lapis-silo-database-config.yaml
resolves `TODO` in comment of `silo_import_job.sh`
preview URL: https://tae-remove-silo-preproces.loculus.org/
~SILO 0.5.0 has much better CLI support. We now use this to simplify some of the logic which was in place for the silo import job. This also removed a file template and accompanying docker file mount.~
It is cumbersome to decide whether to supply the lineageDefinitionsFilename or not, if we do it via CLI. Therefore, moving it to the template where the `preprocessing_config` is generated is a much simpler change. Also this lends itself for extensibility once more lineage definitions are supplied for the same organism
=> Remove silo preprocessing_config_merged

website/src/components/SearchPage/SeqPreviewModal.tsx, website/src/components/SequenceDetailsPage/SequenceDataUI.tsx, website/src/components/SequenceDetailsPage/types.ts, website/src/pages/seq/[accessionVersion]/details.json.ts, website/src/pages/seq/[accessionVersion]/index.astro, website/src/types/config.ts, website/src/types/detailsJson.ts, website/src/types/lapis.ts, website/src/types/runtimeConfig.ts
preview URL: https://dontexposeserversideconfi.loculus.org/
The client side code only needs the client side config, which is already contained in the details.json anyway. Also remove some lint ignores by introducing types for the `details.json`.
=> fix(website): don't expose the server side runtime config in `details.json`

deploy.py
I always find myself having to make this change locally as I use conda environments and they don't change `python3`, just `python` to point to the right place. Seeing if (A) it passes CI [it does] (B) anyone objects to it.
=> chore(deployment): Change python3 to python in deploy.py

website/src/components/SearchPage/Table.tsx, website/src/styles/base.scss
resolves #
preview URL: https://tablerowsep.loculus.org/ebola-sudan/search?
This PR adds separators between table rows on the search page. I think it looks quite a bit cleaner:
In the process of implementing it I realised that we, I guess accidentally, basically disabled borders on all tables with hardcoded CSS. Therefore I've removed that.
=> feat(website): Use a row separator in the search table

ingest/Snakefile, ingest/config/defaults.yaml, ingest/scripts/call_loculus.py
resolves #
preview URL: https://stream-batching.loculus.org/
The backend cannot handle submission of over 60k sequences at once, therefore they must be batched. I introduced batching in https://github.com/loculus-project/loculus/pull/3429 but my script required ingest to read both the sequences and metadata files into memory to merge the batches. This was very memory inefficient. 
I now switch to sorting the files using gnu-sort (which should even work for files that are larger than working memory) and then refactor my batching script to read in both metadata and sequence files line by line, creating batched files to be then submitted to the backend. 
Use https://github.com/pathoplexus/pathoplexus/tree/main/data-integrity-tests/regression-testing and switch the URLs to this branch and …
=> feat(ingest): decrease memory usage of submission batching

.github/workflows/integration-tests.yml
We are seeing flakiness due to the wait for pods to be ready not being met in time on `main`. Now I have copied the more complex configuration over from the E2E tests.
=> fix(CI): extend/adjust timeout for pods to be ready before integration tests

kubernetes/loculus/values.yaml
preview URL: https://lapis0312silo052.loculus.org/
The most notable change is that SILO now exposes its version. And we wire that version through LAPIS. -> LAPIS responses will tell you which SILO version was used.
* add the version to the output of the info endpoint ([#680](https://github.com/GenSpectrum/LAPIS-SILO/issues/680)) ([87e3f60](https://github.com/GenSpectrum/LAPIS-SILO/commit/87e3f60c5c517a6ad1e33376886cb72e6fb9cd2c)), closes [#604](https://github.com/GenSpectrum/LAPIS-SILO/issues/604)
* update base image to ubuntu:24.04 ([46d0567](https://github.com/GenSpectrum/LAPIS-SILO/commit/46d056739f7b673ad6a2f3d9daa72f4514abe4e3))
* return an error if reserved value INT32_MIN is used in filter ([042646b](https://github.com/GenSpectrum/LAPIS-SILO/commit/042646be296d7a8d68736ad3b0d8da6715 …
=> chore(kubernetes): update to LAPIS 0.3.13, SILO 0.5.2

kubernetes/loculus/templates/ena-submission-deployment.yaml, kubernetes/loculus/values.yaml
preview URL: https://config-resources.loculus.org
One should now specify an extra resource dict like this (if one uses ena-submission)
https://github.com/loculus-project/loculus/blob/805cebd1d0e5ac466ae93e5c9e40b46438fbd8cf/kubernetes/loculus/values.yaml#L1707-L1712
Allow ENA submission cronjob resources to be configured through values.yaml, so we can give it more memory in production.
=> feat!(deployment): allow ena submission cronjob resources to be specified in values

ena-submission/scripts/get_ena_submission_list.py, ena-submission/src/ena_deposition/call_loculus.py
resolves https://github.com/loculus-project/loculus/issues/3602
preview URL: https://fix-cronjob-memory.loculus.org/
Instead of loading the whole released data into memory, we now process the ndjson line by line using a Python generator (pair programmed together with @corneliusroemer)
I confirmed this sends notifications correctly on Loculus preview.
=> feat(deposition): stream get-released-data in cronjob to avoid OOM

preprocessing/nextclade/src/loculus_preprocessing/processing_functions.py
resolves #3566 and partly https://github.com/loculus-project/loculus/issues/3460
We may want to make this configurable in some way in the future, but for now it addresses the issue that displayName gets referenced when there are date problems which is confusing to users.
When would this change potentially cause a problem: if an admin had a field that was only part of a concatenation, and not used as a standalone field, so the date parsing would never cause an error.
preview URL: https://prop.loculus.org/
=> fix(website): Don't propagate date parsing errors to concatenated fields

ena-submission/src/ena_deposition/__main__.py, ena-submission/src/ena_deposition/call_loculus.py, ena-submission/src/ena_deposition/create_assembly.py, ena-submission/src/ena_deposition/create_project.py, ena-submission/src/ena_deposition/create_sample.py, ena-submission/src/ena_deposition/ena_submission_helper.py, ena-submission/src/ena_deposition/notifications.py, ena-submission/src/ena_deposition/trigger_submission_to_ena.py, ena-submission/src/ena_deposition/upload_external_metadata_to_loculus.py
resolves #
preview URL:
Fixes ruff warning: https://docs.astral.sh/ruff/rules/root-logger-call/
Logs look the same as on main, and still include which file the log message comes from, e.g.:
```
21:29:26    DEBUG (upload_external_metadata_to_loculus.py: 190) - Checking for external metadata to upload to Loculus
21:29:26    DEBUG (    create_sample.py: 383) - Checking for samples to create
21:29:26    DEBUG (    create_sample.py: 159) - Found 0 entries in submission_table in status SUBMITTED_PROJECT
21:29:26    DEBUG (    create_sample.py: 211) - Found 0 entries in submission_table in status SUBMITTING_SAMPLE
21:29:26    DEBUG (    create_sample.py: 263) - Found 0 entries in sample_table in status READY
21:29:27    DEBUG (  create_assembly.py: 608) - Checking for assemblies to create …
```
=> chore(deposition): Improve deposition logging with ruff suggestions

website/src/components/SearchPage/DownloadDialog/DownloadDialog.spec.tsx, website/src/components/SearchPage/DownloadDialog/DownloadUrlGenerator.ts
Fixes #3624
https://theosanderson-fix-downloa.loculus.org/
Update `generateDownloadUrl` method to exclude empty parameters from the generated download URLs.
* Modify `website/src/components/SearchPage/DownloadDialog/DownloadUrlGenerator.ts` to check for empty values before appending them to the URL.
* Add a test case in `website/src/components/SearchPage/DownloadDialog/DownloadDialog.spec.tsx` to verify that empty parameters are excluded from the generated download URLs.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/loculus-project/loculus/pull/3625?shareId=5a59b39e-2d42-4f6d-aa57-4675282a6810).
=> Simplify download URLs generated by Download button (exclude empty fields)

website/src/components/SearchPage/DownloadDialog/DownloadUrlGenerator.ts
resolves #3626
We ended up with duplicate parameters in our download URL - because they were being set both from the download form and from the original search query. Now we overwrite the original search query with whatever is in the form. It's possible that previously we were not actually respecting the form about open data - depending how LAPIS processed duplicate entries. Also we were not respecting the choice about including old versions.
preview URL: http://dupe.loculus.org (no sequences due to ingest issues currently, but you can check the download URLs)
=> fix(website): avoid duplicated items in download url and respect choice to include old versions

website/src/components/OrganismMetadataTable/OrganismMetadataTable.tsx
Otherwise searching is really hard
https://expanded.loculus.org/ebola-sudan/submission/metadataformat
https://loculus.slack.com/archives/C061ZQQM3N1/p1738851331300799
Stop gap while we consider other options
Also expands the width of the name column to avoid too much wrapping
=> feat(website): Make all metadata sections in format page expanded by default

ingest/Snakefile, kubernetes/loculus/templates/ingest-config.yaml, kubernetes/loculus/values.yaml, kubernetes/loculus/values_preview_server.yaml
https://support-gateay-url.loculus.org/
resolves #3629 for now
We are currently unable to connect from NCBI datasets from our Hetzner server
We add the capacity for NCBI datasets to be configured to receive an alternative gateway URL. Atm for our preview servers this is a proxy I am hosting on one of my servers. Hopefully if this causes our traffic to decrease we will get unblacklisted and we can move to a proxy hosted here at Loculus.
=> add support for NCBI gateway URL

website/colors.cjs
In https://github.com/loculus-project/loculus/pull/2085/commits/027c5786f34bc038a93b54e76390a206e5443d33 we added a special color number, `1500`, used for the organism selector.
It looked like this:
(as Pathoplexus still looks).
Later we moved the old Loculus color scheme to Pathoplexus and gave Loculus it's own purpler color scheme. In the new purpler color scheme we forgot to define color `1500` so the organism selector shows up as black.
This looks suboptimal. Here we add a `1500` colour for Loculus.
https://orgselector.loculus.org
=> fix(website): Add special color for organism selector in Loculus color scheme

website/src/components/SearchPage/ScrollContainer.tsx, website/src/components/SearchPage/Table.tsx, website/src/styles/base.scss
resolves https://github.com/loculus-project/loculus/issues/3457
preview URL: https://improve-scroll.loculus.org/
the scrollbar at the bottom of the page is the result of this PR
Makes it obvious you can scroll the table by implementing a custom horizontal scroll bar that always appears. (Written with o3-mini)
Also truncates tooltip expansions on the field which was always a todo and became more important with this since over-long tooltips make native scrollbars appear.
Negatives: will not match the users expected scroll appearance e.g. on windows probably
=> feat(website): Improve scroll behaviour in search table

website/src/components/Edit/DataRow.tsx, website/src/components/Edit/EditPage.spec.tsx, website/src/components/Edit/EditPage.tsx, website/src/pages/[organism]/submission/edit/[accession]/[version].astro, website/vitest.setup.ts
resolves #3544 
preview URL: https://edit-page-sections.loculus.org
Input fields are grouped by the _Headers_ in the metadata definitions.
- ~~All necessary documentation has been adapted.~~ (n/a)
- ~~The implemented feature is covered by an appropriate test.~~ (n/a)
=> feat(website): Group metadata fields on the revision page

kubernetes/loculus/values.yaml
preview URL: https://lapis0314silo053.loculus.org/
This adds an endpoint that let's users query the lineage definitions.
SILO:
* add endpoint that returns the lineageDefinitions for the requested column ([#689](https://github.com/GenSpectrum/LAPIS-SILO/issues/689)) ([69cd9b0](https://github.com/GenSpectrum/LAPIS-SILO/commit/69cd9b0f5947d8b249a1c5431dd425e7f090e50f))
LAPIS:
* **lapis:** expose the lineage definition files used by SILO ([#1073](https://github.com/GenSpectrum/LAPIS/issues/1073)) ([2ac977c](https://github.com/GenSpectrum/LAPIS/commit/2ac977ceab23a6479a343bcee2234c289f88fd4f)), closes [#1034](https://github.com/GenSpectrum/LAPIS/issues/1034)
=> chore(kubernetes): update to LAPIS 0.3.14, SILO 0.5.3

website/src/components/SearchPage/SearchFullUI.tsx
Fixes #3665 fixes https://github.com/loculus-project/loculus/issues/2044
https://theosanderson-fix-paginat.loculus.org/ebola-sudan/search?page=1&orderBy=authors&order=ascending
Update `setOrderByField` and `setOrderDirection` functions to reset pagination to page 1 when sorting.
* Modify `setOrderByField` to set the page state to '1' when changing the order by field.
* Modify `setOrderDirection` to set the page state to '1' when changing the order direction.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/loculus-project/loculus/pull/3667?shareId=f78821ff-7852-4c27-ab7b-6679a4c7a7db).
=> fix(website): pagination reset on search page table resort

website/src/components/SearchPage/SearchFullUI.tsx
Fixes #3572
Add conditional padding to the split view in the browse page to allow scrolling to reach the pagination
* Modify `SearchFullUI.tsx` to add a conditional class to the div containing the recent sequences banner, applying additional padding when `previewHalfScreen` is true.
https://theosanderson-fix-scroll.loculus.org/west-nile/search?
Probably not 100% the most perfect - but does the job for now for a niche component.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/loculus-project/loculus/pull/3669?shareId=9e56555a-41e6-415b-968b-53eec423f3da).
=> fix(website): Fix scroll issue on browse page split view

kubernetes/loculus/templates/ingest-deployment.yaml
resolves #
preview URL: http://www.add-back-apikey.loculus.org/
Discovered by @theosanderson - the api-key was accidentally removed from ingest's env variables: https://github.com/loculus-project/loculus/pull/2473. 
This adds back the api-key - sadly it still doesn't fix our connectivity issue but it good to have!
=> fix(ingest): add back api-key to env variables

docs/src/content/docs/for-administrators/data-use-terms.mdx, website/src/components/DataUseTerms/DataUseTermsSelector.tsx, website/src/components/Submission/DataUploadForm.tsx
- very slightly rephrases text
- links to the specific pages on the two terms of use
- corrects a reference to "Loculus" to Pathoplexus
At some point we should disentangle all references to Pathoplexus and Pathoplexus paths from this, but:
- we can now disable data use terms entirely
- there were already references to Pathoplexus so this doesn't really make it worse
amends docs (to clarify something that was already true):
=> (merging into Anya's PR) Suggestions for data use terms selector

kubernetes/loculus/templates/_resources.tpl, kubernetes/loculus/templates/lapis-silo-deployment.yaml, kubernetes/loculus/values.yaml
Preview: https://organism-scoped-resources.loculus.org/
Adds `organismSpecific` resource requirements, keyed by organism. These are optional - without them everything works as before
Example:
```
resources:
organismSpecific:
dummy-organism:
silo:
requests:
memory: "10Mi"
limits:
memory: "10Mi"
```
Tested working:
=> feat(deployment): organism scoped resource specification

website/src/components/SearchPage/SeqPreviewModal.tsx, website/src/components/SequenceDetailsPage/DataTable.tsx
https://alignment.loculus.org/
Fixes alignment on sequence details page in full screen mode:
before:
after:
=> fix(website): Fix alignment of seq details page

website/src/components/SearchPage/SearchFullUI.tsx
(imo no preview needed)
makes download button line up with table:
vs before:
(ignore the button styling difference - one is moused over)
=> fix(website): improve alignment of download button on search page

ena-submission/README.md, ena-submission/flyway/sql/V1.2__alter_project_table_id.sql, ena-submission/scripts/deposition_dry_run.py, ena-submission/scripts/get_ena_submission_list.py, ena-submission/scripts/test_ena_submission.py, ena-submission/src/ena_deposition/create_assembly.py, ena-submission/src/ena_deposition/create_project.py, ena-submission/src/ena_deposition/create_sample.py, ena-submission/src/ena_deposition/ena_submission_helper.py, ena-submission/src/ena_deposition/submission_db_helper.py, ena-submission/src/ena_deposition/upload_external_metadata_to_loculus.py, kubernetes/loculus/templates/keycloak-config-map.yaml, kubernetes/loculus/values.yaml
resolves https://github.com/loculus-project/loculus/issues/3466
preview URL:
Breaking changes: Please merge the corresponding PP PR with these changes - https://github.com/pathoplexus/pathoplexus/pull/375
1. Allow input of bioproject and biosample (remove noInput in values.yaml), add description to tell users when to add this
2. Modify the DB table PROJECT_table to not use (group_id, organism) as unique ID -> small DB migration
3. Modify the SUBMISSION_table code to store PROJECT_table's new id for new created bioproject
4. Modify code: if bioproject exists create a new entry in PROJECT_table with the details - do not create a new bioproject, else create new bioproject for (group_id, organism) as before
5. Modify code: if biosample exists create a new entry in SAMPLE_table with details - …
=> feat(deposition)!: Allow groups to specify which BioProject (and BioSample) we upload their sequences into 

kubernetes/loculus/values.schema.json
Resolves #3691
Schema was too strict - as strings that happen to also be integers end up interpreted as integers (at least by Helm).
Same issue also manifests in Pathoplexus, so just excluding Loculus previews from schema check isn't enough.
=> fix(k8s): Also accept integers as shas/branch names in values schema

kubernetes/loculus/values.yaml
resolves https://github.com/loculus-project/loculus/issues/3689
preview URL: http://alig.loculus.org
Renames unexpected header `Alignment states and QC metrics` header to `Alignment and QC metrics`.
Requires same changes made to Pathoplexus
Corresponding PP PR: https://github.com/pathoplexus/pathoplexus/pull/388
=> fix!(deployment): update Alignment states and QC metrics header

kubernetes/loculus/silo_import_wrapper.sh, kubernetes/loculus/templates/lapis-silo-deployment.yaml
Previously, when silo preprocessing started failing after an update to a preview but there was still successful processed data in the shared volume we would not easily observe the processing failure as "-1/0 sequences" in the UI. One would only see the failure in processing logs which would often not be checked (e.g. in testing https://github.com/loculus-project/loculus/pull/3534).
This PR makes silo preprocessing errors more easily observable _in dev environments only_ by _force replacing_ the LAPIS/SILO pod including the shared volume even if there are no code changes between updates (e.g. when only the backend code changes).
Also, we make the silo preprocessing crash rather than happily error without crashing when there are preprocessing errors.
Force replacing is switched on iff …
=> feat(deployment): improve observability of silo preprocessing errors by force replacing pod in development and exiting the process if failed

.github/workflows/datasets-mirror.yml
Mirror NCBI datasets zip folders to Hetzner object storage to reduce load on NIH servers and uncouple our CI from external services.
Right now all Loculus/PPX organisms are covered, we can easily add Taxon IDs for Genspectrum ones @anna-parker 
It scrapes once a day. The zip folder can be downloaded at:
```
https://hel1.your-objectstorage.com/loculus-public/mirror/{TAXONID}.zip
```
Where TAXONID is the taxonid we scrape, e.g. `10244` for mpox.
As a next step, we can optionally use these paths to download the zip folders in ingest.
- Single PUT: The old object remains unchanged; no partial overwrite.
- Multipart Upload: Incomplete parts stay temporarily; must complete or abort the upload.
- They get the old version until the new upload is fully completed.
- No partial or mixed content; …
=> feat(ci): Mirror NCBI datasets results to Hetzner object storage to reduce NIH load and get independence from external service

kubernetes/loculus/values_preview_server.yaml
resolves https://github.com/loculus-project/loculus/pull/3681#issuecomment-2668970273
preview URL: https://enable-flagging-on-previe.loculus.org
=> enable flagging on preview

kubernetes/loculus/values.yaml
preview URL: https://tae-silo-0-5-4.loculus.org
This updates SILO to 0.5.4. That is the version that also contains 2 additional improvements to excessive memory usage
https://github.com/GenSpectrum/LAPIS-SILO/releases/tag/v0.5.4
* add monitoring to log the swapover to datasets ([39f1ed2](https://github.com/GenSpectrum/LAPIS-SILO/commit/39f1ed2ddba4e4711ce850380674b8d41d645d52))
* call malloc_trim after all connections to the old database are finished ([5742a52](https://github.com/GenSpectrum/LAPIS-SILO/commit/5742a521b467d153a2dd633cdacfd7ec3b8080bb))
* tell malloc to give empty heap space back to the OS before every fasta call ([16ce850](https://github.com/GenSpectrum/LAPIS-SILO/commit/16ce850145db75d81f702368f3944692dd0da080))
* prohibit allocation of new Poco threads for incoming …
=> chore(deps): SILO v0.5.4

kubernetes/loculus/values.schema.json
Fixes #3720
Modify the helm schema to allow only a `memory` or only a `cpu` setting in `limits` for `defaultResources`.
* Make `memory` property in `limits` optional.
* Make `cpu` property in `limits` optional.
* Remove the requirement for both `memory` and `cpu` settings in `limits` and `requests`.
* Remove the requirement for both `requests` and `limits` in `defaultResources`.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/loculus-project/loculus/pull/3723?shareId=5c4d8cf3-3953-4997-9bd6-f76378d0cc8c).
=> fix(deployment): make `memory` / `cpu` optional settings in Helm schema

docs/src/content/docs/for-administrators/data-use-terms.mdx, website/src/components/DataUseTerms/DataUseTermsSelector.tsx, website/src/components/Submission/DataUploadForm.tsx, website/src/components/Submission/FileUpload/UploadComponent.tsx
partially resolves https://github.com/loculus-project/loculus/issues/3556
resolves https://github.com/loculus-project/loculus/issues/3555, resolves https://github.com/loculus-project/loculus/issues/3562
preview URL: https://typos.loculus.org/
1. add missing comma
2. replace Files with file
3. update compression statement using @chaoran-chen's suggestion
=> feat(website): improve docs

website/src/components/SearchPage/Table.tsx
preview URL: https://box-content.loculus.org/ebola-sudan/search? vs https://main.loculus.org/ebola-sudan/search?
We specifically add padding to the last column in the table for aesthetic reasons (`last:pr-6`), but this is problematic because we specify widths for each column but those widths include the padding and we don't know which column the user will choose to be last. Here we use [`box-content`](https://tailwindcss.com/docs/box-sizing) so that the specified width is just for the content, excluding any padding. This will likely require us to update all widths to take account of this.
All columns get a bit bigger on our current previews but I think that's ok as they are not tuned much on Loculus (they are more so on PPX)
We may want to make all specified column widths on PPX 16 pixels …
=> fix(website)!: use `box-content` for consistent column widths regardless of position

kubernetes/loculus/templates/keycloak-deployment.yaml
resolves #3618 for now
preview URL: https://authentication-kcflags.loculus.org/admin/master/console (admin/admin)
We upgraded the keycloak environment variable flags without upgrading keycloak itself, meaning an admin account with a known admin password is not created. This is an unfortunate breakage on main for anyone wanting to try out Loculus for their own use, and prevents us logging in ourselves (except on pathoplexus).
Here I add the old flags back as duplicates to mitigate.
=> fix(deployment): add old keycloak flags

website/src/components/SearchPage/DownloadDialog/DownloadDialog.spec.tsx, website/src/components/SearchPage/DownloadDialog/DownloadUrlGenerator.ts, website/src/settings.ts
resolves #3438
preview URL: https://explicit-seq-dataformat.loculus.org
`dataFormat` now specified explicitly for all download links.
For ebola sudan: I checked the links for all download types (metadata, unaligned seq, aligned, ...) and verified they all have the dataFormat parameter. I downloaded all for variants and the downloads all returned a file (no error).
=> feat(website): Explicitly set `dataFormat=fasta` for sequence downloads

docs/src/content/docs/reference/helm-chart-config.mdx, kubernetes/loculus/values.schema.json
resolves https://github.com/loculus-project/loculus/issues/3782
preview URL: https://docs-fix-values-docs.loculus.org/reference/helm-chart-config
Clean up the helm template docs
=> fix(docs): improve helm template values docs

website/src/components/Edit/InputForm.spec.tsx, website/src/components/Edit/InputForm.tsx
resolves #3798 
preview URL:
the frontend code for the edit and single-submit form generated FASTAs that had segment headers with no data.
This PR adds a test for this case and fixes it, so empty segments aren't added to the FASTA anymore.
n/A
=> fix(website): fasta was incorrectly generated with empty segments

backend/src/main/kotlin/org/loculus/backend/utils/ParseFastaHeader.kt, backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmitEndpointTest.kt, backend/src/test/resources/sequences_multi_segment.fasta
**BREAKING** because now we do not accept arbitrary segment names in FASTAs anymore.
resolves #3683 
~~preview URL: https://better-error-msg.loculus.org~~ (currently preview isn't on)
- when parsing the fasta headers, already check that the segment ID is in the list of valid segment IDs.
(The "IDs" in the error message has been changed to "names")
=> feat!: Improve error message for fastas with missing segment names

kubernetes/loculus/values.yaml, kubernetes/loculus/values_preview_server.yaml
**BREAKING** for PPX - because the ORCiD settings have been removed. To migrate, please include these settings in your own values.yaml.
resolves #3637 
preview URL: https://untangle-values.loculus.org
- move email SMTP settings out.
- remove ORCID setting.
I created an account on the preview, and still got the mail.
- ~~The implemented feature is covered by appropriate, automated tests.~~ (I don't think a test is needed)
=> chore!: move preview/ppx specific Helm Chart settings out of the default values

website/src/components/SearchPage/DownloadDialog/DownloadButton.tsx
preview URL:
Follow-up to #3814 (https://github.com/loculus-project/loculus/pull/3814#discussion_r1987624964). Adds a little message that shows why the download button is disabled when we would need POST request to download sequences with rich fasta headers. The endpoint that handles the custom rich fasta header downloads doesn't support post requests yet.
=> feat(website): show why download button is disabled when query is too long

website/src/components/SequenceDetailsPage/ReferenceSequenceLinkButton.tsx
resolves #3780 
I've changed the display of the table-like rows to use a table instead of fixed-width divs, so the cells expand if the labels get long.
- ~~The implemented feature is covered by appropriate, automated tests.~~
=> fix(website): Fix the format of the reference dialog

kubernetes/loculus/templates/lapis-deployment.yaml
Before this when SILO saturated all LAPIS pods would be restarted
=> fix(deployment): change lapis livenessProbe to readinessProbe and use a liveness probe based on health endpoint

kubernetes/loculus/templates/silo-deployment.yaml
Preview: https://silo-workers.loculus.org
SILO by default only processes 4 requests in parallel (while accepting 64 requests). This is very low, and if all workers are blocked (e.g., due to parallel downloads), the liveliness probe of LAPIS fails, causing Kubernetes to kill LAPIS. By increasing the number of workers, we allow more parallel downloads but also mitigate the problem of LAPIS being killed a bit (#3839 actually fixes it).
=> chore: increase number of SILO workers

kubernetes/loculus/templates/silo-deployment.yaml
preview URL: https://silo-queue.loculus.org
The default number of requests that SILO allows to queue is 64 which is quite low. This PR increases it to 1000. We can of course adapt further (or make it configurable) in the future if needed.
- ~~[ ] All necessary documentation has been adapted.~~
- ~~[ ] The implemented feature is covered by appropriate, automated tests.~~
- ~~[ ] Any manual testing that has been done is documented (i.e. what exactly was tested?)~~
=> chore(deployment): increase SILO API max queued

kubernetes/loculus/templates/lapis-deployment.yaml
Fixes #3843 - though behaviour should be the same
Set the `failureThreshold` property for the readiness and liveness probes in `kubernetes/loculus/templates/lapis-deployment.yaml`.
* Set `failureThreshold` to 3 for the readiness probe.
* Set `failureThreshold` to 3 for the liveness probe.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/loculus-project/loculus/pull/3844?shareId=4802f559-0c54-47b5-87e0-8c143d94ecdd).
=> fix(deployment): add missing value for liveness probe

kubernetes/loculus/silo_import_job.sh
preview URL: https://validemptylineagedefiniti.loculus.org/
An empty file is not a valid lineage definition, because that must be a YAML object on top level.
=> fix(kubernetes): make the "empty lineage definition file" valid YAML

website/src/components/SequenceDetailsPage/SequenceEntryHistoryMenu.spec.tsx, website/src/components/SequenceDetailsPage/SequenceEntryHistoryMenu.tsx, website/tests/pages/sequences/sequences.page.ts
Removes somewhat confusing behaviour of a dropdown that is actually a button, with a more conventional dropdown that displays the current selected version.
preview URL: http://dropdown.loculus.org
=> feat(website): Improve sequence details dropdown a little

website/src/components/SearchPage/DownloadDialog/SequenceFilters.tsx, website/src/components/SearchPage/fields/DateField.spec.tsx, website/src/components/SearchPage/fields/DateField.tsx, website/src/components/common/ActiveFilters.spec.tsx
resolves #3727 , resolves #1556
preview URL: https://timestamp-format.loculus.org
- Render timestamp fields as YYYY-MM-DD
- Check whether a timestamp field is 'From' or 'To' (or neither) and set the HH:MM component to 23:59 for 'To'.
- Added unit test to the `ActiveFilters` component to check that the format is correct for timestamps.
- Added unit test for the `TimestampField` to check if the correct unix timestamp gets set.
=> fix(website): Render timestamp as YYYY-MM-DD instead of UNIX timestamp

website/package-lock.json, website/package.json
Reverts loculus-project/loculus#3866
https://revert-3866-dependabot-np.loculus.org/ebola-sudan/search?
The formatting of the download modal is a bit messed up - this seems to be the cause:
Main:
Vs this PR:
In due course we can merge bumping it whilst fixing the classes to give the original result (and we probably will want to check other forms carefully too)
=> Revert "chore(deps-dev): bump daisyui from 4.12.23 to 5.0.6 in /website"

integration-tests/playwright.config.ts, integration-tests/tests/fixtures/group.fixture.ts, integration-tests/tests/fixtures/sequence.fixture.ts, integration-tests/tests/pages/auth.page.ts, integration-tests/tests/readonly.setup.ts, integration-tests/tests/specs/features/download.spec.ts, integration-tests/tests/specs/features/search.spec.ts, integration-tests/tests/specs/features/sequence-preview-url.spec.ts, integration-tests/tests/specs/features/sequence-view.spec.ts, integration-tests/tests/specs/features/submission-flow.spec.ts
A lot of tests do not edit the data, and creating a new group and submitting a sequence for each test slows down the tests a lot.
I added a base project dependency that submits a single sequence of ebola sudan to use in other tests.
I know this breaks the isolation of the tests, but I'd argue the test speed up is well worth it.
I also replaced a bunch of hard-coded timeouts with loops or waits for elements.
=> feat(integration-tests): use setup project to submit some data to speed up tests

integration-tests/playwright.config.ts, integration-tests/tests/fixtures/group.fixture.ts, integration-tests/tests/fixtures/sequence.fixture.ts, integration-tests/tests/pages/review.page.ts, integration-tests/tests/pages/search.page.ts, integration-tests/tests/readonly.setup.ts, integration-tests/tests/specs/features/download.spec.ts, integration-tests/tests/specs/features/revise-sequence.spec.ts, integration-tests/tests/specs/features/search.spec.ts, integration-tests/tests/specs/features/sequence-preview-url.spec.ts, integration-tests/tests/specs/features/sequence-view.spec.ts, integration-tests/tests/specs/features/submission-flow.spec.ts, website/src/components/Edit/EditPage.spec.tsx, website/src/components/Edit/EditPage.tsx, website/src/components/Edit/InputForm.spec.tsx, website/src/components/Edit/InputForm.tsx, website/src/components/Edit/SequencesForm.spec.tsx, website/src/components/Edit/SequencesForm.tsx, website/src/components/Submission/FileUpload/FileUploadComponent.spec.tsx, website/src/components/Submission/FileUpload/FileUploadComponent.tsx, website/src/components/Submission/FileUpload/fileProcessing.ts, website/src/pages/[organism]/submission/edit/[accession]/[version].astro
resolves #3850
preview URL:
- Allow defining 'initial data' for the file upload component. it is displayed as a file.
- add the 'undo' functionality to the file upload component so you can revert to the initial data.
- bugfix: empty segments now show an upload control on the edit form of a sequence.
- Added automated tests for the FileUploadComponent to check that it correctly discards and undos.
- Manually checked that it's possible to discard sequence data in the edit form.
- Add integration test to check that discarded or modified sequence data is submitted correctly in the edit form.
https://github.com/user-attachments/assets/1fb2a998-38ed-4675-958a-1029fdea360f
=> feat(website): Visualize that a file upload component has data in it already if empty

website/src/components/SearchPage/SearchForm.tsx, website/src/components/SearchPage/fields/AutoCompleteField.spec.tsx, website/src/components/SearchPage/fields/AutoCompleteField.tsx, website/src/components/SearchPage/fields/AutoCompleteOptions.ts, website/src/components/SearchPage/fields/LineageField.spec.tsx, website/src/components/SearchPage/fields/LineageField.tsx, website/src/services/lapisApi.ts, website/src/types/lapis.ts
resolves #3506 
preview URL: https://lineage-search2.loculus.org
Lineage search now pulls all lineages and aliases from LAPIS. Previously, it only displayed lineages/aliases that were also present in the data already. LAPIS is still queried to get counts for lineages. a lineage and its aliases are listed seperately, but have the same (joint) count (i.e. if A1 and B are aliases and there are 2 seqs with A1 and 1 with B, both will be listed with count 3).
Also a bugfix was included where removing the value didn't reset the text field.
- New test to check that things are aggregated correctly.
- New test to check that externally resetting the value resets the text field as well.
- Minor test improvements
I created a bunch of sequences and checked that the aliases etc are all there, as well as …
=> feat(website): better lineage search

website/src/components/Edit/SequencesForm.spec.tsx, website/src/components/Edit/SequencesForm.tsx, website/src/components/Submission/FileUpload/fileProcessing.ts
resolves #3798 
preview URL: https://fix-submission.loculus.org
- The data given to the `submit-edit-data` endpoint now does not contain empty strings anymore for sequences that weren't submitted.
- I added some more tests to cover better that component. - Including a test that reproduced the issue.
- I did manual testing to check that the error doesn't show anymore.
https://github.com/user-attachments/assets/cc307f36-5cfb-4a5c-aaad-33ed700b193f
=> fix: Edit form does not incorrectly drop sequence data anymore.

website/src/components/Submission/FileUpload/fileProcessing.ts
I think this message would be confusing for unsegmented organisms
=> chore: Tweak no data error message

.github/workflows/integration-tests.yml, integration-tests/tests/pages/search.page.ts, integration-tests/tests/specs/features/search.spec.ts, integration-tests/tests/specs/features/search/active-filters.spec.ts, integration-tests/tests/specs/features/search/download.spec.ts, integration-tests/tests/specs/features/search/override-hidden-fields.ts, integration-tests/tests/specs/features/search/search.spec.ts, website/src/components/SearchPage/DownloadDialog/SequenceFilters.tsx, website/src/components/SearchPage/SearchFullUI.tsx, website/src/components/SearchPage/fields/DateField.spec.tsx, website/src/components/SearchPage/fields/DateField.tsx, website/src/components/SearchPage/fields/DateRangeField.spec.tsx, website/src/components/SearchPage/fields/DateRangeField.tsx, website/src/components/SearchPage/fields/NormalTextField.tsx, website/src/components/common/ActiveFilters.spec.tsx, website/src/components/common/ActiveFilters.tsx
resolves #3857 
preview URL: https://improve-filters.loculus.org
- "Is revocation" and "version status" were previously not shown if unset, but also not shown if set (because it's a hidden default). Now the fields are shown when unset, and clicking the "x" button will reset it to the hidden field value.
- for substring-search-enabled fields, the active filter showed "<fieldname>.regex: (i?)<value>" because the lapisSearchParameters were used. This is now not the case anymore.
- A small 'regression': previously, mutations were shown split into "nucleotide" and "aminoacid" etc, but now this isn't done anymore.
- date fields
- use Monday as the start of the week. 
- use `oneTap` -> no more clicking "OK" to confirm a date selection.
- date range field now also suppors 'x'-ing in the active …
=> fix(website): fix handling of certain edgecases for the active filter display

docs/src/content/docs/reference/helm-chart-config.mdx, kubernetes/loculus/templates/lapis-deployment.yaml, kubernetes/loculus/templates/loculus-backend.yaml, kubernetes/loculus/templates/loculus-website.yaml, kubernetes/loculus/templates/silo-deployment.yaml, kubernetes/loculus/values.schema.json, kubernetes/loculus/values.yaml
**BREAKING** - Changes the way images are configured. If your `values.yaml` specified `images.lapisSilo`, `images.lapis` or `customWebsiteImage`, you need to change those settings to use the new format. Otherwise, nothing needs to be done.
resolves #3726
preview URL (docs): https://docs-helm-refactor-image-conf.loculus.org/reference/helm-chart-config/
Images for `lapis`, `lapisSilo`, `website` and `backend` are now all configured under an `images` key:
```yaml
images:
lapisSilo:
repository: "ghcr.io/genspectrum/lapis-silo"
tag: "0.5.7"
pullPolicy: IfNotPresent
lapis:
repository: "ghcr.io/genspectrum/lapis"
tag: "0.4.1"
pullPolicy: IfNotPresent
website:
repository: "ghcr.io/loculus-project/website"
pullPolicy: Always
backend:
repository: "ghcr.io/loculus-project/backend"
pullPolicy: Always …
```
=> feat!(deployment): Standardize image config in Helm Chart

backend/docs/db/schema.sql, backend/src/main/kotlin/org/loculus/backend/service/files/FilesTable.kt, backend/src/main/resources/db/migration/V1.11__file_sharing.sql
_This PR is targeting the `file-sharing` feature branch and not the main branch._
resolves #3904
I named the field `requested_at` instead of `file_requested_at` as specified in the issue since it is in the files table, so it's clear that it is about the file.
=> feat(backend): add Files table

integration-tests/tests/specs/features/search/active-filters.spec.ts
Clicking "11" wasn't unique anymore (Apr 11 and May 11). With clicking "20" this shouldn't happen anymore.
=> fix(integration-tests): Fix a test that broke due to month changing

.github/pull_request_template.md
We now have Squash merges defaulting to include PR description, which yields something like https://github.com/loculus-project/loculus/commit/1b944de935fe6b5b3dd9cd9895528d1de0f689b2 
which is very saturated with comments from the PR template. Obviously we had these for a reason but they could be something we describe in Nuclino or docs instead. My preference would be to remove them, as here, but I expect some may disagree. Just an idea.
=> chore: remove comments from PR template

website/src/components/DataUseTerms/DataUseTermsSelector.spec.tsx, website/src/components/DataUseTerms/DataUseTermsSelector.tsx
Previously this text said "Restricted", we should standardise to "Restricted Use" as much as possible since data remains accessible. Technically it was right before anyway since its the "Terms of use" but this wouldn't be super clear.
🚀 Preview: https://restricted-use.loculus.org
=> feat(website): Rename restricted to restricted use in terms selector

.github/scripts/wait_for_pods_to_be_ready.py, .github/workflows/e2e-k3d.yml, .github/workflows/integration-tests.yml, backend/docs/db/schema.sql, backend/src/main/kotlin/org/loculus/backend/api/SubmissionTypes.kt, backend/src/main/kotlin/org/loculus/backend/controller/SubmissionController.kt, backend/src/main/kotlin/org/loculus/backend/model/SubmitModel.kt, backend/src/main/kotlin/org/loculus/backend/service/files/FilesDatabaseService.kt, backend/src/main/kotlin/org/loculus/backend/service/submission/CompressionService.kt, backend/src/main/kotlin/org/loculus/backend/service/submission/MetadataUploadAuxTable.kt, backend/src/main/kotlin/org/loculus/backend/service/submission/UploadDatabaseService.kt, backend/src/main/resources/db/migration/V1.11__file_sharing.sql, backend/src/test/kotlin/org/loculus/backend/controller/ExceptionHandlerTest.kt, backend/src/test/kotlin/org/loculus/backend/controller/files/FilesClient.kt, backend/src/test/kotlin/org/loculus/backend/controller/submission/GetOriginalMetadataEndpointTest.kt, backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmissionControllerClient.kt, backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmitEndpointFileSharingTest.kt, kubernetes/loculus/values.yaml
_This PR is targeting the `file-sharing` feature branch and not the main branch._
resolves #3906
To test this:
```bash
curl -X 'POST' \
'http://localhost:8079/dummy-organism/submit?groupId=1&dataUseTermsType=OPEN' \
-H 'accept: application/json' \
-H 'Authorization: Bearer <token>' \
-H 'Content-Type: multipart/form-data' \
-F 'metadataFile=@metadata.tsv;type=text/tab-separated-values' \
-F 'sequenceFile=@sequences.fasta' \
-F 'fileMapping={"seq1":{"dance_video":[{"fileId":"550e8400-e29b-41d4-a716-446655440000","name":"dance.mp4"}]}}'
```
🚀 Preview: https://fs-submit-api.loculus.org
=> feat(backend): accept file mapping in /submit and /revise endpoints

website/src/components/IndexPage/OrganismCard.astro, website/src/pages/index.astro
Adds a shadow to organism cards and redesigns them in various small ways. Uses Felix's original number formatting.
=> feat(website): some small improvements to organism card (rev 2)

website/src/layouts/BaseLayout.astro, website/src/pages/[organism]/submission/[groupId]/index.astro, website/src/pages/[organism]/submission/edit/[accession]/[version].astro, website/src/pages/seq/[accessionVersion]/getSequenceDetailsTableData.ts, website/src/services/backendApi.ts, website/src/services/backendClient.ts, website/src/services/backendClientFactory.ts, website/tests/backendAuth.spec.ts, website/tests/e2e.fixture.ts, website/tests/util/preprocessingPipeline.ts
Removes the zodios dependency from the `BackendClient`. Also makes the `BackendClient` usable in react by not having the `config.ts` import in it anymore.
🚀 Preview: https://backend-client.loculus.org
=> refactor(website): get rid of zodios in the backend client

website/src/components/Submission/FormOrUploadWrapper.tsx, website/src/components/Submission/SubmissionForm.spec.tsx
resolves #3972 
https://github.com/user-attachments/assets/667dc925-f6dd-438e-bbd2-5cc8c3dc9f19
=> fix(website): Make sequences-file check only happen when consensus sequences are enabled

backend/src/main/kotlin/org/loculus/backend/model/ReleasedDataModel.kt, backend/src/main/kotlin/org/loculus/backend/service/files/S3Service.kt, kubernetes/loculus/templates/_siloDatabaseConfig.tpl
partially resolves #3932 
- Generate metadata field settings in SILO
- compute string fields in the `get-release-data` endpoint. Each "file field" is added as a field to metadata, and it contains the links to the files as public S3 links, separated by a space"
🚀 Preview: https://fs-silo.loculus.org
=> Make file links available in SILO

kubernetes/loculus/values.yaml
The randomly occurring errors and warnings thrown by the dummy pipeline are annoying and not useful for developing the file sharing feature.
🚀 Preview: https://fs-disable-dummy-errors.loculus.org
=> chore(preprocessing): disable dummy errors for files

website/src/components/SearchPage/fields/TextField.spec.tsx, website/src/components/SearchPage/fields/TextField.tsx
resolves #3655.
N.B. This does not resolve the underlying issue https://github.com/loculus-project/loculus/issues/3878
It is unlikely we want linebreaks in singleline fields - it is quite easily to accidentally paste them and then they can cause confusion. This becomes very common due to https://github.com/loculus-project/loculus/issues/3878. Here we strip these characters from single line fields as a workaround. For now this only addresses singleline text fields.
I tested that this works
🚀 Preview: https://pastefix.loculus.org
=> feat(website): Strip `\r` and `\n` on paste into text field

website/src/components/SequenceDetailsPage/DataTableEntryValue.tsx
`whitespace-wrap` is not defined in https://tailwindcss.com/docs/white-space (I thought it might fix the copy issue but that is sadly not true)
🚀 Preview: https://fix-br.loculus.org
=> feat(website): remove `whitespace-wrap` as undefined in tailwind

deploy.py, kubernetes/loculus/templates/docs-preview.yaml, kubernetes/loculus/templates/ena-submission-deployment.yaml, kubernetes/loculus/templates/ingest-deployment.yaml, kubernetes/loculus/templates/keycloak-database-standin.yaml, kubernetes/loculus/templates/keycloak-deployment.yaml, kubernetes/loculus/templates/lapis-deployment.yaml, kubernetes/loculus/templates/loculus-backend.yaml, kubernetes/loculus/templates/loculus-preprocessing-deployment.yaml, kubernetes/loculus/templates/loculus-website.yaml, kubernetes/loculus/templates/silo-deployment.yaml
1. Removed the reloader.stakater.com/auto: "true" annotation from
all Kubernetes deployment files:
- loculus-backend.yaml
- loculus-website.yaml
- silo-deployment.yaml
- lapis-deployment.yaml
- keycloak-deployment.yaml
- ingest-deployment.yaml
- ena-submission-deployment.yaml
- docs-preview.yaml
- keycloak-database-standin.yaml
- loculus-preprocessing-deployment.yaml
2. Removed the reloader installation code from deploy.py:
- Removed install_reloader() function call from handle_cluster()
function
- Deleted the entire install_reloader() function
🚀 Preview: https://remove-reloader.loculus.org
=> chore(deployment): remove reloader

kubernetes/loculus/templates/docs-preview.yaml, kubernetes/loculus/templates/ena-submission-deployment.yaml, kubernetes/loculus/templates/ingest-deployment.yaml, kubernetes/loculus/templates/keycloak-database-standin.yaml, kubernetes/loculus/templates/keycloak-deployment.yaml, kubernetes/loculus/templates/lapis-deployment.yaml, kubernetes/loculus/templates/loculus-backend.yaml, kubernetes/loculus/templates/loculus-preprocessing-deployment.yaml, kubernetes/loculus/templates/loculus-website.yaml, kubernetes/loculus/templates/silo-deployment.yaml
resolves #3170
This adds timestamp annotations to all pods that basically describe the time on which helm was run to make a deployment. The effect of this should be that all pods have to restart when a new deployment is made, because this value will change. This should ensure that config-only updates are still made.
Testing:
- Tested that the product still works
- Tested that I can see the annotations in the pod
In terms of whether it fixes the issue - it should but IMO we can wait and see
🚀 Preview: https://timetamp-now.loculus.org
=> feat(deployment): timestamp pods on deployment to force restart of all pods on every deployment

backend/src/main/kotlin/org/loculus/backend/api/SubmissionTypes.kt, backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt, ingest/scripts/call_loculus.py, ingest/scripts/compare_hashes.py
resolves https://github.com/loculus-project/loculus/pull/4040#issuecomment-2823260215
If we now revoke 2 sequences that were created by the insdc_ingest_user we get another error. Original metadata is empty for revocations and without this the call_loculus script maps the revoked sequences to insdc_accession=NULL. We throw an error if multiple sequences map to the same insdc_accession - it also good to make sure this are mapped correctly so we never try to revise a revoked sequence. 
🚀 Preview: https://original-metadata-endpoin.loculus.org
=> fix(ingest): handle revocations correctly in call_loculus

backend/src/main/kotlin/org/loculus/backend/api/SubmissionTypes.kt, backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt, backend/src/test/kotlin/org/loculus/backend/controller/submission/GetOriginalMetadataEndpointTest.kt, ingest/README.md, ingest/scripts/call_loculus.py, ingest/scripts/compare_hashes.py
resolves #4036 
co-authored by @anna-parker
Fix backend to deal with `null` original metadata.
Now we get this for revoked sequences in `/get-original-metadata` (we add the `isRevocation` field to the output):
```
{"accession":"LOC_000M2HN","version":2,"submitter":"superuser","originalMetadata":null, "isRevocation": True}
```
Ingest also works: we remove the key sort and additionally handle revocations separately (as they do not contain the INSDC accession in the originalMetadata as it is empty) 
We now emit isRevocation in `/get-original-metadata` to allow ingest to handle revocations properly.
- Unit test added that reproduces the bug and no longer does so with the fix
- Manual in preview: Revoke a sequence, rerun ingest without problems
- Manual in preview: Revoke two sequences, rerun …
=> fix(backend,ingest): handle revoked sequences in /get-original-metadata, they have null metadata

backend/src/main/kotlin/org/loculus/backend/api/FileTypes.kt, backend/src/main/kotlin/org/loculus/backend/service/files/S3Service.kt, backend/src/test/kotlin/org/loculus/backend/controller/EndpointTestExtension.kt, backend/src/test/kotlin/org/loculus/backend/controller/files/FilesClient.kt, backend/src/test/kotlin/org/loculus/backend/controller/submission/ApproveProcessedDataEndpointTest.kt, backend/src/test/kotlin/org/loculus/backend/controller/submission/ExtractUnprocessedDataEndpointTest.kt, backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmissionConvenienceClient.kt
resolves #3991
- Add public policy to testcontainer bucket, so tagged files get made public.
- Add a new test, that checks whether approved files are actually public.
- Add a new test that checks whether the presigned URLs returned by 'extract-...-data' are accessible.
=> file sharing: more backend testing

website/src/components/Navigation/Navigation.astro, website/src/components/Navigation/SandwichMenu.tsx
Update the sandwich menu to display the site name dynamically
* Import `getWebsiteConfig` from `../config` in `SandwichMenu.tsx`.
* Replace the hardcoded "Loculus" with the dynamically fetched site name from `getWebsiteConfig().name` in the `SandwichMenu` component.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/loculus-project/loculus/pull/4074?shareId=11cb7a4a-78e9-47de-a5fe-b6380f3099c4).
🚀 Preview: https://theosanderson-fix-sandwic.loculus.org
=> fix(website): Make the sandwich menu display the site name not 'Loculus'

docs/src/content/docs/for-administrators/setup-with-kubernetes.md, kubernetes/loculus/templates/_siloDatabaseConfig.tpl, kubernetes/loculus/values.schema.json, kubernetes/loculus/values.yaml
These options will be deprecated when SILO is bumped to https://github.com/GenSpectrum/LAPIS-SILO/releases/tag/v0.6.0 so I thought we might as well remove the fluff while I remember.
Breaking!: ensure the `silo` section is removed from `values.yaml` to avoid helm lint errors
=> chore!(deployment): Remove `dateToSortBy`, `partitionBy` as now deprecated in SILO (and the wrapper `silo` value)

ingest/scripts/compare_hashes.py, kubernetes/loculus/values.yaml
resolves https://github.com/loculus-project/loculus/issues/2885
Send a notification on slack if re-ingested sequences do not include insdc-accessions that were previously ingested (and are not in a blocked, error, revoked state).
Test:
1. ingest from ebola zaire and set db to persistent
2. switch to ingest from ebola sudan
3. ensure receive notification:
admittedly its not very easy to search this message - but I assume we will generally not receive a notification of 3k sequences that are missing and I would need to give ingest the slack token to upload files
4. revoke some sequences (e.g. ebola zaire: OK572988.1), re-ingest ensure not notified about these sequences 
=> I am now reverting the persistent DB changes to stop us getting notifications every 30min on slack.
🚀 Preview: …
=> feat(ingest): notify on potential suppression

preprocessing/nextclade/src/loculus_preprocessing/backend.py, preprocessing/nextclade/src/loculus_preprocessing/prepro.py, preprocessing/nextclade/src/loculus_preprocessing/processing_functions.py
resolves #
🚀 Preview: https://trim-ns-anya.loculus.org
=> feat: strip Ns right after reading from file to ensure all pipelines (incl. those without nextclade) strip Ns

docs/package-lock.json, docs/package.json
Reverts loculus-project/loculus#4013 which breaks CI for docs: https://github.com/loculus-project/loculus/actions/runs/14888052688/job/41813084241
=> Revert "chore(deps): bump @astrojs/starlight-tailwind from 3.0.1 to 4.0.1 in /docs"

kubernetes/loculus/values.schema.json
The Helm chart supports the specification of a docker tag for the preprocessing pipeline:
https://github.com/loculus-project/loculus/blob/de7cb98029c992ae7d38874577b3d2047b68ddb9/kubernetes/loculus/templates/loculus-preprocessing-deployment.yaml#L11
However, the field is missing in the schema. This PR adds it.
- ~[ ] The implemented feature is covered by appropriate, automated tests.~ No additional tests needed.
- ~[ ] Any manual testing that has been done is documented (i.e. what exactly was tested?)~ No manual testing needed.
🚀 Preview: https://fix-schema-prepro-tag.loculus.org
=> fix(kubernetes): add preprocessing dockerTag to schema

docs/src/content/docs/for-administrators/setup-with-k3d-and-nginx.mdx
The schema doesn't allow setting `auth.smtp` and `auth.identityProviders` to `null`.
=> docs: fix config example in tutorial

ingest/Snakefile
When investigating why Pathoplexus got some Genbank sequences only a week after their release,
I noticed some logs about the content of NCBI datasets downloads could be helpful for debugging in the future.
None of the changes cause any change in behaviour, it's just a few extra log lines.
🚀 Preview: https://ingest-ncbi-logs.loculus.org
=> chore(ingest): log basic details about NCBI dataset files

website/src/components/SearchPage/DownloadDialog/FieldSelector/FieldSelectorModal.spec.tsx, website/src/components/SearchPage/DownloadDialog/FieldSelector/FieldSelectorModal.tsx
resolves #4116 
The select all/none buttons were not working in the download panel. This is fixed now.
- Confirmed in preview that the buttons are working.
🚀 Preview: https://fix-select-all-none.loculus.org
=> fix(website): fix select all/none in FieldSelectorModal

kubernetes/loculus/values.schema.json, website/src/components/SearchPage/DownloadDialog/LinkOutMenu.spec.tsx, website/src/components/SearchPage/DownloadDialog/LinkOutMenu.tsx, website/src/components/SearchPage/SearchFullUI.tsx
resolves #4114
If DUTs are disabled when clicking on a LinkOut / Tool on the search page, no modal to select the data use terms will be shown. Instead, the tool will be opened directly.
To test manually, use a config with
```
dataUseTerms:
enabled: false
```
If data use terms are disabled:
https://github.com/user-attachments/assets/129bd696-8e52-4125-8db2-480013ac6a0c
- See screen recording
🚀 Preview: https://link-out-without-dut.loculus.org
=> feat(website): make LinkOuts usable without data use terms

backend/src/main/kotlin/org/loculus/backend/auth/AuthenticatedUser.kt, backend/src/main/kotlin/org/loculus/backend/controller/FilesController.kt, backend/src/main/kotlin/org/loculus/backend/service/files/FilesPreconditionValidator.kt, backend/src/test/kotlin/org/loculus/backend/controller/files/RequestUploadEndpointTest.kt
resolves #4062
Requesting file uploads now works for the preprocessing pipeline.
A test was added as well.
No manual testing was done (but changes are pretty trivial).
=> feat(backend): allow prepro to upload files for groups

backend/src/main/kotlin/org/loculus/backend/service/files/FilesPreconditionValidator.kt
Remove space to fix backend code style
=> style(backend): fix code style

website/src/components/Navigation/SandwichMenu.tsx, website/src/components/SandwichIcon.tsx
resolves #2729
- clean up ARIA label usage in the hamburger menu icon
- add explicit aria labels to menu toggle buttons
=> fix(website): fix website aria violation

website/src/components/SequenceDetailsPage/SequenceEntryHistoryMenu.tsx
resolves #4115
- add margin to the version selector so it's not flush against adjacent controls
🚀 Preview: https://codex-adjust-spacing-betw.loculus.org
=> fix(website): Fix spacing around version selector

website/src/components/common/ErrorBox.tsx, website/src/styles/base.scss
Resolves https://github.com/loculus-project/loculus/issues/3025
- simplify ErrorBox by removing runtime link styling
- apply bold and underline styling to links in alerts via global CSS
- 
=> refactor(website): Refactor ErrorBox anchor styling

website/AGENTS.md, website/src/hooks/useGroupOperations.ts
Fix minor bug in group edit error message (copy/paste bug identified by codex)
- fix error message shown when group editing fails
=> fix(website): Fix group edit error message

.gitignore, website/src/components/ReviewPage/ReviewCard.tsx
resolves https://github.com/loculus-project/loculus/issues/1400
- truncate long metadata values in ReviewCard
- show tooltip when text is truncated
=> feat(website): truncate review cards

preprocessing/nextclade/src/loculus_preprocessing/processing_functions.py
- correct return annotation for `format_authors`
=> fix(ingest): fix `format_authors` return type

ingest/scripts/call_loculus.py
- rename BatchIterator field `current_fasta_header` to `fasta_record_header` consistent with usage below
=> fix(ingest): Fix BatchIterator variable `current_fasta_header`

website/Dockerfile
- use `npm ci` in Dockerfile for reproducible dependency installs
=> chore(website): Use npm ci in website Dockerfile

preprocessing/dummy/main.py
The dummy pipeline currently doesn't allow more than 100 sequences to be fetched at the same time. This PR is introducing a `batchSize` option.
=> feat(preprocessing): allow dummy pipeline to take larger batches

kubernetes/loculus/values.yaml
Thanks to @theosanderson's https://github.com/pathoplexus/pathoplexus/pull/445, this shouldn't be breaking for Pathoplexus.
* **lapis-docs:** correct invalid gene in example ([#1165](https://github.com/GenSpectrum/LAPIS/issues/1165)) ([42b79a2](https://github.com/GenSpectrum/LAPIS/commit/42b79a2548e0a68027e871d2bde03d60e7f790f0))
* **lapis-docs:** fix condition when to show the "variant queries are not available" banner ([#1186](https://github.com/GenSpectrum/LAPIS/issues/1186)) ([6fe60fe](https://github.com/GenSpectrum/LAPIS/commit/6fe60fe9f7bcb943d5d5e35cb8448ddebe93e1f5))
* **lapis:** add missing `dataFormat` to amino acid mutation GET endpoint in Swagger UI ([#1160](https://github.com/GenSpectrum/LAPIS/issues/1160)) ([5c4dbe2](https://github.com/GenSpectrum/LAPIS/commit/5c4dbe2f5808252 …
=> chore(kubernetes): update LAPIS to 0.4.5 and SILO to 0.6.0

website/src/components/User/GroupPage.tsx
Resolves https://github.com/loculus-project/loculus/issues/698
- warn users when leaving a group if they are the last member
I tested this and it worked as expected (tested both for groups with >1 members and 1 member)
🚀 Preview: https://codex-add-warning-when-le.loculus.org
=> feat(website): Add warning when last group member leaves

website/src/components/SearchPage/fields/AutoCompleteField.spec.tsx, website/src/components/SearchPage/fields/AutoCompleteField.tsx
The auto-completion of the search is crashing my browser tab if there are too many options. As a solution, this PR proposes to only show a limited number of options. I observed a problem in a field with ~8000 values while it worked well for ~700 values, so I chose a cutoff of 1000.
- Up to 1000 options work well for me (if we observe that it is too much for some devices, we can further adjust)
=> feat(website): limit max number of displayed autocomplete options

website/src/utils/urlForKeycloakAccountPage.spec.ts, website/src/utils/urlForKeycloakAccountPage.ts
resolves https://github.com/loculus-project/loculus/issues/3273 (which codex independently identified). Now we can link to Keycloak account info page even when we're hosting it on HTTP not HTTPS.
- keep protocol from `endSessionUrl` when building Keycloak account link
- add unit tests for http and https issuers
=> fix(website): Fix Keycloak account URL protocol handling

.gitignore, website/src/utils/templateProcessor.spec.ts, website/src/utils/templateProcessor.ts
In the code that constructs URLs for linkOuts I forgot to consider the case that a placeholder might appear twice - this fixes that
- ensure all occurrences of each placeholder get replaced in templates using `replaceAll`
- test multiple placeholders of the same name
=> fix(website): Fix processTemplate multiple placeholder replacement

website/src/components/Submission/FileUpload/fileProcessing.spec.ts, website/src/components/Submission/FileUpload/fileProcessing.ts
resolves #4151 
- show better error when uploading metadata files with unsupported extensions
- test unsupported metadata extension
🚀 Preview: https://codex-fix-empty-error-mes.loculus.org
=> fix(website): Fix error message for invalid metadata file extension upload

.github/workflows/preprocessing-tests.yaml, kubernetes/loculus/values.yaml, preprocessing/nextclade/.mypy.ini, preprocessing/nextclade/README.md, preprocessing/nextclade/src/loculus_preprocessing/backend.py, preprocessing/nextclade/src/loculus_preprocessing/datatypes.py, preprocessing/nextclade/src/loculus_preprocessing/prepro.py, preprocessing/nextclade/src/loculus_preprocessing/processing_functions.py, preprocessing/nextclade/src/loculus_preprocessing/sequence_checks.py, preprocessing/nextclade/tests/factory_methods.py, preprocessing/nextclade/tests/test_processing_functions.py
partially resolves https://github.com/loculus-project/loculus/issues/4189
@corneliusroemer showed me how to enable type checking for python in VSCode - this PR cleans up prepro. It also adds a mypy type check to the cli to ensure that we do not regress again.
All changes are type related, main changes:
- ArgValue is now correctly typed as `ArgValue = list[str] | str | bool | None` and the type is checked before being used in functions
- `FunctionArgs` is now always a dictionary and never None (it was always used as a dict which caused type errors)
- In `ProcessingAnnotation` `unprocessedFields` and `processedFields` are now `list[AnnotationSource]` instead of tuples (they were typically used as lists)
- sign in as super user check that warnings and errors are being displayed correctly
🚀 …
=> Reformat prepro

kubernetes/loculus/templates/_common-metadata.tpl, kubernetes/loculus/values.schema.json, kubernetes/loculus/values.yaml, website/src/components/SearchPage/DownloadDialog/LinkOutMenu.spec.tsx, website/src/components/SearchPage/DownloadDialog/LinkOutMenu.tsx, website/src/components/SearchPage/SearchFullUI.tsx, website/src/types/config.ts
Resolves #4215 for now. It's not perfect but we can come back to the whole linkOut modal when we have sequence numbers for the number of open and restricted sequences.
🚀 Preview: https://codex-add-warning-for-exc.loculus.org
=> feat(website): warn when link out exceeds recommended sequences

website/src/utils/createDownloadAPIRoute.ts
resolves #4223 
LAPIS resonds with an `OK` response also for empty data, and that caused issues. Now we're checking if at least one data row is returned, and otherwise an error is raised (making the Promise rejected).
Note on redirects: for URLs without a version, a redirect is returned, so that is just passed through as OK - we "kick the can down to road"
I tested that I can DL sequence data on seqs where I couldn't (reliably) before. I also tested a link without a version part and that worked too. This is the URL I used during my tests: https://main.loculus.org/seq/LOC_00004U7.1 (but with localhost)
- ~~All necessary documentation has been adapted.~~ (n/A)
- ~~The implemented feature is covered by appropriate, automated tests.~~ (postponed: #4225)
🚀 Preview: …
=> fix(website): Check for empty LAPIS responses and raise error

integration-tests/tests/specs/features/sequence-tsv-download.dependent.spec.ts
Resolves https://github.com/loculus-project/loculus/issues/4225
- add a Playwright integration test that verifies the 'Download metadata TSV' button for individual sequences
=> test(integration): add sequence TSV download test

kubernetes/loculus/templates/_siloDatabaseConfig.tpl, kubernetes/loculus/values.yaml
We recently added advanced queries in LAPIS. They are documented here: https://lapis.cov-spectrum.org/open/v2/docs/concepts/advanced-query
The config field `lapisAllowsRegexSearch` is not necessary anymore. All string fields can be queried with `<fieldName>.regex` now.
I left the `enableSubstringSearch` config field in Loculus though, because it's probably good to leave that for the UI, isn't it?
Changelog: 
* **lapis:** advanced queries: make `.regex` case-insensitive ([#1198](https://github.com/GenSpectrum/LAPIS/issues/1198)) ([fd85fa5](https://github.com/GenSpectrum/LAPIS/commit/fd85fa5fbe8cb765c6a994214d10fb587cd36d10))
* **lapis:** lapisAllowsRegexSearch on string metadata fields in the database config is not necessary anymore, regex search is always enabled for all string fields.
* …
=> feat(kubernetes): update LAPIS to 0.5.1 and enable advanced queries

website/src/components/SearchPage/SearchFullUI.tsx
- ensure Sequence Preview modal resets when selecting a new sequence
Resolves https://github.com/loculus-project/loculus/issues/4236
I couldn't see the issue in the preview
🚀 Preview: https://codex-fix-sequence-detail.loculus.org
=> fix(website): reset sequence preview state when switching

backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmissionConvenienceClient.kt
Fixes lint:
```
> Task :compileTestKotlin
w: file:///home/runner/work/loculus/loculus/backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmissionConvenienceClient.kt:487:9 'when' is exhaustive so 'else' is redundant here.
```
=> chore(backend): fix Kotlin lint about redundant else clause

kubernetes/loculus/templates/lapis-deployment.yaml, kubernetes/loculus/templates/loculus-backend.yaml, kubernetes/loculus/values_preview_server.yaml
When the cluster is CPU throttling the backend/lapis startup, it can take quite some time to become live - longer than 90 seconds, causing it to get killed. Java has ridiculously long startup CPU requirements unfortunately.
Adding a startup probe to give them more time (3min)
🚀 Preview: https://backend-startup.loculus.org
=> fix(k8s): give backend and LAPIS 3min to become live with startup probe

website/src/components/SearchPage/SearchForm.tsx, website/src/components/SearchPage/fields/AutoCompleteField.tsx, website/src/components/SearchPage/fields/DateField.tsx, website/src/components/SearchPage/fields/NormalTextField.tsx
resolves #4273 at least for now - we should do some thinking about whether we use `sentenceCase` for these sorts of purposes or not (we currently inconsistently sometimes do and sometimes don't - but it would be great to merge this as the current state is bad!)
🚀 Preview: https://namefallback.loculus.org
=> fix(website): fallback to `name` if `displayName` not available

.github/workflows/backend-tests.yml
Backend tests are no longer flaky, so simplify setup
resolves #
=> chore(ci): remove retry from backend tests, no longer needed

backend/src/main/kotlin/org/loculus/backend/auth/AuthenticatedUser.kt, backend/src/test/kotlin/org/loculus/backend/controller/files/FilesClient.kt, backend/src/test/kotlin/org/loculus/backend/controller/files/GetFilesEndpointTest.kt
I found an issue, the authenticated access to unpublished files didn't work. I wrote a test for that: `GIVEN an unpublished file WHEN requesting with auth THEN the file is returned`, and implemented the fix.
This came up while working on https://github.com/loculus-project/loculus/issues/3968 and is relevant for implementing that.
=> fix(backend): authenticated file access to unpublished files

kubernetes/loculus/values.yaml
* **lapis:** advanced queries: tell which metadata fields exist when finding an unknown one ([#1209](https://github.com/GenSpectrum/LAPIS/issues/1209)) ([1011154](https://github.com/GenSpectrum/LAPIS/commit/1011154db50b541b166f88d996f966fdb45c8293))
* **lapis:** allow advanced queries to be used with simple variant and metadata queries ([#1212](https://github.com/GenSpectrum/LAPIS/issues/1212)) ([8a1409e](https://github.com/GenSpectrum/LAPIS/commit/8a1409e736abbdcf3d9b2e3e136ca04789717ad2))
=> chore(kubernetes): update LAPIS to 0.5.2

backend/src/main/kotlin/org/loculus/backend/service/datauseterms/DataUseTermsPreconditionValidator.kt, backend/src/test/kotlin/org/loculus/backend/controller/datauseterms/DataUseTermsControllerTest.kt
resolves #4272
This (codex) revealed various test cases which didn't make a lot of sense!
When you first do it you get this:
(that was already the case)
now when you try again you get this (minus the typo which I will have fixed by the time you read this)
=> fix(backend): prevent open sequence being set to Open

backend/src/main/kotlin/org/loculus/backend/model/SubmitModel.kt, backend/src/main/kotlin/org/loculus/backend/utils/FastaReader.kt, backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmitEndpointTest.kt, docs/src/content/docs/reference/fasta-format.md
resolves #3800 
The FASTA reader was modified to raise an error if a segment doesn't have data.
I've uploaded CCHF example file with one segment data but removed, and I got an error (as expected).
🚀 Preview: https://fix-empty-segment-err.loculus.org
=> fix(backend): reject empty FASTA segments

backend/src/main/kotlin/org/loculus/backend/model/SubmitModel.kt, backend/src/test/kotlin/org/loculus/backend/controller/submission/ReviseEndpointTest.kt
There was a bug that prevented files from being attached to revisions. We need to associate revision entries with the existing sequence entries and their groups before checking the group ownership of files. I added a test to verify that attaching a file mapping now works.
🚀 Preview: https://fix-files-revisions.loculus.org
=> fix(backend): file upload for revisions

backend/build.gradle, backend/gradle.properties, backend/src/main/kotlin/org/loculus/backend/service/files/S3Service.kt
Unfortunately, the MinIO S3 client library doesn't support multipart uploads (#4378). Therefore, this PR switches to using AWS' SDK.
- ~[ ] The implemented feature is covered by appropriate, automated tests.~ – It's a pure refactoring, the existing feature is well covered by tests.
=> refactor(backend): use AWS SDK instead of MinIO client

integration-tests/tests/specs/features/search/download.dependent.spec.ts, kubernetes/loculus/templates/_common-metadata.tpl
These feel like things we should have available by default in downloads - `submissionId` in particular because submitters will need it to link accessions to submissions, e.g. for revision.
In due course we should allow customising this stuff by deployers, but that's a bigger job
🚀 Preview: https://add-default-download.loculus.org
=> feat(deployment): Add `submissionId`, `groupName` to default metadata downloads

backend/build.gradle
In #4393, dependabot was not able to update a JUnit dependency. The issue is that we import JUnit dependencies through different paths: `org.junit.platform:junit-platform-launcher` is imported directly, while other packages are imported indirectly through other dependencies, and in case of #4393, this is causing conflicting packages to be imported. To solve this, we can use a BOM (Bill of Material) package to manage the versions.
For more information about the problem and the BOM-packages, [here](https://reflectoring.io/maven-bom/) is a good article.
=> chore(backend): use BOM to manage JUnit dependency

ena-submission/scripts/get_ena_submission_list.py, ena-submission/src/ena_deposition/submission_db_helper.py
- Fix bug in ena-submission-list
- Refactor to make logic easier to follow
- Improve efficiency, by making only one db call per organism to get highest submitted version per accession - instead of one call per entry
- Tested on staging: no more errors, Slack messages are correct and so is JSON
=> fix(deposition): improve typing and fix bug if external metadata present

.github/workflows/integration-tests.yml, deploy.py, integration-tests/playwright.config.ts, integration-tests/tests/specs/features/search/download.dependent.spec.ts, kubernetes/loculus/templates/_common-metadata.tpl, kubernetes/loculus/templates/_urls.tpl, kubernetes/loculus/templates/ena-submission-config.yaml, kubernetes/loculus/templates/ingest-config.yaml, kubernetes/loculus/templates/loculus-preprocessing-deployment.yaml, kubernetes/loculus/templates/loculus-website-config.yaml, kubernetes/loculus/values.schema.json, kubernetes/loculus/values.yaml
based on #4448, #4450, #4453
In #4344, #4298 we ran into issues with the integration tests running in CI. After some research we found that the issues were caused by the backend giving pre-signed URLs to the prepro pipeline, that only work from outside the cluster.
This PR fixes that, by making it possible to use the local IP of the host instead of the literal `localhost`. The IP will work inside and outside of the cluster.
- Introduces new `localHost` value in Helm Chart to override `localhost` literal with something else.
- Introduces `./deploy.py helm --use-localhost-ip` flag to use the IP instead of the `localhost` literal.
- Introduces `./deploy.py cluster --bind-all` flag to bind to all interfaces to reach bound ports via the IP.
- Uses the new flags in integration tests CI.
- ~~Any …
=> feat(deployment): Make it possible to use local IP instead of `localhost`

integration-tests/tests/pages/review.page.ts, integration-tests/tests/specs/features/file-sharing.spec.ts, kubernetes/loculus/templates/_common-metadata.tpl, website/src/components/ReviewPage/FilesDialog.tsx, website/src/components/ReviewPage/ReviewCard.tsx, website/src/components/ReviewPage/ReviewPage.spec.tsx, website/src/components/ReviewPage/ReviewPage.tsx, website/src/components/Submission/DataUploadForm.tsx, website/src/components/Submission/FileUpload/FolderUploadComponent.tsx, website/src/config.ts, website/src/pages/[organism]/submission/[groupId]/review.astro, website/src/pages/seq/[accessionVersion]/[fileCategory]/[fileName].ts, website/src/types/backend.ts, website/src/types/config.ts, website/vitest.setup.ts
resolves #3968 
Adds a button similar to the 'view sequences' button to view files that opens a dialog with the file links.
The /seq/...filename.txt route is refactored to directly return a redirect to S3, instead of a redirect to the backend (which could then redirect to S3), so one network hop is saved.
I've made a submission with files, waited for them to process, and then downloaded them through the dialog. works! See also the video below.
https://github.com/user-attachments/assets/4af8f542-823f-4e4f-8d2f-0be38b5d3480
🚀 Preview: https://review-files.loculus.org
=> feat(website): Add dialog to view processed files in 'review' window (before approving)

backend/src/main/kotlin/org/loculus/backend/service/submission/FileMappingPreconditionValidator.kt, backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt, backend/src/test/kotlin/org/loculus/backend/controller/submission/ReviseEndpointTest.kt, backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmitEditedSequenceEntryVersionEndpointTest.kt, backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmitEndpointFileSharingTest.kt, backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmitProcessedDataEndpointTest.kt
The error message for category validation for submission vs output categories is now different, which makes finding and fixing the error easier.
=> feat(backend): Improve error message

.github/workflows/e2e-k3d.yml, .github/workflows/helm-schema-lint.yaml, .github/workflows/integration-tests.yml, .github/workflows/website-playwright-dev-test.yml
The azure/setup-helm action falls back to an old default version (3.13.3) when fetching the latest fails.
Pinning version to a concrete recent version (3.18.3) avoids this fallback and causes easier to debug failures.
It's recommended in the action's README:
> If something goes wrong with fetching the latest version the action will use the hardcoded default stable version (currently v3.13.3). If you rely on a certain version higher than the default, you should explicitly use that version instead of latest.
The undesired fallback behavior happened here: https://github.com/loculus-project/loculus/actions/runs/15763535878/job/44435288826#step:6:10
=> fix(ci): pin helm version in setup-helm action to avoid old fallback

integration-tests/tests/specs/features/search/active-filters.dependent.spec.ts, website/src/components/SearchPage/fields/DateField.spec.tsx, website/src/components/SearchPage/fields/DateField.tsx, website/src/components/SearchPage/fields/DateRangeField.spec.tsx
Switch date picker date format from `dd/mm/yyyy` to `yyyy-mm-dd`.
- Type dates in both date range and timestamp fields and verify they behave as expected
🚀 Preview: https://year-first-2.loculus.org
=> feat(website): switch date format in date picker fields from dd/MM/yyyy to yyyy-MM-dd

website/src/components/Submission/FileUpload/ColumnMappingModal.tsx
Resolves #4501
Using timeout caused tests to occasionally crash locally. The original implementation was a hack to avoid tooltip from reopening after modal is closed (it returns because focus returns to button with tooltip).
One shouldn't use timeout without cleaning up the timeout in case of component unmount.
As few people will use keyboard navigation, we can just not trigger the tooltip on focus.
resolves #
=> fix(website): replace brittle timeout hack by changing tooltip triggers

.github/workflows/keycloakify-image.yml, .github/workflows/website-image.yml
I forgot to update the keycloakify image action in this PR #4443 causing keycloakify image builds to fail, see https://github.com/loculus-project/loculus/actions/runs/15854243044/job/44695382181#step:10:11
Testing: Keycloakify builds again
=> fix(ci): parse nvmrc with comments correctly for keycloakify image as well

integration-tests/tests/pages/submission.page.ts
Lack of await caused weird failures in "afterHooks" which made no sense to me until @anna-parker and I stumbled over this together looking through the Playwright UI and tests.
@fhennig remember to sprinkle `await` liberally - linters will readily tell when the `await` is not needed. They often don't tell you when `await`s are missing.
=> fix(integration-tests): add missing await that otherwise causes spurious test failures

preprocessing/nextclade/src/loculus_preprocessing/processing_functions.py
We should trigger a full reprocessing in case there were untrimmed `n`s
=> fix!(prepro): trim lower case Ns from unaligned, not just upper case

.gitignore, integration-tests/tests/fixtures/auth.fixture.ts, integration-tests/tests/fixtures/sequence.fixture.ts, integration-tests/tests/pages/review.page.ts, integration-tests/tests/readonly.setup.ts, integration-tests/tests/specs/features/submission-flow.spec.ts, website/src/components/Edit/InputField.tsx, website/src/components/SearchPage/SearchForm.tsx, website/src/components/SearchPage/fields/MutationField.tsx
resolves #4513, resolves #4369, resolves #4498, resolves #4358
Using `PLAYWRIGHT_TEST_BASE_URL="https://test-tweaks2.loculus.org" npx playwright test --ui --workers 10` I debugged flaky tests locally, figuring out root causes of timeouts/lack of progress.
Main reasons for failure:
- Lack of marking React controlled inputs as disabled until React has hydrated the server side rendered HTML. This has been a common flakiness theme for a while. The solution is to use the `const isClient = useClientFlag()` hook and set `disabled={!isClient}`. The phenotype of this failure mode is playwright apparently getting stuck at a step after it clicked something. It did the click but React never listened, and hence didn't open a combobox option or modal or...
- Too short timeouts, sometimes things like …
=> fix(website): deflake tests by disabling buttons until react has hydrated and increasing timeout

integration-tests/tests/fixtures/group.fixture.ts, integration-tests/tests/fixtures/user.fixture.ts, integration-tests/tests/pages/auth.page.ts, integration-tests/tests/pages/group.page.ts, integration-tests/tests/pages/submission.page.ts, integration-tests/tests/readonly.setup.ts
When doing Playwright debugging locally, it was annoying that for dependent tests, there would be new sequence creation every time one runs a test. This took 15+ seconds.
This PR now checks for existence of a sequence and skips submission of sequence if there already is a sequence in a group. This takes only ~2 seconds allowing faster iteration on dependent tests.
=> feat(int-tests): speed up read-only dependent tests by using pre-existing sequences

website/src/components/DisabledUntilHydrated.tsx
- Ensure it gets only one child
- Throw if it would override a disabled (ideally this would be done by TS but it seems complicated)
Example lint we get now:
And if disabled is set on child:
=> chore(website): small improvements to DisabledUntilHydrated element

.github/workflows/ena-submission-unit-tests.yaml, .github/workflows/ena-submission-workflow-tests.yml
=> chore(ci): remove powershell from init-shells as it's unused and triggers warning

website/src/components/SearchPage/fields/AutoCompleteOptions.ts, website/src/components/SearchPage/fields/LineageField.spec.tsx
resolves #4534 
Removes the explicit adding of aliases to the options list. Component tests are adapted accordingly.
**manual testing** - Created 100 Test organism entries, checked the dropdown, only the canonical names are shown.
lineage file content:
```
A:
aliases: []
parents: []
A.1:
aliases: []
parents:
- A
A.1.1:
aliases:
- B
parents:
- A.1
A.2:
aliases: []
parents:
- A
```
- ~~All necessary documentation has been adapted.~~ (I can't think of anything to document here)
🚀 Preview: https://dont-show-lineage-aliases.loculus.org
=> fix(website): remove lineage aliases from drop down

backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt, backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmitProcessedDataEndpointTest.kt
resolves #4055
When submitting processed data of an already approved entry, associated files will be made public immediately. 
- The automated tests cover the fix well.
=> fix(backend): publish approved files after pipeline update

ingest/scripts/call_loculus.py
This looks unintended? (Found by codex)
=> fix(ingest): fix bare string in ingest

.github/workflows/ena-submission-workflow-tests.yml, ena-submission/flyway/Dockerfile
The action was set to only run when the test file itself changed - we want it to run in general when there are relevant changes to the ena package as a whole.
=> chore(ci): run ena integration tests on all ena-submission file changes

ena-submission/README.md, ena-submission/environment.yml, ena-submission/src/ena_deposition/ena_submission_helper.py
I used find/replace to replace the remaining CreationResult kwarg typos (there were 2 left)
Also, allow using `.env` file to keep username/password for deposition (more convenient than env variables that need to be explicitly set).
=> fix(deposition): fix all `CreationResult(results=` typos, allow setting user/pass in .env file

backend/src/main/kotlin/org/loculus/backend/model/ReleasedDataModel.kt, backend/src/test/kotlin/org/loculus/backend/controller/submission/GetReleasedDataFileSharingEndpointTest.kt
resolves #4382
The PR makes `/get-released-data` return a stable metadata column set, containing all configured file columns. If an entry doesn't have files or is a revocation entry, it will set the value to `null`.
- Covered by automated tests
=> fix(backend): include all file categories in get-released-data

backend/docs/file_sharing.md
resolves #4587 
Add various explanation, add links to user docs.
See: https://github.com/loculus-project/loculus/blob/fs-dev-docs/backend/docs/file_sharing.md
=> docs(backend): expand file sharing developer docs

.github/workflows/format-website-on-dispatch.yml
See https://github.com/loculus-project/loculus/pull/4577#discussion_r2180240161
Looks like 4.4 itself isn't a tag, it's either 4.4.0 or 4 that's accepted. We use 4 everywhere so for consistency let's go to that.
=> fix(ci): use actual existing tag v4 for setup-node, not non-existing v4.4

kubernetes/loculus/values.yaml
Remove "dummy organism without consensus sequences" from defaultOrganism
🚀 Preview: https://consensus.loculus.org
=> chore(deployment): Remove "dummy organism without consensus sequences" from `defaultOrganism`

kubernetes/loculus/templates/_common-metadata.tpl, kubernetes/loculus/templates/_enabledOrganisms.tpl, kubernetes/loculus/templates/_urls.tpl, kubernetes/loculus/templates/ingest-config.yaml, kubernetes/loculus/templates/ingest-deployment.yaml, kubernetes/loculus/templates/lapis-deployment.yaml, kubernetes/loculus/templates/lapis-ingress.yaml, kubernetes/loculus/templates/lapis-service.yaml, kubernetes/loculus/templates/lapis-silo-database-config.yaml, kubernetes/loculus/templates/loculus-preprocessing-config.yaml, kubernetes/loculus/templates/loculus-preprocessing-deployment.yaml, kubernetes/loculus/templates/silo-deployment.yaml, kubernetes/loculus/templates/silo-service.yaml, kubernetes/loculus/values.schema.json, kubernetes/loculus/values.yaml
- I've updated the schema
- Tested that `not-aligned-organism` doesn't appear in produced config files anymore
🚀 Preview: https://enable-false.loculus.org
=> feat(k8s): allow disabling organism by setting "enabled: false"

preprocessing/nextclade/environment.yml, preprocessing/nextclade/src/loculus_preprocessing/backend.py, preprocessing/nextclade/src/loculus_preprocessing/datatypes.py, preprocessing/nextclade/src/loculus_preprocessing/prepro.py, preprocessing/nextclade/src/loculus_preprocessing/processing_functions.py, preprocessing/nextclade/tests/factory_methods.py, preprocessing/nextclade/tests/test_processing_functions.py
resolves https://github.com/loculus-project/loculus/issues/4613
From looking at https://github.com/loculus-project/loculus/pull/2268 we pass the `submittedAt` timestamp to preprocessing - this should be used instead of `now` for the upper bound as `now` will change each time the sequence is reprocessed. 
🚀 Preview: https://fix-release-date-range.loculus.org
=> feat(prepro): use submittedAt date as upperBound in parse_date_into_range instead of processing time

ena-submission/src/ena_deposition/notifications.py
resolves #
Since the refactor in https://github.com/loculus-project/loculus/pull/4577 the file is now being uploaded in bytes - this reverts the changes in the refactor that affected this function
-> Im not sure how best to test these slack notifications but would be good to in future think of a way to test them as they often break 
tested on preview, submitted sequences and then ran cronjob, was successful:
🚀 Preview: https://fix-notifications.loculus.org
=> fix(deposition): make submission list upload to Slack work again

backend/src/main/kotlin/org/loculus/backend/controller/SubmissionControllerDescriptions.kt, backend/src/main/kotlin/org/loculus/backend/utils/ParseFastaHeader.kt
Apparently some controller descriptions were forgotten to be adapted in #3711. This doesn't intend to change anything, but help with preparations for #4296.
resolves #
=> refactor(backend): use constant to refer to submission id for better reference

backend/src/main/kotlin/org/loculus/backend/config/Config.kt, backend/src/main/kotlin/org/loculus/backend/service/submission/CompressionService.kt, backend/src/main/kotlin/org/loculus/backend/service/submission/EmptyProcessedDataProvider.kt, backend/src/main/kotlin/org/loculus/backend/service/submission/ProcessedSequenceEntryValidator.kt, backend/src/main/kotlin/org/loculus/backend/utils/ParseFastaHeader.kt, backend/src/test/kotlin/org/loculus/backend/config/BackendSpringConfigTest.kt, backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmissionConvenienceClient.kt, backend/src/test/kotlin/org/loculus/backend/service/submission/EmptyProcessedDataProviderTest.kt, backend/src/test/resources/backend_config.json, backend/src/test/resources/backend_config_data_use_terms_disabled.json, backend/src/test/resources/backend_config_s3.json, backend/src/test/resources/backend_config_single_segment.json, docs/src/content/docs/for-administrators/my-first-loculus.md, docs/src/content/docs/for-administrators/setup-with-k3d-and-nginx.mdx, docs/src/content/docs/for-administrators/setup-with-kubernetes.md, docs/src/content/docs/reference/helm-chart-config.mdx, kubernetes/loculus/templates/_common-metadata.tpl, kubernetes/loculus/templates/lapis-silo-database-config.yaml, kubernetes/loculus/values.schema.json, kubernetes/loculus/values.yaml, website/src/config.ts, website/src/pages/[organism]/api/_sequences.spec.ts, website/src/pages/[organism]/api/sequences.ts, website/src/pages/seq/[accessionVersion].fa/index.ts, website/src/types/referencesGenomes.ts
resolves #4691 
Breaking change in the config:
The reference genomes became a dictionary `[suborganismName, referenceGenome]`. Before:
```yaml
referenceGenomes:
nucleotideSequences:
- name: 'main'
sequence: 'NNN'
genes: []
```
After:
```yaml
referenceGenomes:
singleReference:
nucleotideSequences:
- name: 'main'
sequence: 'NNN'
genes: []
```
The key must be `singleReference` if there only one suborganism. (Maybe we'll bind logic to that specific name and it's easier to drop that requirement later compared to adding it)
This is supposed to be minimally invasive and change as few place in the code as possible. For now this simply assumes that each organism has exactly one reference genome configured (handling multiple ones in the code will be the next step).
🚀 Preview: …
=> feat!(kubernetes): [CFG] add support for multiple reference genomes

website/src/routes/extraTopNavigationItems.ts, website/src/routes/navigationItems.ts
This refactoring is needed for https://github.com/pathoplexus/pathoplexus/pull/590 so that the top navigation for tools can be organism-specific.
🚀 Preview: https://extra-sequence-related-na.loculus.org
=> refactor!(website): enable extra sequence-related nav items in Pathoplexus

ena-submission/config/defaults.yaml, ena-submission/scripts/deposition_dry_run.py, ena-submission/scripts/test_ena_submission.py, ena-submission/src/ena_deposition/config.py, ena-submission/src/ena_deposition/create_sample.py, ena-submission/src/ena_deposition/ena_submission_helper.py, ena-submission/test/test_sample_request_gisaid.xml, kubernetes/loculus/values.yaml
Based on #4713 by @anna-parker
Refactor of the biosample mapping function `get_sample_attributes` that simplifies the config and adds support for optional extra fields.
This is so we can add GISAID accession as a Biosample attribute.
Adds a test that this actually works.
Breaking config changes:
- removes `metadata_mapping_mandatory_field_defaults`
- these are added through `default: "..."` entries in the `metadata_mapping` dict
Example:
```yaml
metadata_mapping:
'host age':
loculus_fields: [hostAge]
metadata_mapping_mandatory_field_defaults:
'host age': 'not provided'
```
becomes
```yaml
metadata_mapping:
'host age':
loculus_fields: [hostAge]
default: 'not provided'
```
resolves https://github.com/pathoplexus/ena-submission/issues/91
=> feat!(deposition): simplify biosample mapping config, support optional extra metadata fields

preprocessing/nextclade/src/loculus_preprocessing/backend.py
It just showed:
`INFO:loculus_preprocessing.backend:Unprocessed data from backend: status code 200, request id: {response.headers.get('x-request-id')}`
=> fix(preprocessing): fix request id in log message

.github/dependabot.yml
resolves: https://github.com/loculus-project/loculus/issues/4468
The issue in question should have been fixed upstream in Astro - https://github.com/withastro/astro/issues/13989
=> chore(ci): Unignore astro for dependabot

backend/src/main/kotlin/org/loculus/backend/controller/SubmissionController.kt, backend/src/main/kotlin/org/loculus/backend/controller/SubmissionControllerDescriptions.kt
Resolves #4801
resolves #
🚀 Preview: https://swagger-fix.loculus.org
=> doc(backend): Add description to `/revise`'s fileMapping param

ingest/scripts/heuristic_group_segments.py, ingest/scripts/parse_nextclade_sort_output.py, ingest/scripts/prepare_metadata.py, kubernetes/loculus/values.yaml
resolves #
Main is failing with the error 
```
File "/package/scripts/heuristic_group_segments.py", line 145, in main
segment = values["segment"]
~~~~~~^^^^^^^^^^^
KeyError: 'segment'
```
`segment` is a keyword in the heuristic grouping script. However, in the enteroviruses config we renamed `segment` to genotype. This rename meant that `segment` was nolonger a field in the metadata - leading the heuristic grouping script to break. This PR should ensure that even if we rename `segment` the `segment` field should stay in the metadata as it is a required field for grouping.
This PR also covers the case where nextclade sort assigns a segment to a sequence which is not a valid segment - in this case we also drop these matches. This is important as the backend (for now) does not allow …
=> feat(ingest): never remove segment field from metadata and filter out nextclade sort matches that are not supported

preprocessing/nextclade/README.md
While all our code is still in progress, the nextclade pipeline is no more so
resolves #
=> docs(prepro): Remove reference to nextclade pipeline being a work in progress

kubernetes/loculus/values.schema.json, preprocessing/nextclade/src/loculus_preprocessing/config.py, preprocessing/nextclade/src/loculus_preprocessing/prepro.py, preprocessing/nextclade/tests/factory_methods.py, preprocessing/nextclade/tests/multi_segment_config.yaml, preprocessing/nextclade/tests/test_nextclade_preprocessing.py
resolves https://github.com/loculus-project/loculus/issues/4698, https://github.com/loculus-project/loculus/issues/4764
1. make `alignment_requirement` an enum, drop unused `reference_length`, reorder config options
2. determine if no segment aligned without using metadata (will now work correctly even when no nextclade metadata fields are used) -> add tests for case where there is no metadata to ensure this always works without errors
3. Add tests for alignment_requirement=ANY` config option
=> feat(prepro): change how `alignment_requirement` errors are determined and add tests

preprocessing/nextclade/src/loculus_preprocessing/prepro.py, preprocessing/nextclade/tests/test_nextclade_preprocessing.py
resolves #https://github.com/loculus-project/loculus/issues/4765
=> feat(prepro): do not show "No segment aligned" error for single segmented organisms

backend/src/main/kotlin/org/loculus/backend/service/submission/ProcessedDataPostprocessor.kt, backend/src/main/kotlin/org/loculus/backend/service/submission/ProcessedSequenceEntryValidator.kt, backend/src/main/kotlin/org/loculus/backend/service/submission/ProcessedSequencesPostprocessor.kt, backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmitProcessedDataEndpointTest.kt, backend/src/test/kotlin/org/loculus/backend/service/ProcessedSequencesPostprocessorTest.kt, preprocessing/nextclade/src/loculus_preprocessing/prepro.py, preprocessing/nextclade/tests/factory_methods.py, preprocessing/nextclade/tests/test_nextclade_preprocessing.py, preprocessing/specification.md
resolves https://github.com/loculus-project/loculus/issues/4814, resolves https://github.com/loculus-project/loculus/issues/4763
Similar to in https://github.com/loculus-project/loculus/pull/3232 now that we have multi-pathogens we also want to facilitate the easy addition of new "segments" (i.e. suborganisms) and their genes. 
We can do this again in an efficient way where we do not store nulls in the backend but impute the `null` entries while streaming - this also means that we can drop the requirement on prepro to add nulls for all "missing" segments and genes - decreasing the amount of data we have to stream.
This PR omits `null` entries and empty lists for nucleotide and amino acid sequences as well as insertions.
🚀 Preview: https://sequence-hydration.loculus.org
=> feat(backend): omit nulls in insertions and sequences and do not require prepro to upload null sequences

website/src/components/Submission/SubmissionGroupSelector.tsx
- remove extra left margin from group selector so the group icon aligns with the review page title
********
=> fix(website): align group icon on review page

preprocessing/nextclade/src/loculus_preprocessing/datatypes.py, preprocessing/nextclade/src/loculus_preprocessing/prepro.py, preprocessing/nextclade/src/loculus_preprocessing/processing_functions.py, preprocessing/nextclade/src/loculus_preprocessing/sequence_checks.py, preprocessing/nextclade/tests/test_nextclade_preprocessing.py
resolves #
Always writing out the full annotation type annoyed me so I created some constructors and did a refactor - this significantly decreases the lines of code and is IMO much easier to read
=> refactor(prepro): add a creation classmethod to the ProcessingAnnotation and use

kubernetes/loculus/values.yaml
Somehow I didn't test https://github.com/loculus-project/loculus/pull/4848 well enough - the dummy-organism needs `PangoLineage` not `lineage` and is rejecting the `lineage field.
🚀 Preview: https://dummy-fix.loculus.org
=> Fix dummy-organism `lineage` field not found error

ingest/scripts/call_loculus.py
resolves https://github.com/loculus-project/loculus/issues/4856#issuecomment-3187807064
I would like to have this on genspectrum before I do db surgery
=> feat(ingest): fix `submissionId` misnaming in cronjob

kubernetes/loculus/templates/_common-metadata.tpl, kubernetes/loculus/values.schema.json, kubernetes/loculus/values.yaml, website/src/components/SequenceDetailsPage/getDataTableData.spec.ts, website/src/components/SequenceDetailsPage/getDataTableData.ts, website/src/components/SequenceDetailsPage/getTableData.ts, website/src/components/SequenceDetailsPage/types.ts, website/src/types/config.ts
This PR introduces a new `orderOnDetailsPage` property for metadata fields that allows explicit control over the display order of fields on the sequence details page. Previously, fields were displayed in a relatively unspecified order, making it difficult to create a logical and user-friendly layout. Headed groups are sorted by the mean of their members' orders.
- **Added `orderOnDetailsPage` property to metadata schema** (`values.schema.json`)
- Type: number
- Description: "Determines the order on the sequence details page"
- Optional property that can be added to any metadata field
- **Updated template processing** (`_common-metadata.tpl`)
- Template now includes `orderOnDetailsPage` values when defined
- Properly propagates the property through the configuration pipeline
- **Frontend …
=> feat!(website): add details page ordering

docs/src/content/docs/for-administrators/setup-with-k3d-and-nginx.mdx
This fixes a missing line in the "Setup with k3d and nginx" tutorial. It is needed so that the Backend Swagger knows where it is and loads the config from the right location.
=> fix(docs): fix missing proxy header in k3d/nginx tutorial

kubernetes/loculus/templates/_urls.tpl
I'm working on a prod deployment of Loculus, and I disabled the development S3 and configured my own bucket, and I found this setting still in my backend Pod:
```yaml
- name: S3_BUCKET_ENDPOINT
value: http://localhost:8084
```
The backend also generates pre-signed URLs with the `localhost:8084`, instead of the proper endpoint.
I changed it so that the backend uses the user-given endpoint.
I've tested this in our setup, with a Hetzner bucket, and it's working.
n/A
- ~~The implemented feature is covered by appropriate, automated tests.~~
=> fix(deployment): Make the backend use the user given S3-endpoint for the file-sharing feature

docs/src/content/docs/for-administrators/configuring-extra-files.md
I've re-ordered the sections, divided it into Loculus and S3 config, and gave an example for a CORS policy.
docs page preview: https://docs-update-s3-cors-info.loculus.org/for-administrators/configuring-extra-files/
🚀 Preview: https://update-s3-cors-info.loculus.org
=> docs(extra-files): Clean up tutorial, add more info

kubernetes/loculus/values.schema.json, kubernetes/loculus/values.yaml, website/src/components/SearchPage/DownloadDialog/DownloadDialog.spec.tsx, website/src/components/SearchPage/DownloadDialog/DownloadForm.tsx, website/src/components/SearchPage/DownloadDialog/SequenceFilters.tsx, website/src/components/SearchPage/SearchForm.spec.tsx, website/src/components/SearchPage/SearchFullUI.spec.tsx, website/src/components/SearchPage/fields/MutationField.spec.tsx, website/src/components/SequenceDetailsPage/DataTable.tsx, website/src/components/SequenceDetailsPage/RevocationEntryDataTable.astro, website/src/components/SequenceDetailsPage/SequenceContainer.spec.tsx, website/src/components/SequenceDetailsPage/SequenceDataUI.tsx, website/src/components/SequenceDetailsPage/SequencesContainer.tsx, website/src/components/SequenceDetailsPage/getTableData.spec.ts, website/src/components/SequenceDetailsPage/getTableData.ts, website/src/components/Submission/FileUpload/SequenceEntryUploadComponent.tsx, website/src/components/Submission/FormOrUploadWrapper.spec.tsx, website/src/components/Submission/FormOrUploadWrapper.tsx, website/src/components/Submission/SubmissionForm.spec.tsx, website/src/components/common/ActiveFilters.spec.tsx, website/src/config.ts, website/src/pages/[organism]/submission/edit/[accession]/[version].astro, website/src/pages/seq/[accessionVersion]/details.json.ts, website/src/pages/seq/[accessionVersion]/getSequenceDetailsTableData.ts, website/src/pages/seq/[accessionVersion]/index.astro, website/src/types/config.ts, website/src/types/detailsJson.ts, website/src/types/referencesGenomes.ts, website/src/utils/mutation.spec.ts, website/src/utils/mutation.ts
resolves #4784
This PR contains:
* squashed versions of #4767 and #4770 because they are required to get a working preview (they should be dropped before merging)
* compute the suborganism from the respective LAPIS field
* Still to do: How do we configure which field that should be? Add a field to `defaultOrganisms.[organism].schema.website`?
* making the `ReferenceGenomesSequenceNames` a dictionary `{ [suborganism]: <the object with the names> } and propagate this through the website (a lot of noise...)
* read the first value of that dictionary almost everywhere
* This is to keep the website in a working state until it's properly implemented everywhere. The single pathogen case will stay untouched. In the multi pathogen case, some things that are shown on the website might be wrong until …
=> feat(website): multi pathogen support: sequence details page: only show relevant mutation references

website/src/hooks/useUrlParamState.ts
It's a derived state, let's make it a proper derived state. We don't need a separate, intermediate state that we need to be careful about syncing correctly.
- `halfScreen` and `selectedSeq` still seem to work as before
🚀 Preview: https://useurlparamstate.loculus.org
=> refactor(website): don't duplicate the state in useUrlParamState

ingest/Snakefile, ingest/config/defaults.yaml, kubernetes/loculus/values.yaml
resolves #
This uses the newly merged CCHF dataset that now does QC and lineages! See details here: https://github.com/nextstrain/nextclade_data/pull/265
It also vastly improves alignment, especially of the M segment which has high variability at the start and end of the sequences - leading to many alignments previously failing the QC scores. 
Uses new lineage file: https://github.com/pathoplexus/silo-lineage-hierarchy-definitions/blob/main/definitions/cchf/S/2025-09-12/lineages.yaml
To release on PPX this requires a pipeline version update: https://github.com/pathoplexus/pathoplexus/pull/658 and the regroup-revoke cronjob will have to be run once.
Results: Exactly 1 sequence must be revoked as it can no longer be grouped : https://loculus.slack.com/archives/C07FP0BGHDZ/p1757518656855529 …
=> feat!(config): use new cchf dataset

kubernetes/loculus/values.yaml
This is required for #4983.
This changes the SILO image to include the cherry picked commit:
[feat(silo): add a health endpoint that checks whether the api is able to answer requests](https://github.com/GenSpectrum/LAPIS-SILO/pull/978/commits/789ddf5b68872940b330c9b271631b6097009cc9)
See:
https://github.com/GenSpectrum/LAPIS-SILO/pull/978/commits
🚀 Preview: https://update-silo-0-7-10-2.loculus.org
=> chore(deps): bump SILO to use backported health-check in version 0.7.10.2

kubernetes/loculus/templates/silo-deployment.yaml
Uses https://github.com/GenSpectrum/LAPIS-SILO/pull/979 to ensure we restart SILO if it gets unhealthy (sorry for the delay I didn't notice this get added at the time)
🚀 Preview: https://silo-liveness.loculus.org
=> feat(deployment): Add liveness probe to silo-deployment.yaml

.github/workflows/ena-submission-unit-tests.yaml, .github/workflows/format-ena-deposition-on-dispatch.yml, .pre-commit-config.yaml, ena-submission/environment.yml
Prevents breakage of CI on main due to new rules when new ruff version is released (it just happened).
This uses a consistent ruff version defined in environment.yml.
=> chore(ci): use consistent ruff version to format/check ena-submission

website/src/components/SearchPage/DownloadDialog/DownloadDialog.spec.tsx, website/src/components/SearchPage/DownloadDialog/DownloadForm.tsx, website/src/components/SearchPage/DownloadDialog/OptionBlock.tsx, website/src/components/SequenceDetailsPage/SequencesDisplay/SequencesContainer.tsx, website/src/components/SequenceDetailsPage/SequencesDisplay/getSequenceNames.tsx, website/src/utils/sequenceTypeHelpers.ts
resolves #4997
Make sure that the correct segments and genes are displayed and downloaded. All downloads should now work in the multi pathogen case.
* When downloading raw sequences when no suborganism is selected yet, it will download all segments that are not null (#5092 is still open here).
* When downloading raw sequences when a suborganism is selected, it will download the corresponding segment only.
- sequence download works
- for EV as expected
- for west nile as before
=> feat(website): multi pathogen support: show correct segments in download modal

kubernetes/loculus/templates/_common-metadata.tpl
https://github.com/loculus-project/loculus/pull/5028 currently has failing CI since the helm lint fails. I think it's due to this change: 
https://github.com/loculus-project/loculus/commit/ef6db73e8b65d1045523b7808f03ea6df10de583
I believe that this PR is the fix. Please check.
=> fix(kubernetes): don't generate ENA deposition config if there is no config for it

ena-submission/config/defaults.yaml, ena-submission/src/ena_deposition/check_external_visibility.py, ena-submission/src/ena_deposition/config.py
There were potential test failures due to timeouts being potentially too short. Looking into it I noticed that we were using timeout configs inconsistently. This is low risk, low impact stuff.
---
Separate public API visibility check timeouts from submission API timeouts:
- Add `ena_public_search_timeout_seconds` (120s) for ENA browser API checks
- Add `ncbi_public_search_timeout_seconds` (120s) for NCBI visibility checks
- Previously used `ena_http_timeout_seconds` (60s) for both submission and public checks
- NCBI non-GCA checks were hardcoded to 30s
This fixes timeout issues with NCBI visibility checks by increasing from 30s to 120s.
=> fix(deposition): separate and increase timeouts for public visibility checks

website/src/utils/mutation.spec.ts, website/src/utils/mutation.ts
This looks like broken escaping to me, but `.` doesn't need to be escaped here?
On current main without the fix:
=> fix(website): don't allow `\` in mutations in mutation search

integration-tests/tests/specs/features/revise-sequence.spec.ts, website/src/components/ReviewPage/SequencesDialog.spec.tsx, website/src/components/ReviewPage/SequencesDialog.tsx
resolves #4998
Before:
After:
- see screenshots
=> feat(website): review page, sequences dialog: only show sequences that exist for that entry

.github/workflows/helm-schema-lint.yaml, .pre-commit-config.yaml, kubernetes/AGENTS.md, kubernetes/CLAUDE.md, kubernetes/loculus/values.schema.json
Extend the JSON Schema validation to enforce type requirements for metadata configuration options (building on #5184):
- generateIndex requires type: string
- autocomplete requires type: string, int, float, number, or boolean
- enableSubstringSearch requires type: string
- lineageSystem requires type: string
- rangeSearch requires numeric or date types (int, float, number, or date)
- rangeOverlapSearch requires numeric or date types (int, float, number, or date)
I also add AGENTS.md (and CLAUDE.md symlink) to kubernetes dir to instruct to run prettier.
I also added a pre-commit hook to prettier-format the schema automatically and validate it with helm lint. The helm lint action now gets the values.yamls applied over each other the way we do it in practice (preview on top of basic values). …
=> feat(k8s): add 6 more metadata schema constraints to values.schema.json

kubernetes/loculus/templates/silo-deployment.yaml, kubernetes/loculus/values.yaml
This reverts commit bf2e75a906fc64d67a028e75f655449d0e03027e from #5109
SILO 0.7.10.3 seems to make the memory leak worse rather than better.
I downloaded unaligned nucleotide sequences a couple hundred times using curl and compared memory increases of 0.7.10.3 vs 0.7.10.2 (using pyimport preview as it uses the 0.7.10.2).
In both cases, SILO memory usage increase a lot, up from ~120MB prior - but 0.7.10.3 is a lot worse than 0.7.10.2 and definitely not better - as one would expect based on PR description (it's not quite clear which issue it should have fixed but it sounds like memory usage was supposed to improve).
With a few hundred downloads, current main (with 0.7.10.3) saw a 9-fold increase in SILO RAM usage for west nile, from 124MB to 1080MB while previous version 0.7.10.2 increased …
=> fix(deps): Revert 'chore(deps): update silo to 0.7.10.3 (#5109)'
